save-backend/src/main/kotlin/org/cqfn/save/backend/configs/H2.kt
save-backend/src/main/kotlin/org/cqfn/save/backend/repository/ProjectRepository.kt
save-backend/src/test/kotlin/org/cqfn/save/backend/DownloadFilesTest.kt
save-backend/src/test/kotlin/org/cqfn/save/backend/H2DatabaseTest.kt
save-common/src/commonMain/kotlin/org/cqfn/save/entities/Annotations.kt
save-common/src/commonMain/kotlin/org/cqfn/save/entities/Project.kt
save-common/src/jvmMain/kotlin/org/cqfn/save/entities/Annotations.kt

* Made clean up
This pull request closes #26

Feature. Make save consistent with diktat

---

save-agent/src/nativeMain/kotlin/org/cqfn/save/agent/SaveAgent.kt
save-common/src/commonMain/kotlin/org/cqfn/save/agent/AgentState.kt

* Added states CLI_FAILED, BACKEND_FAILED, BACKEND_UNREACHABLE
* Changed logic in Agent
Closes #17

Support more granular AgentStates instead of ERROR

---

build.gradle.kts
docker-compose.yaml.template
save-backend/src/main/kotlin/org/cqfn/save/backend/postprocessor/DockerSecretsDatabaseProcessor.kt
save-backend/src/main/resources/application-dev.properties
save-backend/src/main/resources/application-prod.properties
save-backend/src/main/resources/application.properties
save-backend/src/main/resources/spring.factories
save-backend/src/test/kotlin/org/cqfn/save/backend/DatabaseTest.kt
save-backend/src/test/resources/application.properties

* Added secrets to server
* Fixed bugs with liquibase
This pull request closes #12

Feature. Docker secrets enabled.

---

.run/save [deployLocal].run.xml
build.gradle.kts
buildSrc/src/main/kotlin/org/cqfn/save/buildutils/DockerStackConfiguration.kt
docker-compose.yaml.template
save-backend/src/main/resources/application-dev.properties
save-deploy/README.md

* Added mysql with default password and default database to docker-compose.yaml.template in dev profile
* Added startMysqlDb task
* Updated save-deploy/README.md
* Added run configuration for IDEA
* Fixed application-dev.properties
Closes #39

Added configuration for local database

---

buildSrc/src/main/kotlin/Versions.kt
save-preprocessor/build.gradle.kts
save-preprocessor/src/main/kotlin/org/cqfn/save/preprocessor/SaveApplication.kt
save-preprocessor/src/main/kotlin/org/cqfn/save/preprocessor/config/ConfigProperties.kt
save-preprocessor/src/main/kotlin/org/cqfn/save/preprocessor/controllers/DownloadProject.kt
save-preprocessor/src/test/kotlin/org/cqfn/save/preprocessor/DownloadProjectTest.kt

Added configuration for preprocessor
closes #38

Preprocessor: add class for configuration properties

---

save-agent/README.md
save-agent/build.gradle.kts
save-agent/src/nativeMain/kotlin/org/cqfn/save/agent/SaveAgent.kt
save-agent/src/nativeTest/kotlin/org/cqfn/save/agent/SaveAgentTest.kt
save-common/src/commonMain/kotlin/org/cqfn/save/agent/ExecutionLogs.kt

* Added file writing in CLI stub
* Added sending logs to orchestrator
closes #15

Orchestrator: store logs of SAVE SAVE CLI

---

db/changelog/v-1/db.changelog-v-1.xml
db/changelog/v-1/event_scheduler.xml

* Created mysql event scheduler
closes #46

Database: Configure retention for tests and test_executions

---

db/changelog/v-1/11-changeset-test-agent-insert-data.xml
db/changelog/v-1/12-changeset-test-insert-data.xml
db/changelog/v-1/db.changelog-v-1.xml
save-backend/src/main/kotlin/org/cqfn/save/backend/configs/ConfigProperties.kt
save-backend/src/main/kotlin/org/cqfn/save/backend/repository/TestRepository.kt
save-backend/src/main/kotlin/org/cqfn/save/backend/service/TestService.kt
save-backend/src/main/resources/application.properties
save-backend/src/test/kotlin/org/cqfn/save/backend/SaveResultTest.kt
save-backend/src/test/kotlin/org/cqfn/save/backend/controller/TestInitializeControllerTest.kt
save-backend/src/test/resources/application.properties

* Sending batches logic added.
* Added tests
This PR closes #51

Feature. Orchestrator & backend: Retrieve batches of test IDs from DB

---

db/changelog/v-1/event_scheduler.xml

Database: bug dropAll events

---

buildSrc/build.gradle.kts
buildSrc/src/main/kotlin/Versions.kt
diktat-analysis.yml
save-agent/build.gradle.kts
save-agent/src/nativeMain/kotlin/org/cqfn/save/agent/SaveAgent.kt
save-backend/src/test/kotlin/org/cqfn/save/backend/utils/MySqlExtension.kt
save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/views/CollectionView.kt

* Rearranged versions in Versions.kt
* Bump kotlin to 1.4.32
* Bump ktor to 1.5.3
* Bump docker-java-api, liquibase and uuid
* Bump diktat to 0.5.0 and fixed code style

Infra: Dependency updates

---

save-backend/src/test/kotlin/org/cqfn/save/backend/DownloadFilesTest.kt
save-backend/src/test/kotlin/org/cqfn/save/backend/SaveResultTest.kt
save-backend/src/test/kotlin/org/cqfn/save/backend/controller/CloningRepositoryControllerTest.kt
save-backend/src/test/resources/application.properties
save-preprocessor/src/main/kotlin/org/cqfn/save/preprocessor/controllers/DownloadProjectController.kt
save-preprocessor/src/test/kotlin/org/cqfn/save/preprocessor/DownloadProjectTest.kt
save-preprocessor/src/test/kotlin/org/cqfn/save/preprocessor/utils/RepositoryVolume.kt
settings.gradle.kts

* Use repeatable MockBeans annotation
* Use kotlin-friendly expectBody
* Added more tests

Improve spring tests

---

diktat-analysis.yml
save-agent/build.gradle.kts
save-agent/src/nativeMain/kotlin/org/cqfn/save/agent/AgentConfiguration.kt
save-agent/src/nativeMain/kotlin/org/cqfn/save/agent/Main.kt
save-agent/src/nativeMain/kotlin/org/cqfn/save/agent/SaveAgent.kt
save-agent/src/nativeMain/kotlin/org/cqfn/save/agent/utils/FileUtils.kt
save-agent/src/nativeMain/resources/agent.properties
save-agent/src/nativeTest/kotlin/org/cqfn/save/agent/SaveAgentTest.kt
save-orchestrator/build.gradle.kts
save-orchestrator/src/main/kotlin/org/cqfn/save/orchestrator/docker/ContainerManager.kt
save-orchestrator/src/main/kotlin/org/cqfn/save/orchestrator/service/DockerService.kt
save-orchestrator/src/test/kotlin/org/cqfn/save/orchestrator/docker/ContainerManagerTest.kt

* Added deserialization from Properties
* Added default properties file
* Changed logic in DockerService
* Refactored packaging of save-agent for inclusion in orchestrator
Closes #83

Agent: Read agent properties from file

---

docker-compose.yaml.template
save-orchestrator/src/main/kotlin/org/cqfn/save/orchestrator/config/ConfigProperties.kt
save-orchestrator/src/main/kotlin/org/cqfn/save/orchestrator/controller/AgentsController.kt
save-orchestrator/src/main/resources/application.properties
save-orchestrator/src/test/kotlin/org/cqfn/save/orchestrator/controller/agents/AgentsControllerTest.kt
save-orchestrator/src/test/resources/application.properties

- Created logic to save aget's logs
- Closes #104

Orchestrator save logs

---

db/changelog/v-1/05-changeset-test-suite-table.xml
db/changelog/v-1/13-changeset-test-suite-insert-data.xml
detekt.yml
save-agent/src/nativeMain/kotlin/org/cqfn/save/agent/SaveAgent.kt
save-agent/src/nativeTest/kotlin/org/cqfn/save/agent/SaveAgentTest.kt
save-backend/src/main/kotlin/org/cqfn/save/backend/controllers/DownloadFilesController.kt
save-backend/src/main/kotlin/org/cqfn/save/backend/service/TestService.kt
save-backend/src/main/kotlin/org/cqfn/save/backend/service/TestSuitesService.kt
save-backend/src/test/kotlin/org/cqfn/save/backend/controller/TestInitializeControllerTest.kt
save-backend/src/test/kotlin/org/cqfn/save/backend/controller/TestSuitesControllerTest.kt
save-common/src/commonMain/kotlin/org/cqfn/save/agent/Heartbeat.kt
save-common/src/commonMain/kotlin/org/cqfn/save/entities/ExecutionRequest.kt
save-common/src/commonMain/kotlin/org/cqfn/save/test/TestDto.kt
save-common/src/commonMain/kotlin/org/cqfn/save/testsuite/TestSuiteDto.kt
save-common/src/jvmMain/kotlin/org/cqfn/save/entities/TestSuite.kt
save-orchestrator/src/main/kotlin/org/cqfn/save/orchestrator/service/AgentService.kt
save-orchestrator/src/test/kotlin/org/cqfn/save/orchestrator/controller/agents/AgentsControllerTest.kt
save-orchestrator/src/test/kotlin/org/cqfn/save/orchestrator/controller/heartbeat/HeartbeatControllerTest.kt
save-preprocessor/src/main/kotlin/org/cqfn/save/preprocessor/controllers/DownloadProjectController.kt
save-preprocessor/src/test/kotlin/org/cqfn/save/preprocessor/DownloadProjectTest.kt

* Added propertiesLocationPath to TestSuite
* Added TestBatch class
* Changed API in backend
* Changed NewJonReponse
* Updated tests and luqiubase changelogs
* Turned off ForbiddenComment inspection in detekt
* Use temporary file in DownloadFileController stub
Closes #116

Support execution from sub-folder

---

save-agent/src/nativeMain/kotlin/org/cqfn/save/agent/SaveAgent.kt
save-agent/src/nativeMain/kotlin/org/cqfn/save/agent/utils/FileUtils.kt

Agent: Send execution logs even if SAVE cli has failed

---

.github/workflows/build_and_test.yml
.github/workflows/detekt.yml
.github/workflows/diktat.yml
build.gradle.kts
buildSrc/build.gradle.kts
buildSrc/src/main/kotlin/Versions.kt
buildSrc/src/main/kotlin/org/cqfn/save/buildutils/DetektConfiguration.kt
buildSrc/src/main/kotlin/org/cqfn/save/buildutils/SpringBootConfiguration.kt
detekt.yml
diktat-analysis.yml
gradle.properties
gradle/wrapper/gradle-wrapper.properties
save-agent/build.gradle.kts
save-agent/src/nativeMain/kotlin/org/cqfn/save/agent/SaveAgent.kt
save-backend/src/main/kotlin/org/cqfn/save/backend/controllers/AgentsController.kt
save-backend/src/main/kotlin/org/cqfn/save/backend/service/ExecutionService.kt
save-backend/src/main/kotlin/org/cqfn/save/backend/service/ProjectService.kt
save-backend/src/main/kotlin/org/cqfn/save/backend/service/TestService.kt
save-backend/src/test/kotlin/org/cqfn/save/backend/controller/AgentsControllerTest.kt
save-backend/src/test/kotlin/org/cqfn/save/backend/controller/JpaSpecificationTest.kt
save-backend/src/test/kotlin/org/cqfn/save/backend/controller/TestInitializeControllerTest.kt
save-common/src/commonMain/kotlin/org/cqfn/save/agent/Heartbeat.kt
save-common/src/jvmMain/kotlin/org/cqfn/save/entities/BaseEntity.kt
save-common/src/jvmMain/kotlin/org/cqfn/save/entities/Execution.kt
save-frontend/build.gradle.kts
save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/tables/TableComponent.kt
save-orchestrator/src/main/kotlin/org/cqfn/save/orchestrator/service/DockerService.kt
save-orchestrator/src/test/kotlin/org/cqfn/save/orchestrator/docker/ContainerManagerTest.kt
save-orchestrator/src/test/kotlin/org/cqfn/save/orchestrator/service/DockerServiceTest.kt

* Gradle from 6.8.3 to 6.9
* Spring, spring boot, liquibase, micrometer, diktat, mockito, ktor, testcontainers, kotlin-js wrappers
* Diktat code style
* Fixed Detekt errors

Dependency updates

---

build.gradle.kts
buildSrc/build.gradle.kts
buildSrc/src/main/kotlin/Versions.kt
buildSrc/src/main/kotlin/org/cqfn/save/buildutils/JacocoConfiguration.kt
gradle.properties
save-agent/build.gradle.kts
save-cloud-common/build.gradle.kts
save-orchestrator/src/main/kotlin/org/cqfn/save/orchestrator/service/DockerService.kt
save-orchestrator/src/test/kotlin/org/cqfn/save/orchestrator/service/DockerServiceTest.kt
save-orchestrator/src/test/resources/application.properties
save-preprocessor/src/main/kotlin/org/cqfn/save/preprocessor/service/TestDiscoveringService.kt

* Update Kotlin and related dependencies: ktor, serialization, coroutines, datetime, js-wrappers
* Update jacoco from 0.8.6 to 0.8.7
* Enable logging in docker service test
* Install tzdata in base image
Closes #98

Update Kotlin to 1.5.0

---

buildSrc/build.gradle.kts
buildSrc/src/main/kotlin/Versions.kt
save-agent/src/nativeMain/kotlin/org/cqfn/save/agent/SaveAgent.kt
save-deploy/README.md
save-frontend/build.gradle.kts
save-orchestrator/build.gradle.kts
save-orchestrator/src/main/kotlin/org/cqfn/save/orchestrator/controller/HeartbeatController.kt
save-orchestrator/src/main/kotlin/org/cqfn/save/orchestrator/service/AgentService.kt
save-orchestrator/src/test/kotlin/org/cqfn/save/orchestrator/controller/heartbeat/HeartbeatControllerTest.kt
save-preprocessor/src/test/kotlin/org/cqfn/save/preprocessor/DownloadProjectTest.kt
save-preprocessor/src/test/kotlin/org/cqfn/save/preprocessor/service/TestDiscoveringServiceTest.kt
settings.gradle.kts

* Allow manual placing of `save-cli` for snapshots
* Chain `Mono`s in `HeartbeatController` (`updateAgentStatusesWithDto` wasn't executed before)
* Provide file names in `cliArgs` for `save-cli`
* Code cleanup
* Renamed rootProject, fixed build
* Updated dependencies
Closes #134

Fixes & improvements

---

buildSrc/src/main/kotlin/Versions.kt
buildSrc/src/main/kotlin/org/cqfn/save/buildutils/VersioningConfiguration.kt
save-agent/build.gradle.kts
save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/TopBar.kt
save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/views/ProjectView.kt
save-orchestrator/build.gradle.kts
save-preprocessor/build.gradle.kts
save-preprocessor/src/main/kotlin/org/cqfn/save/preprocessor/controllers/DownloadProjectController.kt
save-preprocessor/src/main/kotlin/org/cqfn/save/preprocessor/service/TestDiscoveringService.kt
save-preprocessor/src/test/kotlin/org/cqfn/save/preprocessor/DownloadProjectTest.kt
save-preprocessor/src/test/kotlin/org/cqfn/save/preprocessor/service/TestDiscoveringServiceTest.kt
save-preprocessor/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker

* Changed logic
* Added tests
* Fixed link to HistoryView
* Reverted liquibase version
* Added a common save-cli snapshot version accessor for agent and orchestrator
Closes #133

Discover tests using save-core

---

save-agent/src/nativeMain/kotlin/org/cqfn/save/agent/AgentConfiguration.kt
save-orchestrator/src/main/kotlin/org/cqfn/save/orchestrator/docker/ContainerManager.kt
save-orchestrator/src/main/kotlin/org/cqfn/save/orchestrator/service/DockerService.kt
save-orchestrator/src/test/kotlin/org/cqfn/save/orchestrator/docker/ContainerManagerTest.kt

Run sh file

---

.github/workflows/build_and_test.yml
.github/workflows/diktat.yml
buildSrc/build.gradle.kts
buildSrc/src/main/kotlin/Versions.kt
buildSrc/src/main/kotlin/org/cqfn/save/buildutils/DetektConfiguration.kt
save-backend/src/main/kotlin/org/cqfn/save/backend/SaveApplication.kt
save-backend/src/main/kotlin/org/cqfn/save/backend/controllers/ExecutionController.kt
save-orchestrator/src/main/kotlin/org/cqfn/save/orchestrator/SaveOrchestrator.kt
save-preprocessor/src/main/kotlin/org/cqfn/save/preprocessor/SaveApplication.kt
save-preprocessor/src/main/kotlin/org/cqfn/save/preprocessor/service/TestDiscoveringService.kt
save-preprocessor/src/test/kotlin/org/cqfn/save/preprocessor/service/TestDiscoveringServiceTest.kt

* SAVE 0.1.0
* Diktat 1.0.0-rc.1
* Other updates

Version updates

---

save-cloud-common/src/jvmMain/kotlin/org/cqfn/save/entities/Test.kt
save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/views/ExecutionView.kt
save-preprocessor/src/main/kotlin/org/cqfn/save/preprocessor/service/TestDiscoveringService.kt
save-preprocessor/src/test/kotlin/org/cqfn/save/preprocessor/service/TestDiscoveringServiceTest.kt

* Changed logic
* Updated tests
Closes #158, even though error on frontend was just a consequence of deeper error in logic

Store tests with relative path

---

save-backend/src/main/kotlin/org/cqfn/save/backend/controllers/ExecutionController.kt
save-backend/src/main/kotlin/org/cqfn/save/backend/repository/ExecutionRepository.kt
save-backend/src/main/kotlin/org/cqfn/save/backend/service/ExecutionService.kt
save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/views/ProjectView.kt

* Added logic on backend
* Update frontend
Closes #160

Frontend: Support /history/latest in ProjectView.kt

---

save-cloud-common/src/commonMain/kotlin/org/cqfn/save/execution/ExecutionDto.kt
save-cloud-common/src/jvmMain/kotlin/org/cqfn/save/entities/Execution.kt

Fixed NPE in execution

---

save-backend/src/main/kotlin/org/cqfn/save/backend/repository/TestRepository.kt
save-backend/src/main/kotlin/org/cqfn/save/backend/service/ExecutionService.kt
save-cloud-common/src/commonMain/kotlin/org/cqfn/save/execution/ExecutionUpdateDto.kt
save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/views/FallbackView.kt

Update execution end time after it completes

---

save-backend/src/main/kotlin/org/cqfn/save/backend/controllers/CloneRepositoryController.kt
save-backend/src/test/kotlin/org/cqfn/save/backend/CloneRepoTest.kt
save-backend/src/test/kotlin/org/cqfn/save/backend/controller/CloningRepositoryControllerTest.kt
save-cloud-common/src/commonMain/kotlin/org/cqfn/save/entities/ExecutionRequest.kt
save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/views/CreationView.kt
save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/views/ProjectView.kt
save-preprocessor/src/main/kotlin/org/cqfn/save/preprocessor/controllers/DownloadProjectController.kt
save-preprocessor/src/test/kotlin/org/cqfn/save/preprocessor/DownloadProjectTest.kt

###What's done:
- Changed logic
- Closes #189 
- Closes #180

Change execution in all cases

---

db/changelog/db.changelog-master.xml
db/changelog/v-2/01-changeset-test.xml
db/changelog/v-2/10-test-update-data.xml
db/changelog/v-2/db.changelog-v-2.xml
save-agent/src/linuxX64Main/kotlin/org/cqfn/save/agent/SaveAgent.kt
save-backend/src/main/kotlin/org/cqfn/save/backend/repository/TestExecutionRepository.kt
save-backend/src/main/kotlin/org/cqfn/save/backend/service/TestExecutionService.kt
save-backend/src/main/kotlin/org/cqfn/save/backend/service/TestService.kt
save-backend/src/test/kotlin/org/cqfn/save/backend/controller/TestExecutionControllerTest.kt
save-backend/src/test/kotlin/org/cqfn/save/backend/controller/TestInitializeControllerTest.kt
save-cloud-common/src/commonMain/kotlin/org/cqfn/save/agent/TestExecutionDto.kt
save-cloud-common/src/commonMain/kotlin/org/cqfn/save/test/TestDto.kt
save-cloud-common/src/jvmMain/kotlin/org/cqfn/save/entities/Test.kt
save-cloud-common/src/jvmMain/kotlin/org/cqfn/save/entities/TestExecution.kt
save-orchestrator/src/test/kotlin/org/cqfn/save/orchestrator/controller/heartbeat/HeartbeatControllerTest.kt
save-preprocessor/src/main/kotlin/org/cqfn/save/preprocessor/service/TestDiscoveringService.kt

* Update entities
* Updated liquibase changelogs
* Updated logic
Closes #176

Add column with plugin_name to test and test_execution tables

---

buildSrc/src/main/kotlin/Versions.kt
save-frontend/build.gradle.kts
save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/TopBar.kt
save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/modal/ErrorModal.kt
save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/modal/LogoutModal.kt
save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/views/CreationView.kt
save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/views/ProjectView.kt

* Changed groupId
* Updated API usages
* Bump version

Update dependency on kotlin-js-wrappers

---

save-backend/src/main/kotlin/org/cqfn/save/backend/controllers/ExecutionController.kt
save-backend/src/main/kotlin/org/cqfn/save/backend/repository/ExecutionRepository.kt
save-backend/src/main/kotlin/org/cqfn/save/backend/service/ExecutionService.kt
save-cloud-common/src/commonMain/kotlin/org/cqfn/save/execution/ExecutionStatus.kt
save-frontend/src/main/kotlin/org/cqfn/save/frontend/App.kt
save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/tables/TableComponent.kt
save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/views/CollectionView.kt
save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/views/ExecutionView.kt
save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/views/HistoryView.kt
save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/views/ProjectView.kt
save-frontend/src/main/kotlin/org/cqfn/save/frontend/externals/fontawesome/Icons.kt
save-frontend/src/main/kotlin/org/cqfn/save/frontend/utils/RequestUtils.kt

* Added icon
* Fixed serverPaging request
* Refactor deserialization from Fetch API
* Fix /latestExecution when there are no executions
Closes #196

Frontend: Display execution status icon

---

save-backend/src/main/kotlin/org/cqfn/save/backend/controllers/CloneRepositoryController.kt
save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/views/CreationView.kt
save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/views/ProjectView.kt

###What's done:
- Fixed bug
- Closes #203

Fixed wrong encode/decode

---

build.gradle.kts
buildSrc/build.gradle.kts
buildSrc/src/main/kotlin/org/cqfn/save/buildutils/SpringBootConfiguration.kt
buildSrc/src/main/kotlin/org/cqfn/save/buildutils/VersioningConfiguration.kt
gradle.properties
save-backend/src/main/kotlin/org/cqfn/save/backend/controllers/ProjectController.kt
save-backend/src/main/kotlin/org/cqfn/save/backend/controllers/TestExecutionController.kt
save-backend/src/main/kotlin/org/cqfn/save/backend/service/GitService.kt
save-backend/src/main/kotlin/org/cqfn/save/backend/service/ProjectService.kt
save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/tables/TableComponent.kt
save-frontend/src/main/kotlin/org/cqfn/save/frontend/utils/RequestUtils.kt
save-orchestrator/src/main/kotlin/org/cqfn/save/orchestrator/config/Beans.kt
save-orchestrator/src/main/resources/application.properties
save-preprocessor/src/main/kotlin/org/cqfn/save/preprocessor/controllers/DownloadProjectController.kt
save-preprocessor/src/test/kotlin/org/cqfn/save/preprocessor/DownloadProjectTest.kt

* Update diktat
* Introduce -Psave.development
* Fix code style

Infrastructure improvements

---

save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/tables/TableComponent.kt
save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/views/ExecutionView.kt
save-preprocessor/src/test/kotlin/org/cqfn/save/preprocessor/service/TestDiscoveringServiceTest.kt

* Correctly unpack array for useEffect (it accepts `vararg`, so array needs to be unpacked)
* Minor changes in TableComponent
Closes #212

Fix multiple re-renders in TableComponent

---

buildSrc/src/main/kotlin/org/cqfn/save/buildutils/VersioningConfiguration.kt
docker-compose.yaml.template
save-orchestrator/src/main/kotlin/org/cqfn/save/orchestrator/service/DockerService.kt
save-preprocessor/src/main/kotlin/org/cqfn/save/preprocessor/controllers/DownloadProjectController.kt
save-preprocessor/src/test/kotlin/org/cqfn/save/preprocessor/DownloadProjectTest.kt

* Minor fixes: remove temp files, change `projectRootRelativePath` in `saveBinaryFile()` to more correct, logging polishing

Minor fixes

---

save-orchestrator/src/main/kotlin/org/cqfn/save/orchestrator/service/DockerService.kt

Check image and container existence before removing

---

buildSrc/src/main/kotlin/org/cqfn/save/buildutils/DockerStackConfiguration.kt
save-backend/src/main/kotlin/org/cqfn/save/backend/controllers/CloneRepositoryController.kt
save-backend/src/test/kotlin/org/cqfn/save/backend/CloneRepoTest.kt
save-backend/src/test/kotlin/org/cqfn/save/backend/controller/CloningRepositoryControllerTest.kt
save-cloud-common/src/commonMain/kotlin/org/cqfn/save/domain/Sdk.kt
save-cloud-common/src/commonMain/kotlin/org/cqfn/save/entities/ExecutionRequest.kt
save-deploy/reverse-proxy.conf
save-frontend/detekt.yml
save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/basic/CheckBoxGrid.kt
save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/basic/FileUploader.kt
save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/basic/SdkSelection.kt
save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/views/CollectionView.kt
save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/views/ProjectView.kt
save-preprocessor/src/main/kotlin/org/cqfn/save/preprocessor/controllers/DownloadProjectController.kt
save-preprocessor/src/test/kotlin/org/cqfn/save/preprocessor/DownloadProjectTest.kt

* Accept arbitrary number of files in `/submitExecutionRequestBin` and `/uploadBin`
* Accept files in `/submitExecutionRequest` and `/upload`
* Frontend: Accept multiple files from ProjectView, minor refactorings
* Frontend: extract `CheckBoxComponent`, `SdkSelection` and `FileUploader` into separate files
* Frontend: Fix missing column in CollectionView
* Increase `client_max_body_size` in nginx configuration
* Introduce `ExecutionRequestBase`
In `/rerunExecution` for GIT flow should also restore binaries (created #231)
Closes #211

Upload multiple files 

---

save-backend/src/main/kotlin/org/cqfn/save/backend/scheduling/StandardSuitesUpdateScheduler.kt
save-preprocessor/src/main/kotlin/org/cqfn/save/preprocessor/controllers/DownloadProjectController.kt

* Fix cron expression
* Fix controller in preprocessor (immediately return and clone repo in background task)

Fix StandardSuitesUpdateScheduler

---

buildSrc/build.gradle.kts
buildSrc/src/main/kotlin/Versions.kt
save-frontend/src/main/kotlin/org/cqfn/save/frontend/App.kt
save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/TopBar.kt
save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/basic/Card.kt
save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/basic/FileUploader.kt
save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/views/HistoryView.kt

* Update kotlin-wrappers: update usages of kotlin-react-router API in App.kt
* Fixed react warning
* Kotlin 1.5.31 and other dependency updates

Dependency updates 

---

save-agent/src/linuxX64Main/kotlin/org/cqfn/save/agent/AgentConfiguration.kt
save-agent/src/linuxX64Main/resources/agent.properties
save-orchestrator/src/main/kotlin/org/cqfn/save/orchestrator/service/DockerService.kt

* Removed code
* Minor refactoring
Closes #255

Remove usages of `run.sh` from SAVE repo

---

docker-compose.yaml.template
gradle.properties
save-backend/src/main/kotlin/org/cqfn/save/backend/postprocessor/DockerSecretsDatabaseProcessor.kt
save-backend/src/main/resources/application-prod.properties

* Changed logic in build scripts
* Updated docker-compose.yaml.template

Set DB URL via secrets file

---

.github/workflows/build_and_test.yml
.github/workflows/deploy_images.yml
buildSrc/src/main/kotlin/org/cqfn/save/buildutils/DockerStackConfiguration.kt
buildSrc/src/main/kotlin/org/cqfn/save/buildutils/SpringBootConfiguration.kt
docker-compose.yaml.template

* Update gradle logic
* Update docker-compose.yaml.template
* Add workflow example

Deploy docker images to ghcr.io

---

docker-compose.yaml.template

Hotfix: Deploy images to ghcr.io

---

save-backend/src/main/kotlin/org/cqfn/save/backend/controllers/TestController.kt
save-backend/src/main/kotlin/org/cqfn/save/backend/controllers/TestSuitesController.kt
save-backend/src/main/kotlin/org/cqfn/save/backend/repository/TestExecutionRepository.kt
save-backend/src/main/kotlin/org/cqfn/save/backend/repository/TestSuiteRepository.kt
save-backend/src/main/kotlin/org/cqfn/save/backend/service/TestSuitesService.kt
save-preprocessor/src/main/kotlin/org/cqfn/save/preprocessor/controllers/DownloadProjectController.kt
save-preprocessor/src/test/kotlin/org/cqfn/save/preprocessor/DownloadProjectTest.kt
save-preprocessor/src/test/kotlin/org/cqfn/save/preprocessor/service/TestDiscoveringServiceTest.kt

* Remove old standard test suites from DB after uploading of the new one

Remove old standard test suites from DB

---

db/changelog/v-2/05-changeset-execution.xml
db/changelog/v-2/db.changelog-v-2.xml
save-backend/src/main/kotlin/org/cqfn/save/backend/controllers/CloneRepositoryController.kt
save-backend/src/main/kotlin/org/cqfn/save/backend/repository/FileSystemRepository.kt
save-backend/src/test/kotlin/org/cqfn/save/backend/controller/CloningRepositoryControllerTest.kt
save-backend/src/test/kotlin/org/cqfn/save/backend/controller/ExecutionControllerTest.kt
save-cloud-common/src/commonMain/kotlin/org/cqfn/save/execution/ExecutionDto.kt
save-cloud-common/src/jvmMain/kotlin/org/cqfn/save/entities/Execution.kt
save-orchestrator/src/test/kotlin/org/cqfn/save/orchestrator/controller/agents/AgentsControllerTest.kt
save-orchestrator/src/test/kotlin/org/cqfn/save/orchestrator/service/DockerServiceTest.kt
save-preprocessor/src/test/kotlin/org/cqfn/save/preprocessor/DownloadProjectTest.kt

* Add new column in Execution table: additional_files
* Store paths to additional files per Execution in the DB
* Update tests

Store paths to additional files per Execution in the DB 

---

save-orchestrator/src/main/kotlin/org/cqfn/save/orchestrator/service/DockerService.kt

Added chmod for clang-tidy

---

db/changelog/v-2/06-changeset-test.xml
db/changelog/v-2/db.changelog-v-2.xml
save-agent/src/linuxX64Main/kotlin/org/cqfn/save/agent/SaveAgent.kt
save-backend/src/main/kotlin/org/cqfn/save/backend/service/TestService.kt
save-backend/src/test/kotlin/org/cqfn/save/backend/controller/TestExecutionControllerTest.kt
save-backend/src/test/kotlin/org/cqfn/save/backend/controller/TestInitializeControllerTest.kt
save-cloud-common/src/commonMain/kotlin/org/cqfn/save/agent/TestExecutionDto.kt
save-cloud-common/src/commonMain/kotlin/org/cqfn/save/test/TestDto.kt
save-cloud-common/src/jvmMain/kotlin/org/cqfn/save/entities/Test.kt
save-cloud-common/src/jvmMain/kotlin/org/cqfn/save/entities/TestExecution.kt
save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/views/ExecutionView.kt
save-orchestrator/src/test/kotlin/org/cqfn/save/orchestrator/controller/heartbeat/HeartbeatControllerTest.kt
save-preprocessor/src/main/kotlin/org/cqfn/save/preprocessor/service/TestDiscoveringService.kt

* Display tags in Execution view
* Add new column in the `Test` table
* Update corresponding tests

Display tags in ExecutionView

---

save-orchestrator/src/main/kotlin/org/cqfn/save/orchestrator/service/DockerService.kt

Fixed chmod

---

save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/basic/FileUploader.kt
save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/views/CollectionView.kt
save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/views/CreationView.kt
save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/views/ProjectView.kt
save-frontend/src/main/kotlin/org/cqfn/save/frontend/externals/modal/Modal.kt
save-frontend/src/main/kotlin/org/cqfn/save/frontend/utils/RBuilderUtils.kt

- added new pop-ups for validation of URL and projects

Validation and pop-ups for a projectView

---

save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/views/ProjectView.kt

- if git url was provided, the creadentials were not passed to the backend. Now fixed

Hot fix for gitDto

---

save-cloud-common/src/commonMain/kotlin/org/cqfn/save/entities/ExecutionRequest.kt
save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/views/CreationView.kt

- as git credentials are optional, we should not fail while creating it

Hotfix for the "create test project" button

---

db/v-2/tables/agent-status.xml
db/v-2/tables/db.changelog-tables.xml
save-backend/src/main/kotlin/org/cqfn/save/backend/controllers/ExecutionController.kt
save-backend/src/main/kotlin/org/cqfn/save/backend/repository/AgentStatusRepository.kt
save-backend/src/main/kotlin/org/cqfn/save/backend/repository/TestExecutionRepository.kt
save-backend/src/main/kotlin/org/cqfn/save/backend/service/AgentService.kt
save-backend/src/main/kotlin/org/cqfn/save/backend/service/AgentStatusService.kt
save-backend/src/main/kotlin/org/cqfn/save/backend/service/ExecutionService.kt
save-backend/src/main/kotlin/org/cqfn/save/backend/service/TestExecutionService.kt
save-backend/src/test/kotlin/org/cqfn/save/backend/controller/DeleteEntitiesTest.kt
save-backend/src/test/kotlin/org/cqfn/save/backend/controller/ExecutionControllerTest.kt
save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/views/HistoryView.kt
save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/views/ProjectView.kt
save-frontend/src/main/kotlin/org/cqfn/save/frontend/externals/fontawesome/Icons.kt
save-preprocessor/src/test/kotlin/org/cqfn/save/preprocessor/service/TestDiscoveringServiceTest.kt

What's done:
* added functionality to delete executions
Closes #383

Deleting executions

---

save-cloud-common/src/commonMain/kotlin/org/cqfn/save/execution/ExecutionDto.kt
save-cloud-common/src/jvmMain/kotlin/org/cqfn/save/entities/Execution.kt
save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/views/ExecutionView.kt
save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/views/HistoryView.kt

What's done:
* added start time
Closes #391

Frontend: Display start and end time of execution

---

save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/views/ExecutionView.kt

What's done:
* added refresh after rerun
Closes #386

Frontend: After rerun request is submitted, refresh the page

---

save-backend/src/main/kotlin/org/cqfn/save/backend/controllers/ProjectController.kt
save-backend/src/main/kotlin/org/cqfn/save/backend/service/TestExecutionService.kt
save-backend/src/test/kotlin/org/cqfn/save/backend/CloneRepoTest.kt
save-backend/src/test/kotlin/org/cqfn/save/backend/controller/CloningRepositoryControllerTest.kt
save-cloud-common/src/commonMain/kotlin/org/cqfn/save/domain/ProjectSaveStatus.kt
save-cloud-common/src/commonMain/kotlin/org/cqfn/save/entities/ExecutionRequest.kt
save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/basic/CheckBoxGrid.kt
save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/basic/SdkSelection.kt
save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/basic/TestResourcesSelection.kt
save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/views/CreationView.kt
save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/views/ProjectView.kt
save-preprocessor/src/test/kotlin/org/cqfn/save/preprocessor/controllers/DownloadProjectTest.kt

- fixed an issue with validation of git URL with tests (with the default value)
- refactored project view

Refactoring for the project view

---

buildSrc/src/main/kotlin/org/cqfn/save/buildutils/SpringBootConfiguration.kt
db/db.changelog-master.xml
db/v-2/insert-test-data/db.changelog-insert.xml
db/v-2/insert-test-data/user-insert.xml
db/v-2/tables/user.xml
gradle/libs.versions.toml
save-backend/build.gradle.kts
save-backend/src/main/kotlin/org/cqfn/save/backend/configs/WebConfiguration.kt
save-backend/src/main/kotlin/org/cqfn/save/backend/configs/WebSecurityConfig.kt
save-backend/src/main/kotlin/org/cqfn/save/backend/repository/UserRepository.kt
save-backend/src/main/kotlin/org/cqfn/save/backend/service/UserDetailsService.kt
save-backend/src/test/kotlin/org/cqfn/save/backend/DownloadFilesTest.kt
save-backend/src/test/kotlin/org/cqfn/save/backend/controller/CloningRepositoryControllerTest.kt
save-backend/src/test/resources/application.properties
save-cloud-common/src/jvmMain/kotlin/org/cqfn/save/entities/User.kt
save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/modal/LogoutModal.kt
save-frontend/src/main/kotlin/org/cqfn/save/frontend/utils/RequestUtils.kt
save-frontend/src/main/resources/scss/save-frontend.scss

Minimal implementation of authorized access. User can log in using credentials, that have been added into the DB.
* Added `user` DB table and data for tests
* Configure spring security in backend
* Once the user logs in from the default spring boot's `formLogin`, credentials are used for all POST requests
* Unauthorized requests are redirected to `/login`
* Fixed inactive buttons in `logoutModal`, enabled `logout` button
* Security is activated in `secure` profile and disabled by default, until other necessary tasks are implemented
* Currently CSRF protection is not implemented
Other tasks are listed in #34
Closes #314, part of #34

Minimal support for authorization and authentication

---

save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/basic/Card.kt
save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/basic/FileUploader.kt
save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/basic/SdkSelection.kt
save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/basic/TestResourcesSelection.kt
save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/views/ProjectView.kt
save-frontend/src/main/kotlin/org/cqfn/save/frontend/externals/fontawesome/Icons.kt

- fixed the layout of the ProjectView

Polishing the design of the project view

---

README.md
buildSrc/src/main/kotlin/org/cqfn/save/buildutils/VersioningConfiguration.kt
db/v-1/insert-test-data/git-insert.xml
gradle/libs.versions.toml
save-agent/src/linuxX64Main/kotlin/org/cqfn/save/agent/Main.kt
save-agent/src/linuxX64Main/kotlin/org/cqfn/save/agent/SaveAgent.kt
save-backend/src/main/kotlin/org/cqfn/save/backend/service/TestExecutionService.kt
save-cloud-common/src/jvmMain/kotlin/org/cqfn/save/TestResultLocationJvm.kt
save-frontend/build.gradle.kts
save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/basic/FileUploader.kt
save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/views/ProjectView.kt
save-orchestrator/build.gradle.kts
save-orchestrator/src/main/kotlin/org/cqfn/save/orchestrator/service/AgentService.kt
save-orchestrator/src/main/kotlin/org/cqfn/save/orchestrator/service/DockerService.kt
save-preprocessor/src/main/kotlin/org/cqfn/save/preprocessor/controllers/DownloadProjectController.kt
save-preprocessor/src/main/resources/TestSuitesRepos
save-preprocessor/src/test/kotlin/org/cqfn/save/preprocessor/controllers/DownloadProjectTest.kt
save-preprocessor/src/test/kotlin/org/cqfn/save/preprocessor/service/TestDiscoveringServiceTest.kt

* Move additional files during standard mode into proper place
* Change links to actual repo over the project
* Update save-cli version and it's API

Fix for standard mode: move additional files into proper place

---

save-agent/src/linuxX64Main/kotlin/org/cqfn/save/agent/SaveAgent.kt
save-backend/src/main/kotlin/org/cqfn/save/backend/service/TestExecutionService.kt
save-cloud-common/src/commonMain/kotlin/org/cqfn/save/utils/StandardTestSuiteUtils.kt
save-cloud-common/src/jvmMain/kotlin/org/cqfn/save/TestResultLocationJvm.kt
save-orchestrator/src/main/kotlin/org/cqfn/save/orchestrator/service/AgentService.kt
save-orchestrator/src/main/kotlin/org/cqfn/save/orchestrator/service/DockerService.kt

* Fix: Compatibility of standard mode with actual version of SAVE-cli

Fix: Compatibility of standard mode with actual version of SAVE-cli

---

gradle/libs.versions.toml
save-backend/src/main/kotlin/org/cqfn/save/backend/controllers/ExecutionController.kt
save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/basic/FileUploader.kt
save-orchestrator/build.gradle.kts
save-orchestrator/src/main/kotlin/org/cqfn/save/orchestrator/service/DockerService.kt

* Support processing of uploaded zip archives - unzip zip archives into docker image among provided additional files

Support processing of uploaded zip archives

---

save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/basic/ExecutionStatistics.kt

What's done:
* changes logic for show info to execution in the PENDING status
Closes #418

If the test execution is in the PENDING status we should show "Loading"

---

gradle/libs.versions.toml
save-cloud-common/src/jvmMain/kotlin/org/cqfn/save/utils/FileUtils.kt
save-orchestrator/src/main/kotlin/org/cqfn/save/orchestrator/service/DockerService.kt
save-preprocessor/src/main/kotlin/org/cqfn/save/preprocessor/controllers/DownloadProjectController.kt

* Create logic of marking files from archive executable
* Fixes: Save attributes during copying/movement files

Make executable all files in archive, which marked executable

---

.github/workflows/deploy_images.yml
buildSrc/build.gradle.kts
buildSrc/src/main/kotlin/Versions.kt
buildSrc/src/main/kotlin/org/cqfn/save/buildutils/DockerStackConfiguration.kt
buildSrc/src/main/kotlin/org/cqfn/save/buildutils/SpringBootConfiguration.kt
save-cloud-common/build.gradle.kts

* Use gradle JVM toolchains
* Add gateway to `deploy_images.yaml`
* Add `RequiresOptIn` for `buildSrc`
* Enable `useOverride` by default and log a warning
Closes #449

Use Gradle JVM toolchains

---

api-gateway/src/main/kotlin/org/cqfn/save/gateway/controller/SecurityInfoController.kt
api-gateway/src/main/kotlin/org/cqfn/save/gateway/security/WebSecurityConfig.kt
api-gateway/src/main/resources/logback.xml
save-agent/src/linuxX64Main/kotlin/org/cqfn/save/agent/SaveAgent.kt
save-cloud-common/src/commonMain/kotlin/org/cqfn/save/info/OauthProviderInfo.kt
save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/tables/TableComponent.kt

* After login redirect to `projects` page instead of login page
* Add logback.xml for gateway
* Update status of save-agent when CLI has crashed
* Increase timeout
* Add information endpoint in gateway

Improve config for OAuth2 login

---

save-frontend/build.gradle.kts
save-frontend/src/main/kotlin/org/cqfn/save/frontend/App.kt
save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/TopBar.kt
save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/basic/HtmlElements.kt
save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/views/CollectionView.kt
save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/views/CreationView.kt
save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/views/HistoryView.kt
save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/views/ProjectView.kt
save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/views/WelcomeView.kt
save-frontend/src/main/kotlin/org/cqfn/save/frontend/externals/fontawesome/BrandIcons.kt
save-frontend/src/main/kotlin/org/cqfn/save/frontend/externals/fontawesome/Icons.kt
yarn.lock

- fixed GitHub logo
- made small hacks that enhanced the work with URL
- added public project checkbox
- updated alignment for navigation bars
- added tips with publicity to projects

Enhancements for the the frontend

---

db/v-2/tables/db.changelog-tables.xml
db/v-2/tables/test_execution.xml
save-agent/src/linuxX64Main/kotlin/org/cqfn/save/agent/SaveAgent.kt
save-backend/src/main/kotlin/org/cqfn/save/backend/service/TestExecutionService.kt
save-backend/src/test/kotlin/org/cqfn/save/backend/controller/TestExecutionControllerTest.kt
save-cloud-common/src/commonMain/kotlin/org/cqfn/save/agent/TestExecutionDto.kt
save-cloud-common/src/jvmMain/kotlin/org/cqfn/save/entities/TestExecution.kt
save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/views/ExecutionView.kt

What's done:
* added columns for match and mismatch warnings
Closes #454

Add columns for match and missing warnings

---

save-backend/src/main/kotlin/org/cqfn/save/backend/service/TestSuitesService.kt
save-preprocessor/src/main/kotlin/org/cqfn/save/preprocessor/controllers/DownloadProjectController.kt
save-preprocessor/src/main/kotlin/org/cqfn/save/preprocessor/service/TestDiscoveringService.kt
save-preprocessor/src/test/kotlin/org/cqfn/save/preprocessor/controllers/DownloadProjectTest.kt
save-preprocessor/src/test/kotlin/org/cqfn/save/preprocessor/service/TestDiscoveringServiceTest.kt

* Initialize tests in batches
* Fix: Save language for new test suites
Closes #474

Preprocessor: Initialize tests in batches

---

save-backend/src/main/kotlin/org/cqfn/save/backend/controllers/TestExecutionController.kt
save-backend/src/main/kotlin/org/cqfn/save/backend/repository/TestExecutionRepository.kt
save-backend/src/main/kotlin/org/cqfn/save/backend/service/TestExecutionService.kt
save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/basic/FiltersRow.kt
save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/views/ExecutionView.kt
save-frontend/src/main/kotlin/org/cqfn/save/frontend/externals/fontawesome/Icons.kt

What's done:
* added sort and filter test execution results by a test suite

Support the logic for aggregation of test results by test suite

---

detekt.yml
diktat-analysis.yml
save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/basic/ExecutionStatistics.kt
save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/basic/FiltersRow.kt
save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/tables/PagingControl.kt
save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/tables/TableComponent.kt
save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/views/AbstractView.kt
save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/views/ExecutionView.kt
save-frontend/src/main/kotlin/org/cqfn/save/frontend/externals/fontawesome/Icons.kt

Widgets on the ExecutionView

---

save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/basic/CheckBoxGrid.kt
save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/basic/TestResourcesSelection.kt
save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/views/WelcomeView.kt

* Removed powered by Huawei cloud
* Change description in git mode
* Fix popover and tooltip

Minor updates on frontend

---

gradle/libs.versions.toml
save-frontend/build.gradle.kts
save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/tables/TableComponent.kt
save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/views/CollectionView.kt
save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/views/ExecutionView.kt
save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/views/HistoryView.kt
save-frontend/webpack.config.d/plugins.js
yarn.lock

Columns require proper accessor functions for react-table to sort them.
* Add explicit accessor functions in all tables
* Add polyfill for `path-browserify`
Caveats:
* I can't find a way to disable sorting on specific columns, that don't (at least for now) have valid accessors. E.g., testFilePath - I don't think we need it to be sortable. Or tags - tags is a collection, and filtering/sorting by tags should be a separate logic.

Fix sorting in TableComponent

---

save-backend/src/main/kotlin/org/cqfn/save/backend/scheduling/StandardSuitesUpdateScheduler.kt
save-backend/src/main/resources/application-prod.properties

[skip ci] Disable qrtz scheduler

---

save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/basic/CheckBoxGrid.kt

What's done:
* fixed bug
Closes #485

Fix add Null in suitesTable method

---

buildSrc/src/main/kotlin/org/cqfn/save/buildutils/DockerStackConfiguration.kt
docker-compose.yaml.template

E.g., `./gradlew -Psave.profile=prod -Psave.component=save-backend buildAndDeployComponent` will build a docker image of save-backend and deploy it via `docker service update`

Gradle task to deploy individual services

---

.github/workflows/deploy_images.yml
README.md
api-gateway/src/main/kotlin/org/cqfn/save/gateway/security/WebSecurityConfig.kt
buildSrc/src/main/kotlin/org/cqfn/save/buildutils/SpringBootConfiguration.kt
buildSrc/src/main/kotlin/org/cqfn/save/buildutils/VersioningConfiguration.kt
db/v-1/insert-test-data/git-insert.xml
diktat-analysis.yml
docker-compose.yaml.template
save-agent/src/linuxX64Main/kotlin/org/cqfn/save/agent/SaveAgent.kt
save-backend/src/main/kotlin/org/cqfn/save/backend/configs/WebSecurityConfig.kt
save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/TopBar.kt
save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/basic/FileUploader.kt
save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/views/ProjectView.kt
save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/views/TestExecutionDetailsView.kt
save-orchestrator/build.gradle.kts
save-orchestrator/src/main/kotlin/org/cqfn/save/orchestrator/service/AgentService.kt
save-orchestrator/src/main/kotlin/org/cqfn/save/orchestrator/service/DockerService.kt
save-preprocessor/src/main/kotlin/org/cqfn/save/preprocessor/controllers/DownloadProjectController.kt
save-preprocessor/src/main/resources/TestSuitesRepos
save-preprocessor/src/test/kotlin/org/cqfn/save/preprocessor/controllers/CheckGitConnectivityTest.kt
save-preprocessor/src/test/kotlin/org/cqfn/save/preprocessor/controllers/DownloadProjectTest.kt
save-preprocessor/src/test/kotlin/org/cqfn/save/preprocessor/service/TestDiscoveringServiceTest.kt

* Rename everywhere
* Set explicit loki version

Rename diktat-static-analysis to analysis-dev

---

buildSrc/src/main/kotlin/org/cqfn/save/buildutils/DockerStackConfiguration.kt
renovate.json

Fix renovate config

---

save-backend/src/main/kotlin/org/cqfn/save/backend/controllers/ExecutionController.kt
save-backend/src/test/kotlin/org/cqfn/save/backend/controller/DeleteEntitiesTest.kt
save-backend/src/test/kotlin/org/cqfn/save/backend/controller/ExecutionControllerTest.kt
save-cloud-common/src/jvmMain/kotlin/org/cqfn/save/utils/LocalDateTimeSerializer.kt
save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/views/HistoryView.kt
save-preprocessor/build.gradle.kts
save-preprocessor/src/main/kotlin/org/cqfn/save/preprocessor/controllers/DownloadProjectController.kt
save-preprocessor/src/main/kotlin/org/cqfn/save/preprocessor/utils/LocalDateTimeConfig.kt
save-preprocessor/src/test/kotlin/org/cqfn/save/preprocessor/controllers/DownloadProjectTest.kt

What's done:
* fixed error on HistoryView
* fixed deserialize for LocalDateTime
Closes #576

Frontend: Error on HistoryView

---

db/v-1/insert-test-data/project-insert.xml
db/v-2/insert-test-data/project-insert.xml
db/v-2/tables/project.xml
save-backend/src/main/kotlin/org/cqfn/save/backend/controllers/ExecutionController.kt
save-backend/src/main/kotlin/org/cqfn/save/backend/repository/ExecutionRepository.kt
save-backend/src/main/kotlin/org/cqfn/save/backend/service/ExecutionService.kt
save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/views/CollectionView.kt
save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/views/CreationView.kt
save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/views/OrganizationView.kt
save-frontend/src/main/kotlin/org/cqfn/save/frontend/utils/RequestUtils.kt

What's done:
* rename owner to organization
* added load organization in organizationView
* deleted owner in project table

Minor fix for organization

---

save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/basic/ProjectInfo.kt
save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/views/ProjectView.kt
save-frontend/src/main/kotlin/org/cqfn/save/frontend/externals/fontawesome/FontAusomeIconBuilders.kt

* Create `projectInfo` component
* Store project in state of ProjectView
* Store draft project in state of `projectInfo`
* Only send request for update if project has actually changed
Closes #588

Create `projectInfo` component, fix project info data updates

---

save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/basic/SelectForm.kt

What's done:
* added warning on field
Closes #623

Warning if list organization for user is empty

---

gradle/libs.versions.toml
save-backend/src/main/kotlin/org/cqfn/save/backend/configs/WebSecurityConfig.kt
save-backend/src/main/kotlin/org/cqfn/save/backend/controllers/OrganizationController.kt
save-backend/src/main/kotlin/org/cqfn/save/backend/controllers/ProjectController.kt
save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/views/OrganizationView.kt
save-frontend/src/main/kotlin/org/cqfn/save/frontend/http/Requests.kt

* Make `/api/organization/**` public
* Refine permission checks in OrganizationController.kt
* Change some API methods for organizations, change return type of annotated methods to Publisher
* Make list of projects by organization public
Closes #639

Make organizations info available for anonymous users

---

save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/views/CreationView.kt

What's done:
* added choice between public and private project
Closes #638

Add choice between public and private project in CreateProject view

---

save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/basic/ProjectStatisticMenu.kt

* Pass executionId into the tabe (follow up after #670)
* Don't render the table if there is no data (to be improved in #673)

Frontend: Hotfix for table on project statistics tab

---

gradle.properties
gradle/libs.versions.toml
save-agent/build.gradle.kts
save-agent/src/linuxX64Main/kotlin/org/cqfn/save/agent/Main.kt
save-agent/src/linuxX64Main/kotlin/org/cqfn/save/agent/SaveAgent.kt
save-agent/src/linuxX64Test/kotlin/org/cqfn/save/agent/SaveAgentTest.kt
save-api/src/main/kotlin/org/cqfn/save/api/RequestUtils.kt

* Update ktor API to v2 in save-agent and save-api
* Switch save-agent to the new MM, because apparently ktor 2 doesn't work with the old MM (https://stackoverflow.com/questions/70975057/invalidmutabilityexceptioninvalidmutabilityexception-on-common-test-with-ktor)
After this update, #568 can probably be finished. This PR can be considered a cleaner version of #572, but without multithreaded contexts or additional logging (it can be added later, if needed).

Update to ktor 2.0.0, enable new MM in save-agent

---

.github/workflows/build_and_test.yml
.github/workflows/deploy_images.yml
.github/workflows/detekt.yml
.github/workflows/diktat.yml
.github/workflows/save-api-examples.yml
.gitmodules
settings.gradle.kts

* Use sarif4k from analysis-dev GH packages
* Remove git submodule
Related: https://github.com/analysis-dev/save-cli/pull/380

Use sarif4k from analysis-dev GH packages

---

CONTRIBUTING.md
api-gateway/src/main/resources/application.yml
build.gradle.kts
buildSrc/src/main/kotlin/org/cqfn/save/buildutils/DockerStackConfiguration.kt
buildSrc/src/main/kotlin/org/cqfn/save/buildutils/SpringBootConfiguration.kt
docker-compose.yaml
save-agent/src/linuxX64Main/resources/agent.properties
save-backend/src/main/resources/application-mac.properties
save-backend/src/main/resources/application.properties
save-backend/src/test/resources/application.properties
save-deploy/README.md
save-frontend/webpack.config.d/dev-server.js
save-orchestrator/src/main/resources/application-mac.properties
save-orchestrator/src/main/resources/application.properties
save-orchestrator/src/test/resources/application-mac.properties
save-orchestrator/src/test/resources/application.properties
save-preprocessor/src/main/resources/application-mac.properties
save-preprocessor/src/main/resources/application.properties
save-preprocessor/src/test/resources/application-mac.properties
yarn.lock

This PR closes #698 
Before merging, proper testing is needed!

Make save-cloud easier to contribute for mac users

---

db/v-2/insert-test-data/sqlRequests/lnk-user-organization.csv
db/v-2/tables/lnk-user-organization.xml
db/v-2/tables/organization.xml
save-backend/src/main/kotlin/org/cqfn/save/backend/controllers/OrganizationController.kt
save-backend/src/main/kotlin/org/cqfn/save/backend/controllers/UsersDetailsController.kt
save-backend/src/main/kotlin/org/cqfn/save/backend/repository/LnkUserOrganizationRepository.kt
save-backend/src/main/kotlin/org/cqfn/save/backend/service/LnkUserOrganizationService.kt
save-backend/src/main/kotlin/org/cqfn/save/backend/service/OrganizationService.kt
save-cloud-common/src/commonMain/kotlin/org/cqfn/save/domain/Role.kt
save-cloud-common/src/commonMain/kotlin/org/cqfn/save/entities/Organization.kt
save-cloud-common/src/jvmMain/kotlin/org/cqfn/save/entities/LnkUserOrganization.kt
save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/TopBar.kt
save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/views/OrganizationView.kt

What's done:
added description in organization

Add description in organization

---

save-backend/src/main/kotlin/org/cqfn/save/backend/controllers/DownloadFilesController.kt
save-cloud-common/src/commonMain/kotlin/org/cqfn/save/domain/Role.kt
save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/views/OrganizationView.kt
save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/views/WelcomeView.kt

What's done:
* fixed button for description in organization
* fixed upload avatar for organization
* added list avatar users in organization view

Minor fix for organization view

---

api-gateway/src/main/kotlin/org/cqfn/save/gateway/security/WebSecurityConfig.kt
api-gateway/src/main/resources/application.yml
save-backend/src/main/kotlin/org/cqfn/save/backend/controllers/OrganizationController.kt
save-backend/src/main/kotlin/org/cqfn/save/backend/controllers/ProjectController.kt
save-backend/src/main/kotlin/org/cqfn/save/backend/repository/LnkUserOrganizationRepository.kt
save-backend/src/main/kotlin/org/cqfn/save/backend/repository/LnkUserProjectRepository.kt
save-backend/src/main/kotlin/org/cqfn/save/backend/service/LnkUserOrganizationService.kt
save-backend/src/main/kotlin/org/cqfn/save/backend/service/LnkUserProjectService.kt
save-backend/src/main/kotlin/org/cqfn/save/backend/service/ProjectService.kt
save-backend/src/test/kotlin/org/cqfn/save/backend/controller/ProjectControllerTest.kt
save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/HasErrorModal.kt
save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/views/CreateOrganizationView.kt
save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/views/CreationView.kt

Redirects of frontend

---

save-backend/src/main/kotlin/org/cqfn/save/backend/controllers/ExecutionController.kt

* Configure proper serialization of LocalDateTime in ExecutionController

Configure proper serialization of LocalDateTime in ExecutionController

---

save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/tables/TableComponent.kt

* Added message if data in table is empty
Closes #484

FE table filters: If no resuts are found, display it explicitly

---

save-api/src/main/kotlin/org/cqfn/save/api/SaveCloudClient.kt
save-api/src/main/kotlin/org/cqfn/save/api/utils/RequestUtils.kt
save-backend/Backend-API.md
save-backend/src/main/kotlin/org/cqfn/save/backend/controllers/CloneRepositoryController.kt
save-backend/src/main/kotlin/org/cqfn/save/backend/controllers/DownloadFilesController.kt
save-backend/src/main/kotlin/org/cqfn/save/backend/repository/TimestampBasedFileSystemRepository.kt
save-backend/src/test/kotlin/org/cqfn/save/backend/DownloadFilesTest.kt
save-cloud-common/src/commonMain/kotlin/org/cqfn/save/domain/FileInfo.kt
save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/views/ProjectView.kt

* Change api of additional files uploading - process low level information at the backend side

Change api of additional files uploading

---

buildSrc/src/main/kotlin/org/cqfn/save/buildutils/DockerStackConfiguration.kt

Register `buildAndDeployComponent` task only if `save.component` is set

---

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/App.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/ErrorBoundary.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/FallbackView.kt

* Add ErrorBoundary (https://reactjs.org/docs/error-boundaries.html)
* Add props for FallbackView
Closes #613

Use React error boundary

---

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/ManageUserRoleCard.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/HistoryView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/OrganizationView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/ProjectView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/utils/RBuilderUtils.kt

Bugfix for wrong redirects

---

save-agent/src/linuxX64Main/kotlin/com/saveourtool/save/agent/SaveAgent.kt

- supported renaming from save-cli

save-cloud: Precision and Recall

---

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/TopBar.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/CheckBoxGrid.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/FileUploader.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/ProjectInfo.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/ScrollToTopButton.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/tables/TableComponent.kt

* pass dependencies as vararg everywhere
* Remove `pageCount` from `useEffect` in `TableComponent`
Closes #827

`useEffect`: pass dependencies as vararg everywhere

---

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/tables/TableComponent.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/ExecutionView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/http/Requests.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/utils/ComponentWithScope.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/utils/RequestUtils.kt

Loading Modal Window Follow-ups

---

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/ProjectView.kt

Loading handler fix for fileUploader

---

save-api/src/main/kotlin/com/saveourtool/save/api/SaveCloudClient.kt
save-api/src/main/kotlin/com/saveourtool/save/api/utils/RequestUtils.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/CloneRepositoryController.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/ExecutionController.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/TestSuitesController.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/internal/TestController.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/service/ExecutionService.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/service/TestExecutionService.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/service/TestService.kt
save-backend/src/test/kotlin/com/saveourtool/save/backend/controller/ExecutionControllerTest.kt
save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/entities/ExecutionRequest.kt
save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/execution/ExecutionInitializationDto.kt
save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/test/TestDto.kt
save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/entities/BaseEntity.kt
save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/entities/Execution.kt
save-cloud-common/src/jvmTest/kotlin/com/saveourtool/save/entities/ExecutionTest.kt
save-orchestrator/src/main/kotlin/com/saveourtool/save/orchestrator/controller/AgentsController.kt
save-orchestrator/src/main/kotlin/com/saveourtool/save/orchestrator/service/DockerService.kt
save-orchestrator/src/test/kotlin/com/saveourtool/save/orchestrator/controller/agents/AgentsControllerTest.kt
save-orchestrator/src/test/kotlin/com/saveourtool/save/orchestrator/service/DockerServiceTest.kt
save-preprocessor/src/main/kotlin/com/saveourtool/save/preprocessor/controllers/DownloadProjectController.kt
save-preprocessor/src/main/kotlin/com/saveourtool/save/preprocessor/service/TestDiscoveringService.kt
save-preprocessor/src/test/kotlin/com/saveourtool/save/preprocessor/controllers/DownloadProjectTest.kt

- added logger extension
- refactored initializations and executing tests

save-cloud: refactoring initialization of tests

---

save-orchestrator/src/main/kotlin/com/saveourtool/save/orchestrator/docker/KubernetesManager.kt
save-orchestrator/src/main/kotlin/com/saveourtool/save/orchestrator/service/AgentService.kt
save-orchestrator/src/main/kotlin/com/saveourtool/save/orchestrator/service/HeartBeatInspector.kt

* Change deserialization type
* Wait for 10 seconds for pods to be created
* Remove unused method
* Improve logging
Related to #862

Orchestrator: Use correct class for deserialization

---

save-api/src/main/kotlin/com/saveourtool/save/api/SaveCloudClient.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/CloneRepositoryController.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/ExecutionController.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/TestSuitesController.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/internal/TestController.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/service/ExecutionService.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/service/TestExecutionService.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/service/TestService.kt
save-backend/src/test/kotlin/com/saveourtool/save/backend/controller/ExecutionControllerTest.kt
save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/entities/ExecutionRequest.kt
save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/execution/ExecutionInitializationDto.kt
save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/entities/BaseEntity.kt
save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/entities/Execution.kt
save-cloud-common/src/jvmTest/kotlin/com/saveourtool/save/entities/ExecutionTest.kt
save-orchestrator/src/main/kotlin/com/saveourtool/save/orchestrator/controller/AgentsController.kt
save-orchestrator/src/main/kotlin/com/saveourtool/save/orchestrator/service/DockerService.kt
save-orchestrator/src/test/kotlin/com/saveourtool/save/orchestrator/controller/agents/AgentsControllerTest.kt
save-orchestrator/src/test/kotlin/com/saveourtool/save/orchestrator/service/DockerServiceTest.kt
save-preprocessor/src/main/kotlin/com/saveourtool/save/preprocessor/controllers/DownloadProjectController.kt
save-preprocessor/src/main/kotlin/com/saveourtool/save/preprocessor/service/TestDiscoveringService.kt
save-preprocessor/src/test/kotlin/com/saveourtool/save/preprocessor/controllers/DownloadProjectTest.kt

* added logger extension
* refactored initializations and executing tests (DownloadProjectController.kt)
It closes #821

save-cloud: refactoring initialization of tests (#816)

---

buildSrc/src/main/kotlin/com/saveourtool/save/buildutils/VersioningConfiguration.kt
renovate.json
save-deploy/README.md
save-orchestrator/build.gradle.kts
save-orchestrator/src/main/kotlin/com/saveourtool/save/orchestrator/docker/DockerAgentRunner.kt

* additional properties and build tasks were introduced to copy save-agent and save-cli from local wsl folders
* fix agent stop check
* readme updated

local run enhancements

---

save-preprocessor/src/main/kotlin/com/saveourtool/save/preprocessor/controllers/DownloadProjectController.kt

* fixed collecting of initialized tests for marking old test suites

Standard test suites loading

---

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/ExecutionView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/OrganizationView.kt

- in case debug info is not available on the execution view - we won't raise 404 and show test name clickable
- small changes in text style

Small bugfixing of debug info

---

.github/workflows/detekt.yml
.github/workflows/diktat.yml
buildSrc/build.gradle.kts
buildSrc/src/main/kotlin/com/saveourtool/save/buildutils/DetektConfiguration.kt
buildSrc/src/main/kotlin/com/saveourtool/save/buildutils/DiktatConfiguration.kt

* Use `ReportMergeTask` to merge SARIF reports

Merge SARIF reports in Github Actions

---

save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/LnkContestProjectController.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/repository/LnkContestProjectRepository.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/service/LnkContestProjectService.kt
save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/entities/ContestResult.kt
save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/entities/LnkContestProject.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/ScoreCard.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/UserBoard.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/contests/ContestParticipantsMenu.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/organizations/OrganizationSettingsMenu.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/projects/ProjectInfoMenu.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/projects/ProjectSettingsMenu.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/projects/ProjectStatisticMenu.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/OrganizationView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/ProjectView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/utils/ProjectMenuBar.kt

This PR is a part of #900 
* Add project global score label
* Improve visual part
* Move `RUN` block from `ProjectView` to separate `FC`

Info tab in ProjectView

---

buildSrc/src/main/kotlin/com/saveourtool/save/buildutils/SpringBootConfiguration.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/SaveApplication.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/CloneRepositoryController.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/DownloadFilesController.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/TestExecutionController.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/repository/TestDataFilesystemRepository.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/repository/TimestampBasedFileSystemRepository.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/storage/AvatarStorage.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/storage/DebugInfoStorage.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/storage/ExecutionInfoStorage.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/storage/FileStorage.kt
save-backend/src/test/kotlin/com/saveourtool/save/backend/DownloadFilesTest.kt
save-backend/src/test/kotlin/com/saveourtool/save/backend/controller/CloningRepositoryControllerTest.kt
save-cloud-common/build.gradle.kts
save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/domain/FileKey.kt
save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/storage/AbstractFileBasedStorage.kt
save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/storage/Storage.kt
save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/utils/FileUtils.kt

* added interface for Storage
* added default implementation based on file system
* refactored TimestampBasedFileSystemRepository to use new storages
It's part of #250 and #857

Introduce interface Storages

---

save-backend/src/main/kotlin/com/saveourtool/save/backend/storage/DebugInfoStorage.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/storage/ExecutionInfoStorage.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/storage/FileStorage.kt
save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/storage/AbstractFileBasedStorage.kt

* added checking count of parts in path

Storage list fix

---

save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/ProjectController.kt

Bugfix for 403 on Project Info Tab

---

save-orchestrator/src/main/kotlin/com/saveourtool/save/orchestrator/controller/AgentsController.kt

- replaced from Flux<String> to Mono<List<String>>

Fix for testRootPath calculating

---

renovate.json
save-cloud-charts/save-cloud/values.yaml

* Enable `lockFileMaintenance` for `helmv3` in `renovate.json` (will update `Chart.lock` from time to time if a new version matching range from `Chart.yaml` is available)
* Fix `loki` tag in `values.yaml`

Enable `lockFileMaintenance` for `helmv3` in `renovate.json`

---

save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/entities/benchmarks/BenchmarkEntity.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/HasErrorModal.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/AwesomeBenchmarksView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/externals/modal/Modal.kt

Awesome benchmarks filtering

---

save-orchestrator/src/main/kotlin/com/saveourtool/save/orchestrator/config/ConfigProperties.kt
save-orchestrator/src/main/kotlin/com/saveourtool/save/orchestrator/docker/DockerAgentRunner.kt
save-orchestrator/src/main/kotlin/com/saveourtool/save/orchestrator/kubernetes/KubernetesManager.kt
save-orchestrator/src/main/kotlin/com/saveourtool/save/orchestrator/runner/AgentRunner.kt

* Orchestrator: delete resources, containers and images after some time

Orchestrator: delete resources, containers and images after some time

---

db/db.changelog-master.xml

- Add context on include file level

Apply changelog for test data for dev profile only

---

save-backend/backend-api-docs.json
save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/TestSuitesSourceController.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/service/TestService.kt
save-backend/src/test/kotlin/com/saveourtool/save/backend/controller/TestInitializeControllerTest.kt
save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/test/TestDto.kt
save-orchestrator/src/main/kotlin/com/saveourtool/save/orchestrator/controller/AgentsController.kt
save-orchestrator/src/main/kotlin/com/saveourtool/save/orchestrator/runner/AgentRunner.kt
save-orchestrator/src/main/kotlin/com/saveourtool/save/orchestrator/service/AgentService.kt
save-orchestrator/src/test/kotlin/com/saveourtool/save/orchestrator/controller/heartbeat/HeartbeatControllerTest.kt
save-preprocessor/src/test/kotlin/com/saveourtool/save/preprocessor/controllers/DownloadProjectTest.kt

- add endpoint to get test suites source id
- changed TestBatch to contains test suites source id
It's a hotfix for #994

Fix location to tests in batches

---

db/test-data/test-suites-source-insert.xml
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/organizations/OrganizationTestsMenu.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/ContestListView.kt

* Removed a button in OrganizationTestsMenu's first table
* Made OrganizationTestsMenu's second table able to hide
* Removed a button in ContestListView's table
https://user-images.githubusercontent.com/35039155/183081582-250d05eb-79e3-4482-a4df-0682ab0b98d6.mov

Minor improvements of tables on frontend

---

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/OrganizationView.kt

* removed download avatar in Organization view

Removed download avatar in Organization view

---

save-preprocessor/src/main/kotlin/com/saveourtool/save/preprocessor/controllers/DownloadProjectController.kt
save-preprocessor/src/test/kotlin/com/saveourtool/save/preprocessor/controllers/DownloadProjectTest.kt

- distinctBy TestSuitesSource.id

Hotfix for distinct of TestSuitesSource

---

save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/OrganizationController.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/utils/ReactorUtils.kt

- Mono.fromCallable accepts null

Fix for additional files on Orchestrator: follow up

---

save-backend/backend-api-docs.json
save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/LnkUserOrganizationController.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/LnkUserProjectController.kt

Bugfix for 500 when adding user to group

---

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/ExecutionView.kt

* Fix pagination on ExecutionView

Fix pagination on ExecutionView

---

save-agent/src/linuxX64Main/kotlin/com/saveourtool/save/agent/AgentConfiguration.kt
save-agent/src/linuxX64Main/kotlin/com/saveourtool/save/agent/Main.kt
save-agent/src/linuxX64Main/kotlin/com/saveourtool/save/agent/SaveAgent.kt
save-agent/src/linuxX64Main/kotlin/com/saveourtool/save/agent/utils/LinuxUtils.kt
save-backend/backend-api-docs.json
save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/TestSuitesController.kt
save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/agent/AgentEnvName.kt
save-orchestrator/src/main/kotlin/com/saveourtool/save/orchestrator/Utils.kt
save-orchestrator/src/main/kotlin/com/saveourtool/save/orchestrator/docker/DockerAgentRunner.kt
save-orchestrator/src/main/kotlin/com/saveourtool/save/orchestrator/kubernetes/KubernetesManager.kt
save-orchestrator/src/main/kotlin/com/saveourtool/save/orchestrator/service/DockerService.kt
save-orchestrator/src/test/kotlin/com/saveourtool/save/orchestrator/controller/agents/AgentsControllerTest.kt
save-orchestrator/src/test/kotlin/com/saveourtool/save/orchestrator/docker/DockerContainerManagerTest.kt
save-orchestrator/src/test/kotlin/com/saveourtool/save/orchestrator/service/DockerServiceTest.kt

* modified execFlags in batch size
It closes #1052

Supported overrideExecCmd and batchSize in save-cloud

---

save-backend/backend-api-docs.json
save-backend/src/main/kotlin/com/saveourtool/save/backend/configs/WebSecurityConfig.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/service/OrganizationService.kt
save-backend/src/test/kotlin/com/saveourtool/save/backend/controller/OrganizationControllerTest.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/CreateOrganizationView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/CreationView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/OrganizationView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/http/Requests.kt
save-frontend/src/test/kotlin/com/saveourtool/save/frontend/components/basic/SelectFormTest.kt
save-frontend/src/test/kotlin/com/saveourtool/save/frontend/components/views/OrganizationViewTest.kt

- renamed duplicated organization controller

Finally removing "api/organization" controller

---

save-backend/src/main/kotlin/com/saveourtool/save/backend/configs/WebConfiguration.kt

Since now we have a lot of new static `.png` files, they should have `Cache-Control` too

Make more resources on the backend cacheable

---

.gitattributes
gradle/libs.versions.toml
save-agent/build.gradle.kts
save-agent/src/linuxX64Main/kotlin/com/saveourtool/save/agent/Requests.kt
save-agent/src/linuxX64Main/kotlin/com/saveourtool/save/agent/SaveAgent.kt

* support setup.sh from additional resources
* support save-overrides.toml
It closes #1120

Support additional setup sh

---

save-backend/backend-api-docs.json
save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/ContestController.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/service/ContestService.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/ContestView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/contests/FeaturedContest.kt

* Added endpoint to check if given contest is marked as featured or not
* Added "placeholder" for featuredContest: if there is no featured contest, "Stay turned..." text is displayed
* Added checkbox to mark contest as featured (for super admins only)

Mark contests as featured on frontend

---

save-agent/src/linuxX64Main/kotlin/com/saveourtool/save/agent/SaveAgent.kt
save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/utils/ReactorUtils.kt
save-preprocessor/src/main/kotlin/com/saveourtool/save/preprocessor/service/TestDiscoveringService.kt

* increased timeout for setup.sh to 1 minute

Increased timeout for setup.sh

---

buildSrc/src/main/kotlin/com/saveourtool/save/buildutils/SpringBootConfiguration.kt

* Cleanup profiles selection
* Remove redundant cast

[Gradle] Cleanup SpringBootConfiguration.kt

---

buildSrc/src/main/kotlin/com/saveourtool/save/buildutils/DockerStackConfiguration.kt

There's no separate `docker-compose` executable on Linux anymore -- just
the Docker plug-in.

Use `docker compose` instead of `docker-compose`

---

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/contests/ContestListView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/contests/FeaturedContest.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/contests/NewContestsCard.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/contests/ProposeYourContest.kt

- propose a contest with an e-mail card

Propose a contest card

---

save-preprocessor/src/main/kotlin/com/saveourtool/save/preprocessor/service/TestDiscoveringService.kt

- hotfix with testSuiteId
It fixes #1099

Hotfix for ID of test suites on tests

---

buildSrc/src/main/kotlin/com/saveourtool/save/buildutils/DockerStackConfiguration.kt

- reverted c83bc7201882b6d25512b4a5cafb6097779501ec

Use `docker-compose` instead of `docker compose`

---

save-agent/src/linuxX64Main/kotlin/com/saveourtool/save/agent/SaveAgent.kt

Fix `save-overrides.toml`

---

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/ProjectView.kt

- checking that execCmd and batchSizeForAnalyzer is not empty

Apply overrides only if they are set

---

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/HasErrorModal.kt

* fix handle 404 
Closes #1067

Response handler doesn't handle errors properly

---

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/ContestView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/http/Requests.kt

* fixed bug on ContestView 
Closes #1165

Bug on ContestView with invalid URL

---

save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/TestSuitesSourceController.kt
save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/validation/ValidationUtils.kt
save-cloud-common/src/jvmTest/kotlin/com/saveourtool/save/validation/ValidationUtilsTest.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/inputform/InputForms.kt

* fixed test suites source name
* move only if name is changed

Moving snapshots of test suites sources

---

api-gateway/build.gradle.kts
buildSrc/src/main/kotlin/com/saveourtool/save/buildutils/kotlin-jvm-configuration.gradle.kts
buildSrc/src/main/kotlin/com/saveourtool/save/buildutils/spring-boot-configuration.gradle.kts
gradle/libs.versions.toml
save-api-cli/build.gradle.kts
save-api/build.gradle.kts
save-backend/build.gradle.kts
save-cloud-common/build.gradle.kts
save-orchestrator/build.gradle.kts
save-preprocessor/build.gradle.kts
test-utils/build.gradle.kts

* Precompiled script plugin for kotlin-jvm plugin application and configuration
* Move some dependencies to libs.versions.toml

Precompiled script plugin for `kotlin-jvm`

---

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/TestResourcesSelection.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/contests/ContestCreationComponent.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/testsuiteselector/TestSuiteSelector.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/testsuiteselector/TestSuiteSelectorBrowserMode.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/testsuiteselector/TestSuiteSelectorManagerMode.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/testsuiteselector/TestSuiteSelectorSearchMode.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/ProjectView.kt

* Changed test suit id on test suite name
* Fixed role priority for project view

Support test suite name for project view

---

docker-compose.yaml
save-agent/src/linuxX64Main/kotlin/com/saveourtool/save/agent/AgentConfiguration.kt
save-agent/src/linuxX64Main/kotlin/com/saveourtool/save/agent/SaveAgent.kt
save-agent/src/linuxX64Test/kotlin/com/saveourtool/save/agent/SaveAgentTest.kt
save-cloud-charts/save-cloud/templates/orchestrator-deployment.yaml
save-orchestrator/src/main/kotlin/com/saveourtool/save/orchestrator/config/ConfigProperties.kt
save-orchestrator/src/main/kotlin/com/saveourtool/save/orchestrator/controller/AgentsController.kt
save-orchestrator/src/main/resources/application-mac.properties
save-orchestrator/src/main/resources/application-win.properties
save-orchestrator/src/main/resources/application.properties
save-orchestrator/src/test/kotlin/com/saveourtool/save/orchestrator/controller/agents/AgentsControllerTest.kt
save-orchestrator/src/test/resources/application-mac.properties
save-orchestrator/src/test/resources/application.properties
save-sandbox/src/main/kotlin/com/saveourtool/save/orchestrator/config/ConfigProperties.kt
save-sandbox/src/main/kotlin/com/saveourtool/save/orchestrator/controller/AgentsController.kt
save-sandbox/src/main/kotlin/com/saveourtool/save/sandbox/storage/SandboxStorage.kt
save-sandbox/src/main/resources/application-mac.properties
save-sandbox/src/main/resources/application-win.properties
save-sandbox/src/main/resources/application.properties
save-sandbox/src/test/kotlin/com/saveourtool/save/orchestrator/controller/agents/AgentsControllerTest.kt
save-sandbox/src/test/resources/application-mac.properties
save-sandbox/src/test/resources/application.properties

Remove endpoint `/executionLogs` from orchestrator 

---

save-backend/src/main/kotlin/com/saveourtool/save/backend/repository/AgentStatusRepository.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/repository/AwesomeBenchmarksRepository.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/repository/ContestRepository.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/repository/TestExecutionRepository.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/TestResourcesSelection.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/testsuiteselector/TestSuiteSelector.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/ProjectView.kt

* Renamed variables testSuitesIds to testSuitesDtos
* Removed JpaSpecificationExecutor implementation in repositories

Minor fix in project

---

save-sandbox/src/main/kotlin/com/saveourtool/save/sandbox/entity/SandboxAgentStatus.kt
save-sandbox/src/main/kotlin/com/saveourtool/save/sandbox/repository/SandboxAgentStatusRepository.kt

Fixed database issues in sandbox

---

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/codeeditor/CodeEditorComponent.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/SandboxView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/utils/ReactUtils.kt
save-frontend/webpack.config.d/dev-server.js
save-sandbox/src/main/kotlin/com/saveourtool/save/sandbox/controller/SandboxController.kt

* supported loading and uploading test to/from sandbox storage
* added routing for frontend to sandbox in local mode
It closes #1284
TODO:
* change file name for code example
* we provide a list of test files to save-cli, probably we should provide an empty cli arg to test a discovering too

Store test and test resources in sandbox storage

---

CONTRIBUTING.md
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/codeeditor/CodeEditorComponent.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/modal/ModalBuilder.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/SandboxView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/TestExecutionDetailsView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/externals/fontawesome/Icons.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/externals/reactace/AceModes.kt

https://user-images.githubusercontent.com/35039155/194892646-7e415093-4e95-4f7b-8fa7-983161081bda.mov

DebugInfo on SandboxView

---

build.gradle.kts
db/v-2/tables/agent-status.xml
db/v-2/tables/agent.xml
db/v-2/tables/contest.xml
db/v-2/tables/execution.xml
db/v-2/tables/git.xml
db/v-2/tables/lnk-contest-execution.xml
db/v-2/tables/lnk-contest-project.xml
db/v-2/tables/lnk-organization-test-suite.xml
db/v-2/tables/lnk-user-organization.xml
db/v-2/tables/lnk-user-project.xml
db/v-2/tables/organization.xml
db/v-2/tables/original-login.xml
db/v-2/tables/project.xml
db/v-2/tables/test-suites-source.xml
db/v-2/tables/test.xml
db/v-2/tables/test_execution.xml
db/v-2/tables/test_suite.xml

Added cascade on delete for all foreign keys

Added cascade on delete for all foreign keys

---

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/codeeditor/EditorToolbar.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/codeeditor/FileType.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/codeeditor/SandboxCodeEditorComponent.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/SandboxView.kt
save-sandbox/src/main/kotlin/com/saveourtool/save/sandbox/controller/SandboxController.kt
save-sandbox/src/main/kotlin/com/saveourtool/save/sandbox/repository/SandboxExecutionRepository.kt

Added validation that there is only a single running execution per user and cleanup of DebugInfo
It closes #1297

Single execution per user

---

save-backend/backend-api-docs.json
save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/OrganizationController.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/repository/OrganizationRepository.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/service/OrganizationService.kt
save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/filters/OrganizationFilters.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/ManageUserRoleCard.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/organizations/testsuitespermissions/ManageTestSuitePermissionsCard.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/inputform/InputWithDebounce.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/contests/ContestGlobalRatingView.kt

Input form with debounce

---

save-backend/backend-api-docs.json
save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/ExecutionController.kt
save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/execution/ExecutionDto.kt
save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/entities/Execution.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/ContestExecutionView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/HistoryView.kt
save-frontend/src/test/kotlin/com/saveourtool/save/frontend/components/basic/ExecutionStatisticsValuesTest.kt

* On execution view don't show executions, participating in contest

Frontend: On execution view don't show executions, participating in contest

---

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/TestResourcesSelection.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/testsuitessources/TestSuiteSourceUpsertComponent.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/testsuitessources/fetch/TestSuitesSourceFetcher.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/ProjectView.kt

* Added `custom-select` to selector class of `SelectForm`
* Improved disabled condition for Run button on `ProjectView`

Minor cosmetic selectors fixes

---

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/modal/ModalDialog.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/modal/ModalDialogStrings.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/OrganizationView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/utils/DeleteButton.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/utils/RequestUtils.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/utils/RunWithConfirmation.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/utils/Utils.kt

This partially implements #1137.

Enable super-admins to delete projects within an organization

---

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/contests/FeaturedContests.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/contests/MyProjectsRating.kt

Hotfix for alignments on contest view

---

save-backend/backend-api-docs.json
save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/OrganizationController.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/service/OrganizationService.kt
save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/validation/FrontendRoutes.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/App.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/ManageUserRoleCard.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/organizations/ManageGitCredentialsCard.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/organizations/OrganizationSettingsMenu.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/ContestView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/OrganizationAdminView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/OrganizationView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/welcome/WelcomeView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/utils/Utils.kt

Create a "secret" organization view intended for super-admins

---

save-cloud-charts/save-cloud/templates/orchestrator-configmap.yaml
save-cloud-charts/save-cloud/templates/sandbox-configmap.yaml
save-orchestrator-common/src/main/kotlin/com/saveourtool/save/orchestrator/config/ConfigProperties.kt
save-orchestrator-common/src/main/resources/META-INF/save-orchestrator-common/application-mac.properties
save-orchestrator-common/src/main/resources/META-INF/save-orchestrator-common/application-win.properties
save-orchestrator-common/src/test/kotlin/com/saveourtool/save/orchestrator/service/DockerServiceTest.kt
save-orchestrator-common/src/test/resources/application.properties

orchestrator.test-resources.tmp-path is not used

Removed unused property in orchestrator

---

save-cloud-charts/save-cloud/templates/orchestrator-service-account.yaml
save-cloud-charts/save-cloud/templates/sandbox-configmap.yaml
save-cloud-charts/save-cloud/templates/sandbox-deployment.yaml
save-cloud-charts/save-cloud/templates/sandbox-service-account.yaml
save-cloud-charts/save-cloud/values-minikube.yaml
save-cloud-charts/save-cloud/values.yaml
save-sandbox/src/main/resources/bootstrap.yml

* Add `spring.datasource.url` to the ConfigMap
* Enable loading Secrets and ConfigMaps using spring-cloud-kubernetes-client-config
* Remove duplicated Role

Fix Helm configs for Sandbox (in Minikube)

---

save-backend/build.gradle.kts

- fix agent-setting for backend and orchestrator url
- fix saveAgent classpath

Local run fixes

---

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/modal/ModalStyles.kt

This PR closes #1381
* Fixed sizes of `react-modal` (in `Styles`)

Fix for overflowing modal

---

save-backend/backend-api-docs.json
save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/LnkOrganizationTestSuiteController.kt
save-backend/src/main/resources/application.properties

* Set the order in Springdoc OpenAPI spec in aim to avoid extra changes by CI
OpenAPI plugin have no any options corresponding to ordering, but probably swagger configuration can fix it. Anyway the alphabetic order seem to be preferable

Order in Springdoc OpenAPI

---

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/organizations/ManageGitCredentialsCard.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/projects/ProjectSettingsMenu.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/modal/ModalStyles.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/utils/Utils.kt

This PR closes #1398
* Fixed `defaultModalStyle`
* Removed global role alert from `ManageGitCredentialsCard`

Several minor frontend fixes

---

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/HistoryView.kt

- added a button to clear the calendar

Added a button to clear the calendar

---

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/TopBar.kt
save-frontend/webpack.config.d/optimizations.js

Fixed dropdown

---

api-gateway/build.gradle.kts
api-gateway/src/main/kotlin/com/saveourtool/save/gateway/SaveGateway.kt
api-gateway/src/main/kotlin/com/saveourtool/save/gateway/security/WebSecurityConfig.kt
api-gateway/src/main/kotlin/com/saveourtool/save/gateway/utils/AuthUtils.kt

* Exclude DataSourceAutoConfiguration from api-gateway

Exclude DataSourceAutoConfiguration from api-gateway

---

api-gateway/src/main/kotlin/com/saveourtool/save/gateway/security/WebSecurityConfig.kt
gradle/libs.versions.toml
save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/demo/DemoAdditionalParams.kt
save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/demo/DemoResult.kt
save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/demo/diktat/DiktatDemoAdditionalParams.kt
save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/demo/diktat/DiktatDemoMode.kt
save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/demo/diktat/DiktatDemoResult.kt
save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/demo/diktat/DiktatDemoRunRequest.kt
save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/demo/diktat/DiktatDemoTool.kt
save-sandbox/build.gradle.kts
save-sandbox/src/main/kotlin/com/saveourtool/save/sandbox/controller/DiktatDemoController.kt
save-sandbox/src/main/kotlin/com/saveourtool/save/sandbox/service/AbstractDemoService.kt
save-sandbox/src/main/kotlin/com/saveourtool/save/sandbox/service/DiktatDemoService.kt

This PR is connected with #1415
* Added AbstractDemoService interface
* Added DiktatDemoController
* Added DiktatDemoService
* Added DiktatDemoMode enum
* Added DiktatDemoTool enum

[Sandbox] DemoService

---

.github/workflows/deploy_images.yml
buildSrc/src/main/kotlin/com/saveourtool/save/buildutils/DockerStackConfiguration.kt
docker-compose.yaml
save-demo/src/main/resources/application.properties

* Added `save-demo` to `docker-compose`

Adding save-demo to docker-compose

---

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/contests/ContestSummaryMenu.kt

* ContestSummaryMenu improvements

ContestSummaryMenu improvements 

---

db/test-data/organization-insert.xml
db/test-data/sqlRequests/organization.csv
db/v-2/tables/lnk-user-organization.xml
save-backend/backend-api-docs.json
save-backend/src/main/kotlin/com/saveourtool/save/backend/repository/OrganizationRepository.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/service/OrganizationService.kt
save-backend/src/test/kotlin/com/saveourtool/save/backend/DownloadFilesTest.kt
save-backend/src/test/kotlin/com/saveourtool/save/backend/controller/OrganizationControllerTest.kt
save-backend/src/test/kotlin/com/saveourtool/save/backend/controller/PermissionControllerTest.kt
save-backend/src/test/kotlin/com/saveourtool/save/backend/security/OrganizationPermissionEvaluatorTest.kt
save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/entities/Organization.kt
save-frontend/src/test/kotlin/com/saveourtool/save/frontend/components/views/OrganizationViewTest.kt
save-frontend/src/test/kotlin/com/saveourtool/save/frontend/components/views/ProjectViewTest.kt

Removed ownerId from Organization

---

db/test-data/project-insert.xml
db/v-2/tables/lnk-user-organization.xml
db/v-2/tables/lnk-user-project.xml
save-backend/backend-api-docs.json
save-backend/src/test/kotlin/com/saveourtool/save/backend/DownloadFilesTest.kt
save-backend/src/test/kotlin/com/saveourtool/save/backend/controller/ProjectControllerTest.kt
save-backend/src/test/kotlin/com/saveourtool/save/backend/security/ProjectPermissionEvaluatorTest.kt
save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/entities/Project.kt
save-frontend/src/test/kotlin/com/saveourtool/save/frontend/components/views/ProjectViewTest.kt

Remove `project.user_id`

---

db/v-2/tables/lnk-user-organization.xml
db/v-2/tables/lnk-user-project.xml

error with zero ids

---

save-demo/src/main/kotlin/com/saveourtool/save/demo/SaveDemo.kt
save-demo/src/main/kotlin/com/saveourtool/save/demo/config/ConfigProperties.kt
save-demo/src/main/kotlin/com/saveourtool/save/demo/storage/ToolKey.kt
save-demo/src/main/kotlin/com/saveourtool/save/demo/storage/ToolStorage.kt
save-demo/src/main/resources/application-mac.properties
save-demo/src/main/resources/application.properties

* Added `ToolKey`
* Implemented `ToolStorage`
* Updated `application.properties`
* Added `application-mac.properties`
* Added `save-demo` configuration

ConfigProperties and Storage for demo

---

gradle/libs.versions.toml
save-demo/build.gradle.kts
save-demo/src/main/resources/application-dev.properties
save-demo/src/main/resources/application.properties

* Removed `diktat` from `save-demo` deps
* Removed `ktlint` from `save-demo` deps
* Removed ktlint version from libs.versions.toml
* Fixed storage location configs for save-demo

Remove unused deps from save-demo

---

save-frontend/build.gradle.kts
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/externals/sigma/ReactSigma.kt
yarn.lock

* Added kotlin wrapper for `useLoadGraph` hook from `@react-sigma/core`
* Added kotlin wrapper for `sigmaContainer` FC from `@react-sigma/core`
1. Define graph-loader `VFC`
```Kotlin
private val loadGraph = VFC {
val loadGraphCallback = useLoadGraph()
useEffect(loadGraphCallback) {
loadGraphCallback(js(" { attributes: {name: 'My Graph'}, nodes: [{key: 'Thomas'}, {key: 'Eric'}], edges: [{source: 'Thomas', target: 'Eric'}] }"))
}
}
```
2. Use `sigmaContainer` with graph loader (do not forget to put `css`)
```Kotlin
kotlinext.js.require("@react-sigma/core/lib/react-sigma.min.css")
sigmaContainer {
style = jso {
height = "500px"
width = "500px"
}
loadGraph()
}
```
In order to make this code work we need to add some layout in order to make sigma place the nodes (assign `x` and `y` coordinates …

react-sigma support

---

save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/demo/cpg/CpgEdge.kt
save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/demo/cpg/CpgGraph.kt
save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/demo/cpg/CpgNode.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/externals/sigma/CpgUtils.kt

* Added node color generation
* Added default parameters for CpgGraph, CpgEdge, CpgNode
* Added utility functions to color graphs on frontend
https://user-images.githubusercontent.com/35039155/202752115-ae890740-e47a-471f-8cc9-9019b940e6af.mov

Colorful graphs

---

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/ExecutionView.kt

* Reset current page after filtering in history view

Reset current page after filtering in history view

---

db/db.changelog-master.xml
db/v-2/events/db.changelog-events.xml
db/v-2/events/event_scheduler.xml

Delete execution event

---

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/BuilderComponent.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/demo/CpgView.kt

* Added a graph placeholder on `CpgView`

Graph placeholder on CpgView

---

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/DemoComponent.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/demo/CpgView.kt

* Reworked CpgView structure
* Renamed BuilderComponent to be DemoComponent

CpgView improvements

---

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/DemoComponent.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/demo/CpgView.kt

* Added request from frontend to backend to save code into DB and get ID
* Improved frontend visuals to support ID alert box
https://user-images.githubusercontent.com/35039155/203585726-0275f2f5-f9a1-4927-9d86-26e5a62450d0.mov

[CPG] Phase I of front-back integration

---

authentication-service/src/main/kotlin/com/saveourtool/save/authservice/config/WebSecurityConfig.kt

* Added `/projects/by-filters` to `publicEndpoints`

Add `/projects/by-filters` to publicEndpoints

---

api-gateway/src/main/resources/application.yml
save-cloud-charts/save-cloud/templates/gateway-configmap.yaml
save-cloud-charts/save-cloud/values.yaml
save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/demo/cpg/CpgEdge.kt
save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/demo/cpg/CpgGraph.kt
save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/demo/cpg/CpgNode.kt
save-demo-cpg/build.gradle.kts
save-demo-cpg/src/main/kotlin/com/saveourtool/save/demo/cpg/controller/CpgController.kt
save-demo-cpg/src/main/kotlin/com/saveourtool/save/demo/cpg/utils/CpgUtils.kt
save-frontend/build.gradle.kts
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/demo/CpgView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/externals/sigma/LayoutCircular.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/externals/sigma/LayoutInstance.kt

* Made `/get-result` endpoint return `CpgGraph` of analyzed code
* Made frontend fetch and display `CpgGraph` from backend
* Added `@react-sigma/layout-circular`
* Replaced `useLayoutRandom` with `useLayoutCircular`
https://user-images.githubusercontent.com/35039155/204020603-be808bf4-446c-4ead-93d2-109eaa0ff616.mov

[CPG] Phase II of front-back integration

---

save-orchestrator-common/src/main/kotlin/com/saveourtool/save/orchestrator/service/AgentService.kt
save-orchestrator-common/src/main/kotlin/com/saveourtool/save/orchestrator/service/OrchestratorAgentService.kt
save-orchestrator-common/src/test/kotlin/com/saveourtool/save/orchestrator/controller/agents/AgentsControllerTest.kt
save-orchestrator-common/src/test/kotlin/com/saveourtool/save/orchestrator/controller/heartbeat/HeartbeatControllerTest.kt
save-orchestrator-common/src/test/kotlin/com/saveourtool/save/orchestrator/docker/DockerContainerManagerTest.kt
save-orchestrator-common/src/test/kotlin/com/saveourtool/save/orchestrator/docker/KubernetesManagerTest.kt
save-orchestrator-common/src/test/kotlin/com/saveourtool/save/orchestrator/service/DockerServiceTest.kt
save-orchestrator/src/main/kotlin/com/saveourtool/save/orchestrator/service/BackendOrchestratorAgentService.kt
save-sandbox/src/main/kotlin/com/saveourtool/save/sandbox/controller/SandboxController.kt
save-sandbox/src/main/kotlin/com/saveourtool/save/sandbox/service/SandboxOrchestratorAgentService.kt

Refactoring logging (extracted from #1368):
* renamed `AgentRepository` to `OrchestratorAgentService `

Renamed `AgentRepository`

---

save-cloud-charts/save-cloud/templates/backend-configmap.yaml
save-cloud-charts/save-cloud/templates/backend-deployment.yaml
save-cloud-charts/save-cloud/templates/fs-storage-pvc.yaml
save-cloud-charts/save-cloud/templates/sandbox-deployment.yaml

- Create separate PVCs for backend's and sandbox's storage
- Add missing property to backend's ConfigMap

[Helm] Create separate PVCs for backend's and sandbox's storage

---

save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/demo/cpg/CpgGraph.kt
save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/demo/cpg/CpgResult.kt
save-frontend/build.gradle.kts
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/DemoComponent.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/demo/CpgView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/externals/sigma/layouts/LayoutCircular.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/externals/sigma/layouts/LayoutForceAtlas2.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/externals/sigma/layouts/LayoutInstance.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/externals/sigma/layouts/LayoutRandom.kt
yarn.lock

* Added `layout-forceatlas2`
* Fixed `Show Logs` button to hide logs if shown
https://user-images.githubusercontent.com/35039155/205352976-46aee085-ce48-4d54-8f26-85970e5855a8.mov

[CPG] `layout-forceatlas2`

---

db/test-data/sqlRequests/awesome-benchmarks.csv
save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/entities/benchmarks/BenchmarkEntity.kt

Change benchmark category

---

save-cloud-charts/save-cloud/templates/demo-deployment.yaml

Increase demo pod memory

---

save-cloud-charts/save-cloud/templates/backend-configmap.yaml
save-cloud-charts/save-cloud/templates/demo-configmap.yaml
save-cloud-charts/save-cloud/templates/demo-cpg-configmap.yaml
save-cloud-charts/save-cloud/templates/orchestrator-configmap.yaml

backend, orchestrator, demo and demo cpg

logging.level.org.springframework=DEBUG

---

save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/demo/diktat/DiktatDemoResult.kt
save-demo/src/main/kotlin/com/saveourtool/save/demo/runners/cli/DiktatCliRunner.kt
save-demo/src/main/kotlin/com/saveourtool/save/demo/service/DiktatDemoService.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/DiktatDemoComponent.kt

* Added logs and terminationCode to be passed from save-demo to frontend

Provide launch logs

---

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/DiktatDemoComponent.kt

* Fixed logs display on frontend

[DEMO] Fix logs display on FE

---

.github/workflows/helm_push.yml
save-cloud-charts/save-cloud/templates/ingress.yaml
save-cloud-charts/save-cloud/templates/neo4j-service.yaml
save-cloud-charts/save-cloud/values.yaml

- Add Ingress for neo4j's tcp-bolt port 7687
- Fix checkout operation in `helm_deploy.yml`

Add separate Ingress for neo4j 7687

---

save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/demo/diktat/DemoAdditionalParams.kt
save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/demo/diktat/DiktatDemoResult.kt
save-demo/src/main/kotlin/com/saveourtool/save/demo/controller/DiktatDemoController.kt
save-demo/src/main/kotlin/com/saveourtool/save/demo/runners/Runner.kt
save-demo/src/main/kotlin/com/saveourtool/save/demo/runners/cli/CliRunner.kt
save-demo/src/main/kotlin/com/saveourtool/save/demo/runners/cli/DiktatCliRunner.kt
save-demo/src/main/kotlin/com/saveourtool/save/demo/service/DiktatDemoService.kt
save-demo/src/main/kotlin/com/saveourtool/save/demo/utils/Constants.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/TopBar.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/DiktatDemoComponent.kt

* Fixed an issue with crashes of diktat fix - set env's `JAVA_TOOL_OPTIONS` and `_JAVA_OPTIONS` to empty string
* Added `Demo` dropdown to `top bar` at frontend
* Improved diktat temp configuration - now there always is default `diktat-analysis.yaml` and `src` is in path to working dir
* Added `Constants.kt` file with demo's constants

[DEMO] Major diktat-demo improvements

---

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/cpg/GraphEvents.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/cpg/GraphLoader.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/demo/CpgView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/externals/sigma/ReactSigma.kt

* Added kotlin wrapper for `useSetSettings` hook from `@react-sigma/core`
* Added kotlin wrapper for `useRegisterEvents` hook from `@react-sigma/core`
* Added kotlin wrapper for `useSigma` hook from `@react-sigma/core`
* Moved `graphLoader` to separate file
* Added `graphEvents` that defines the event handlers for sigma graph
* Added `graphEvents` to `sigmaContainer` on `cpgView`
https://user-images.githubusercontent.com/35039155/206671305-3201f70d-e9e0-4655-b026-69eb1eb17e34.mov

[CPG] react-sigma events

---

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/DemoComponent.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/externals/fontawesome/Icons.kt

* Added `faInfoCircle`
* Replaced buttons containing text with buttons containing icon
* Added tooltips for buttons on `CpgView`

[CPG] Replace button text with icon

---

save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/demo/cpg/CpgGraph.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/DemoComponent.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/cpg/GraphLoader.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/demo/CpgView.kt

* Added `SigmaLayout` enum
* Added an ability to select `SigmaLayout` on `cpgView`
* Improved tool panel on `cpgView`
https://user-images.githubusercontent.com/35039155/207645388-e7bfca43-b2f4-4020-9375-59819a85fe10.mov

[CPG] Layout selector

---

save-orchestrator-common/src/main/kotlin/com/saveourtool/save/orchestrator/docker/DockerContainerRunner.kt
save-orchestrator-common/src/main/kotlin/com/saveourtool/save/orchestrator/kubernetes/KubernetesManager.kt
save-orchestrator-common/src/main/kotlin/com/saveourtool/save/orchestrator/runner/ContainerRunner.kt
save-orchestrator-common/src/main/kotlin/com/saveourtool/save/orchestrator/service/AgentService.kt
save-orchestrator-common/src/main/kotlin/com/saveourtool/save/orchestrator/service/ContainerService.kt
save-orchestrator-common/src/test/kotlin/com/saveourtool/save/orchestrator/docker/KubernetesManagerTest.kt

- combined cleanup[ByExecution] and stop[ByExecution]
- added ContainerRunner.Prunable and ContainerRunner.Stoppable -- only docker does implement it
- removed discover method

Refactoring in ContainerRunner

---

save-orchestrator-common/src/main/kotlin/com/saveourtool/save/orchestrator/controller/AgentsController.kt
save-orchestrator-common/src/main/kotlin/com/saveourtool/save/orchestrator/docker/DockerContainerRunner.kt
save-orchestrator-common/src/main/kotlin/com/saveourtool/save/orchestrator/runner/ContainerRunner.kt
save-orchestrator-common/src/main/kotlin/com/saveourtool/save/orchestrator/service/ContainerService.kt
save-orchestrator-common/src/main/kotlin/com/saveourtool/save/orchestrator/service/HeartBeatInspector.kt
save-orchestrator-common/src/test/kotlin/com/saveourtool/save/orchestrator/controller/agents/AgentsControllerTest.kt
save-orchestrator-common/src/test/kotlin/com/saveourtool/save/orchestrator/controller/heartbeat/HeartbeatControllerTest.kt
save-orchestrator-common/src/test/kotlin/com/saveourtool/save/orchestrator/service/ContainerServiceTest.kt

- removed ContainerRunner.Stoppable
- removed usage of /stopAgents

Delete stop container operation

---

save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/utils/ReactorUtils.kt
save-orchestrator-common/src/main/kotlin/com/saveourtool/save/orchestrator/controller/HeartbeatController.kt
save-orchestrator-common/src/main/kotlin/com/saveourtool/save/orchestrator/service/ContainerService.kt
save-orchestrator-common/src/test/kotlin/com/saveourtool/save/orchestrator/controller/agents/AgentsControllerTest.kt

* reused in heartbeat controller
* reused in container service

Introduced `waitReactivelyUntil`

---

save-cloud-charts/save-cloud/templates/demo-configmap.yaml
save-cloud-charts/save-cloud/templates/demo-deployment.yaml
save-cloud-charts/save-cloud/templates/mysql-deployment.yaml
save-cloud-charts/save-cloud/values.yaml

* Configured save-demo to be able to interact with mysql database in terms of kubernetes

[DEMO] db support ph.IV

---

docker-compose.yaml
save-cloud-charts/save-cloud/README.md
save-cloud-charts/save-cloud/templates/demo-deployment.yaml
save-demo/src/main/resources/META-INF/spring.factories

* Added `docker-secrets` profile to `docker-compose.yaml` demo section
* Added `spring.factories` to enable `DockerSecretsDatabaseProcessor` in `save-demo`

[DEMO] hotfix for db support ph.IV

---

save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/ExecutionController.kt
save-orchestrator-common/src/main/kotlin/com/saveourtool/save/orchestrator/service/AgentService.kt
save-orchestrator-common/src/main/kotlin/com/saveourtool/save/orchestrator/service/OrchestratorAgentService.kt
save-orchestrator/src/main/kotlin/com/saveourtool/save/orchestrator/service/BackendOrchestratorAgentService.kt
save-sandbox/src/main/kotlin/com/saveourtool/save/sandbox/service/SandboxOrchestratorAgentService.kt

- added checking execution status
- added/moved logging when containers are not stopped or execution is already in finale stage
It closes #1656

Added checking execution status on finalization method

---

save-backend/src/main/kotlin/com/saveourtool/save/backend/service/ExecutionService.kt

Update bestScore only when Execution.status is FINISHED

---

save-orchestrator-common/src/main/kotlin/com/saveourtool/save/orchestrator/service/ContainerService.kt

- `curl` is run with `--fail` so that it fails early.
- `errexit` and `nounset` shell options enabled (in addition to `xtrace`).
- This fixes #1663.

Add `--fail` to the list of `curl` options

---

save-backend/backend-api-docs.json
save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/TestSuitesSourceController.kt
save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/entities/DtoWithId.kt
save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/testsuite/TestSuiteDto.kt
save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/testsuite/TestSuitesSourceDto.kt
save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/entities/TestSuite.kt
save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/entities/TestSuitesSource.kt
save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/spring/entity/BaseEntityWithDto.kt
save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/spring/entity/BaseEntityWithDtoWithId.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/organizations/OrganizationTestsMenu.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/organizations/TestSuitesSourcesDisplayer.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/testsuitessources/TestSuiteSourceUpsertComponent.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/utils/RequestUtils.kt

* refactored DtoWithId to abstract class
* changed TestSuite and TestSuitesSource
It's part of #1670

Refactored DtoWithId

---

save-backend/backend-api-docs.json
save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/DemoManagerController.kt
save-demo/src/main/kotlin/com/saveourtool/save/demo/controller/ManagementController.kt
save-demo/src/main/kotlin/com/saveourtool/save/demo/service/DemoService.kt

This PR closes #1682
* Added endpoint on `backend` to upload files to `demo`'s storage
* Added endpoint on `demo` to upload files to storage

[DEMO] upload files to storage manually

---

save-backend/backend-api-docs.json
save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/DemoManagerController.kt

- check permission in ```DemoManagerController```
- added method annotation (ApiResponse and Parameters)
This pull request close backend path #1676

demo manager controller check permission in backend

---

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/projects/ProjectDemoMenu.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/ProjectView.kt

- added a modal window with information about request errors 
This pull request close frontend path in #1676
Close #1676

demo manager controller check permission in frontend

---

save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/ExecutionController.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/repository/LnkExecutionTestSuiteRepository.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/service/ExecutionService.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/service/LnkExecutionTestSuiteService.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/service/TestSuitesService.kt
save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/entities/Execution.kt

Moved delete and marking as obsolete of Execution to ExecutionService

---

save-backend/src/main/kotlin/com/saveourtool/save/backend/storage/MigrationFileStorage.kt
save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/entities/FileDto.kt
save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/storage/AbstractMigrationStorage.kt
save-orchestrator-common/src/main/kotlin/com/saveourtool/save/orchestrator/utils/AgentStatusInMemoryRepository.kt

- added AbstractMigrationStorage
- refactored MigrationFileStorage
It's part of #1670

Added AbstractMigrationStorage

---

build.gradle.kts
save-frontend/build.gradle.kts
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/AvatarForm.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/modal/ModalBuilder.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/OrganizationView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/usersettings/UserSettingsView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/externals/imageeditor/ReactAvatarImageCropper.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/http/Requests.kt
yarn.lock

- added avatar editor
Closes #1669

Added avatar editor

---

save-backend/src/main/kotlin/com/saveourtool/save/backend/storage/TestSuitesSourceSnapshotStorage.kt

support '/' in version for tests source snapshot

---

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/test/analysis/TestMetricsView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/routing/BasicRouting.kt

This is a part of Flaky Test Detector, see #659.

UI improvements

---

save-backend/src/main/kotlin/com/saveourtool/save/backend/service/TestAnalysisService.kt

This is a part of Flaky Test Detector, see #659.

Fix the sequential/parallel behaviour when `replay()` is invoked via JMX

---

save-backend/src/main/kotlin/com/saveourtool/save/backend/storage/FileStorage.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/storage/TestsSourceSnapshotStorage.kt
save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/storage/AbstractStorageWithDatabase.kt

Make `repository` available for child in `AbstractStorageWithDatabase`

---

buildSrc/src/main/kotlin/com/saveourtool/save/buildutils/DockerStackConfiguration.kt

- register a new service for docker stack: minio
- run creating a bucket `cnb` on start
It closes #1763

Minio for local run

---

buildSrc/src/main/kotlin/com/saveourtool/save/buildutils/DockerStackConfiguration.kt
save-backend/backend-api-docs.json
save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/DemoManagerController.kt
save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/demo/DemoDto.kt
save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/domain/ProjectCoordinates.kt
save-demo/src/main/kotlin/com/saveourtool/save/demo/controller/ManagementController.kt
save-demo/src/main/kotlin/com/saveourtool/save/demo/service/GithubDownloadToolService.kt
save-demo/src/main/resources/application.properties
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/projects/ProjectDemoMenu.kt

This PR closes #1766
* Made GitHub download optional - initialized only if `githubProjectCoordinates` are null
* Changed hibernate logging level on save-demo to `WARN`
* Added validation on `save-demo` creation

[DEMO] make GitHub download optional

---

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/projects/ProjectDemoMenu.kt

This PR closes #1760
* Added SDK selector to `projectDemoMenu`
* Added an ability to upload files manually using` simpleFileUploader`
* Split the `projectDemoMenu` `FC` into several private `ChildrenBuilder` extension function

[DEMO] file uploading on frontend

---

gradle/libs.versions.toml
save-cloud-common/build.gradle.kts
save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/utils/FileUtils.kt
save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/utils/ReactorUtils.kt
save-preprocessor/src/main/kotlin/com/saveourtool/save/preprocessor/controllers/TestSuitesPreprocessorController.kt
save-preprocessor/src/main/kotlin/com/saveourtool/save/preprocessor/service/GitPreprocessorService.kt
save-preprocessor/src/main/kotlin/com/saveourtool/save/preprocessor/service/TestDiscoveringService.kt
save-preprocessor/src/main/kotlin/com/saveourtool/save/preprocessor/service/TestsPreprocessorToBackendBridge.kt
save-preprocessor/src/main/kotlin/com/saveourtool/save/preprocessor/utils/GitUtil.kt
save-preprocessor/src/test/kotlin/com/saveourtool/save/preprocessor/service/TestDiscoveringServiceTest.kt

`@Blocking`/`@NonBlocking` annotations have been added as necessary.

Wrap blocking operations into `blockingToMono {}`

---

save-backend/src/main/kotlin/com/saveourtool/save/backend/storage/TestsSourceSnapshotStorage.kt

Migrated TestsSourceSnapshotStorage to S3

---

.run/SaveApplication-LocalRunOnWindows.run.xml
save-backend/backend-api-docs.json
save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/AvatarController.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/FileController.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/internal/TestSuitesSourceInternalController.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/storage/AvatarStorage.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/storage/DebugInfoStorage.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/storage/ExecutionInfoStorage.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/utils/ReactorUtils.kt
save-backend/src/test/kotlin/com/saveourtool/save/backend/DownloadFilesTest.kt
save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/utils/Constants.kt
save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/s3/DefaultS3Operations.kt
save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/s3/S3Operations.kt
save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/s3/S3OperationsProperties.kt
save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/storage/AbstractFileBasedStorage.kt
save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/storage/AbstractMigrationStorage.kt
save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/storage/AbstractS3Storage.kt
save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/storage/AbstractStorageWithDatabase.kt
save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/storage/Storage.kt
save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/utils/ReactorUtils.kt
save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/utils/SpringUtils.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/fileuploader/HeavyFileUploader.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/OrganizationView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/RegistrationView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/usersettings/UserSettingsView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/http/Requests.kt
save-preprocessor/src/main/kotlin/com/saveourtool/save/preprocessor/service/TestsPreprocessorToBackendBridge.kt
save-sandbox/src/main/kotlin/com/saveourtool/save/sandbox/controller/SandboxController.kt
save-sandbox/src/main/kotlin/com/saveourtool/save/sandbox/controller/SandboxInternalController.kt

* added a custom header for Content-Length for multipart-data upload
* migrated to upload with contentLength
* removed upload without contentLength since S3 is target implementation
* refactored method names
It closes #1814

Migrated to upload using content-length

---

save-demo/src/main/kotlin/com/saveourtool/save/demo/controller/ManagementController.kt
save-demo/src/main/kotlin/com/saveourtool/save/demo/storage/ToolStorage.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/fileuploader/SimpleFileUploader.kt

* Added endpoint for demo zip download
* Changed `post` to `postUploadFile`

[DEMO] file uploading updates

---

save-demo-agent/src/nativeMain/kotlin/com/saveourtool/save/demo/agent/utils/SetupUtils.kt

save-demo-agent download-files-as-zip

---

.github/workflows/deploy_images.yml

* Supported `save-demo-agent.kexe` upload in `deploy_images.yml`

Upload save-demo-agent.kexe

---

save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/DemoManagerController.kt
save-demo-agent/src/nativeMain/kotlin/com/saveourtool/save/demo/agent/utils/SetupUtils.kt
save-demo/src/main/kotlin/com/saveourtool/save/demo/controller/DependencyController.kt
save-demo/src/main/kotlin/com/saveourtool/save/demo/controller/ManagementController.kt

* Moved all endpoints that are connected with files to `DependencyController` (`/demo/internal/files`)
* Changed base path for `ManagementController` (`/demo/internal/manager`)
* Fixed all existing demo request urls

[DEMO] DependencyController

---

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/projectcollection/CollectionView.kt

Added filter in CollectionViewState

---

save-cloud-charts/save-cloud/templates/demo-configmap.yaml
save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/utils/AgentDownloadUtils.kt
save-demo/src/main/kotlin/com/saveourtool/save/demo/controller/DependencyController.kt
save-demo/src/main/kotlin/com/saveourtool/save/demo/service/KubernetesService.kt
save-demo/src/main/kotlin/com/saveourtool/save/demo/utils/KubernetesUtils.kt
save-demo/src/main/resources/application-dev.properties
save-orchestrator-common/src/main/kotlin/com/saveourtool/save/orchestrator/service/ContainerService.kt

* Moved curl building command logic to `AgentDownloadUtils.kt`
* Implemented startup command logic that uses `AgentDownloadUtils` in order to build startup command
* Added `/download-agent` endpoint to `DependencyController` of `save-demo`
* Updated configuration on `demo-configmap.yaml`

Download save-demo-agent to pod

---

save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/FileController.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/internal/TestSuitesSourceInternalController.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/storage/FileStorage.kt
save-backend/src/test/kotlin/com/saveourtool/save/backend/DownloadFilesTest.kt
save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/storage/AbstractMigrationStorage.kt
save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/storage/AbstractS3Storage.kt
save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/storage/AbstractStorageWithDatabase.kt
save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/storage/Storage.kt
save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/utils/SpringUtils.kt
save-preprocessor/build.gradle.kts

* returns `key` on upload
* only S3 implementation is expected for database impl
Extracted from #1867

Updated `Storage` interface

---

gradle/libs.versions.toml
settings.gradle.kts

* Added `saveourtool/okio-extras` to `settings.gradle.kts`
https://github.com/saveourtool/save-cli/commit/67267e58aff886359a9461b2da21a0b998e4bb80

okio-extras

---

save-demo/src/main/kotlin/com/saveourtool/save/demo/controller/DependencyController.kt
save-demo/src/main/kotlin/com/saveourtool/save/demo/controller/ManagementController.kt
save-demo/src/main/kotlin/com/saveourtool/save/demo/repository/GithubRepoRepository.kt
save-demo/src/main/kotlin/com/saveourtool/save/demo/repository/SnapshotRepository.kt
save-demo/src/main/kotlin/com/saveourtool/save/demo/repository/ToolRepository.kt
save-demo/src/main/kotlin/com/saveourtool/save/demo/service/GithubRepoService.kt
save-demo/src/main/kotlin/com/saveourtool/save/demo/service/ToolService.kt
save-demo/src/main/kotlin/com/saveourtool/save/demo/utils/SystemUtils.kt

save-demo cleanup

---

save-cloud-charts/save-cloud/values.yaml

* Fixed amount of loki replicas
https://github.com/grafana/loki/issues/8443

Hotfix for loki deployment

---

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/DemoRunComponent.kt

* Fixed url for demo run request on frontend (removed odd `/`)

Bugfix for demo run request

---

save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/validation/FrontendRoutes.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/topbar/TopBar.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/topbar/TopBarLinks.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/FossGraphView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/routing/BasicRouting.kt

* Added FossGraph view for security vulnerabilities database

Security vulnerabilities database

---

save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/RunExecutionController.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/internal/AgentsController.kt
save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/storage/impl/AbstractInternalFileStorage.kt
save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/storage/impl/InternalFileKey.kt
save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/utils/AgentDownloadUtils.kt
save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/utils/ExceptionUtils.kt
save-demo/src/main/kotlin/com/saveourtool/save/demo/service/KubernetesService.kt
save-demo/src/main/kotlin/com/saveourtool/save/demo/storage/DemoInternalFileStorage.kt
save-sandbox/src/main/kotlin/com/saveourtool/save/sandbox/service/SandboxOrchestratorAgentService.kt

- added `fileName` to `InternalFileKey`
- updated `name` in `InternalFileKey`
- supported `InternalFileKey.fileName` in `AbstractInternalFileStorage`
- added a function `AbstractInternalFileStorage.generateRequiredUrlToDownload`
It's extracted from #1916

Updated `InternalFileKey`

---

save-backend/backend-api-docs.json
save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/DemoManagerController.kt
save-cloud-charts/save-cloud/templates/s3-deployment.yaml
save-demo/src/main/kotlin/com/saveourtool/save/demo/controller/ManagementController.kt
save-demo/src/main/kotlin/com/saveourtool/save/demo/service/DemoService.kt
save-demo/src/main/kotlin/com/saveourtool/save/demo/service/KubernetesService.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/projects/ProjectDemoMenu.kt

This PR closes #1922
* Implemented demo deletion
* Added frontend button that would delete demo
* Added `ttlSecondsAfterFinished` to `s3-deployment.yaml` in order to clean the startup job (`minio-create-bucket`)

Demo deletion

---

save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/storage/key/AbstractS3KeyDatabaseManager.kt

- added open to `blockingBridge`
It closes #1932

Spring's `proxy` for closed property

---

build.gradle.kts
buildSrc/src/main/kotlin/com/saveourtool/save/buildutils/DatabaseUtils.kt
buildSrc/src/main/kotlin/com/saveourtool/save/buildutils/DockerStackConfiguration.kt
gradle/libs.versions.toml
save-demo/src/main/resources/application-dev.properties
save-sandbox/src/main/resources/application-dev.properties

- remove a container to create a bucket
- moved liquibase to docker's container run
It duplicates #1897 and is required for #1880

Dev infra cleanup

---

save-cloud-common/src/nativeMain/kotlin/com/saveourtool/save/utils/FileUtils.kt
save-demo-agent/src/nativeMain/kotlin/com/saveourtool/save/demo/agent/SimpleRunner.kt
save-demo/src/main/kotlin/com/saveourtool/save/demo/controller/ManagementApiController.kt
save-demo/src/main/kotlin/com/saveourtool/save/demo/service/KubernetesService.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/projects/ProjectDemoMenu.kt

This PR closes #1950
* Decreased `save-demo` requests `TIMEOUT`
* Decreased `save-demo` requests retries number
* Increased `SimpleRunner` timeout

save-demo-agent cleanups

---

save-backend/src/main/kotlin/com/saveourtool/save/backend/SaveApplication.kt

Adding `typealias`'es, [removing](https://github.com/saveourtool/save-cloud/pull/1956) `typealias`'es...

Add more type aliases

---

save-backend/backend-api-docs.json
save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/vulnerability/VulnerabilityController.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/vulnerability/VulnerabilityProjectController.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/repository/vulnerability/VulnerabilityProjectRepository.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/repository/vulnerability/VulnerabilityRepository.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/service/vulnerability/VulnerabilityProjectService.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/service/vulnerability/VulnerabilityService.kt

* Added controller, service for VulnerabilityProject
Closes #1958

FossGraph. Created controller for VulnerabilityProject

---

buildSrc/src/main/kotlin/com/saveourtool/save/buildutils/DockerStackConfiguration.kt
save-backend/backend-api-docs.json
save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/DemoManagerController.kt
save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/utils/KotlinUtils.kt
save-demo-agent/src/nativeMain/kotlin/com/saveourtool/save/demo/agent/Server.kt
save-demo/src/main/kotlin/com/saveourtool/save/demo/storage/DependencyStorage.kt
save-demo/src/main/kotlin/com/saveourtool/save/demo/utils/KubernetesUtils.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/projects/ProjectDemoMenu.kt

* Improved logging on save-demo-agent
* Fixed URLs on projectDemoMenu
* Fixed getDemoInfo in DemoManagerController
* Fixed registerLiquibaseTask name (reqisterLiquibaseTask -> registerLiquibaseTask)
* Removed PreAuthorization annotations from DemoManagerController

save-demo-agent logging improvements

---

save-demo-agent/build.gradle.kts
save-demo-agent/src/nativeMain/kotlin/com/saveourtool/save/demo/agent/utils/HttpUtils.kt
save-demo/src/main/kotlin/com/saveourtool/save/demo/service/KubernetesService.kt

* Added `ktor.content.negotiation` to `save-demo-agent` dependencies
* Enabled `ContentNegotiation` plugin for ktor client
* Fixed `getStatus` method of `KubernetesService`
Have been debugging it for the whole day

Hotfix for save-demo-agent ktor HttpClient

---

save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/DemoManagerController.kt

* Changed `asyncEffect` to `doOnSuccess` in order to initialize file download after the response is received

Tool should be uploaded to save-demo asynchronously

---

save-demo-agent/src/nativeMain/kotlin/com/saveourtool/save/demo/agent/utils/SetupUtils.kt
save-demo/src/main/kotlin/com/saveourtool/save/demo/controller/DemoController.kt
save-demo/src/main/kotlin/com/saveourtool/save/demo/service/KubernetesService.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/DemoRunComponent.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/codeeditor/CodeEditorComponent.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/demo/DemoView.kt

* Fixed frontend error when no demo result was shown
* Fixed deserialization error on `demoView`
* Fixed logging in `KubernetesService`

Frontend doesn't show demo result

---

save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/entities/vulnerability/VulnerabilityProjectDto.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/fossgraph/CreateVulnerabilityView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/fossgraph/FossGraphView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/fossgraph/VulnerabilityProjectWindow.kt

* added window for add new vulnerabilities
Closes #1987

FossGraph. Add modal window for add new vulnerabilities

---

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/fossgraph/CreateVulnerabilityView.kt

* added list projects on CreateVulnerabilityView
Closes #1991

FossGraph. Added list projects on CreateVulnerabilityView

---

save-orchestrator/src/main/resources/application-minikube.properties
save-sandbox/src/main/resources/application-minikube.properties

This PR closes #1967
* Added `minikube` profile configuration for `save-orchestrator`
* Added `minikube` profile configuration for `save-sandbox`

Minikube profile

---

gradle/libs.versions.toml
save-demo-cpg/build.gradle.kts
save-demo-cpg/src/main/kotlin/com/saveourtool/save/demo/cpg/SaveDemoCpg.kt
save-demo-cpg/src/main/kotlin/com/saveourtool/save/demo/cpg/service/CpgService.kt
save-demo-cpg/src/main/kotlin/com/saveourtool/save/demo/cpg/utils/CpgUtils.kt
save-demo-cpg/src/main/resources/application.properties
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/demo/CpgView.kt

- reverted `da7060ebceb0db318f750bddc4b039933bdd21d4`
- reverted versions of neo4j drivers and set strictly them
- fixed printing error in logs
It closes #2007

Downgraded CPG version

---

.github/workflows/detekt.yml
.github/workflows/diktat.yml

- added permission `security-events: write`
- `Upload SARIF artifacts` only in case of failure
- upgrade agent to latest ubuntu

Updated actions for diktat and detect

---

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/demo/run/DemoOutputComponent.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/demo/run/DemoRunComponent.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/demo/DemoView.kt

This PR closes #2032
* Improved `demoView`
https://user-images.githubusercontent.com/35039155/227253562-c3191134-4c84-44cc-8816-efaddc989d0b.mov

Demo View improvements

---

.github/workflows/backend-api-spec-update.yml

* Fix `update backend api spec` action

Fix `update backend api spec` action

---

.github/workflows/backend-api-spec-update.yml

* Add configuration for manual trigger the update backend api spec action

Add configuration for manual trigger the update backend api spec action

---

save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/vulnerability/VulnerabilityController.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/repository/vulnerability/VulnerabilityProjectRepository.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/service/vulnerability/VulnerabilityService.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/fossgraph/FossGraphView.kt

* added deleting projects in a vulnerability
Closes #2052

FossGraph. Added deleting projects in a vulnerability

---

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/topbar/TopBarUserField.kt

Fixed avatar in topBar

---

save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/entities/ProjectProblemDto.kt
save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/validation/ValidationErrorMessages.kt
save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/entities/ProjectProblem.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/projects/CreateProjectProblemView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/projects/ProjectSecurityMenu.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/inputform/InputForms.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/routing/BasicRouting.kt

Added view for create project problem
Closes #2078

FossGraph. Added view for create project problem

---

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/FossGraphIntroductionComponent.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/fossgraph/FossGraphCollectionView.kt

FossGraph. Improved Foss Graph view

---

save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/vulnerability/VulnerabilityController.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/repository/vulnerability/VulnerabilityRepository.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/service/vulnerability/VulnerabilityService.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/projects/CreateProjectProblemView.kt

Fixed check vulnerability in project problem

Fixed check vulnerability in project problem

---

save-demo/src/main/kotlin/com/saveourtool/save/demo/service/KubernetesService.kt
save-demo/src/main/kotlin/com/saveourtool/save/demo/utils/KubernetesUtils.kt
save-orchestrator-common/src/main/kotlin/com/saveourtool/save/orchestrator/kubernetes/KubernetesManager.kt

- using agent namespace in orchestrator and demo

Agent namespace in K8S

---

save-cloud-charts/save-cloud/templates/agent-network-policy-orchestrator.yaml

- added port for backend in agent-network-policy-orchestrator.yaml

Add port in network policy

---

save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/ProjectController.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/repository/ProjectProblemRepository.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/service/ProjectProblemService.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/service/ProjectService.kt
save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/filters/ProjectProblemFilter.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/projects/ProjectSecurityMenu.kt

Added tables for open and closed problems in project
Closes #2113

Added tables for open and closed problems in project

---

.github/workflows/deploy_images.yml
.github/workflows/deploy_images_reusable.yml

Fix deploy_images_reusable.yml

---

.github/workflows/backend-api-spec-update.yml

- move pull master before generating OpenAPI
- removed unused parameter

Fix backend-api-spec-update.yml

---

.github/workflows/backend-api-spec-update.yml
save-cloud-charts/save-cloud/templates/agent-backend-service.yaml
save-cloud-charts/save-cloud/templates/agent-orchestrator-service.yaml
save-cloud-charts/save-cloud/templates/agent-sandbox-service.yaml

- added services for backend in agent's name space

Backend service for agents

---

.github/workflows/backend-api-spec-update.yml

- set fetch-depth: 0 <-- this fixes pull issue
- moved git configuration to earlier step <-- author is required to rebase\merge changes from master
---
Not tested case:
1. we have opened PR
2. we changes some endpoint
3. the workflow regenerates `backend-api-docs.json`
4. the workflow tries to create PR but it's already existed...

Fix `backend-api-spec-update.yml`

---

db/test-data/sqlRequests/vulnerability-project.csv
db/test-data/vulnerability-project-insert.xml
db/v-2/tables/vulnerability-project.xml
save-backend/src/main/kotlin/com/saveourtool/save/backend/service/vulnerability/VulnerabilityService.kt
save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/entities/vulnerability/VulnerabilityProjectDto.kt
save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/entities/vulnerabilities/VulnerabilityProject.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/inputform/InputForms.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/fossgraph/FossGraphView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/fossgraph/VulnerabilityProjectWindow.kt

Added version field for projects in vulnerabilities

---

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/modal/ModalStyles.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/externals/modal/ReactModal.kt

* Changed z-index of modals to 1000 (which is extremely high)

Fix for wrong z-index of modals

---

save-backend/src/main/kotlin/com/saveourtool/save/backend/service/ProjectProblemService.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/projects/EditProjectProblemWindow.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/projects/ProjectProblemView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/tables/TableComponent.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/topbar/TopBarLinks.kt

Added window to edit the project problem

---

save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/entities/contest/ContestSampleDto.kt
save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/entities/contest/ContestSampleFieldDto.kt
save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/entities/contest/ContestSampleFieldType.kt
save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/validation/FrontendRoutes.kt
save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/entities/ContestSampleField.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/inputform/InputForms.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/contests/ContestListView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/contests/CreateContestTemplateView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/contests/NewContestTemplateCard.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/contests/NewContestsCard.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/contests/WelcomeContests.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/routing/BasicRouting.kt

- added Create contest template view
- added button to go to the view
Closes #2154

Added a view to create templates for future contests

---

save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/ContestSampleController.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/repository/contest/ContestRepository.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/repository/contest/ContestSampleFieldRepository.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/repository/contest/ContestSampleRepository.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/service/ContestSampleService.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/service/ContestService.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/service/LnkContestExecutionService.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/contests/CreateContestTemplateView.kt

- added services, repositories, controller for contest sample and contest sample fields
- added call save method on frontend
Closes #2157

Added backend for contest sample

---

save-demo-agent/src/nativeMain/kotlin/com/saveourtool/save/demo/agent/Server.kt
save-demo-agent/src/nativeMain/kotlin/com/saveourtool/save/demo/agent/SimpleRunner.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/demo/welcome/FeaturedDemos.kt

* Added time logging for whole runner's request
* Added time logging for ProcessBuilder execution

Demo Agent should log time

---

save-demo/src/main/kotlin/com/saveourtool/save/demo/service/KubernetesService.kt
save-demo/src/main/kotlin/com/saveourtool/save/demo/utils/KubernetesUtils.kt

* Made `getJobByName` search in agent namespace

Fix for demo deletion

---

save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/ContestSampleController.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/service/ContestSampleService.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/contests/ContestListView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/contests/ContestSampleListCard.kt

- added method to get list of contest sample
- added card for contest sample table
Closes #2163

Added card for contest sample list

---

save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/entities/FileDto.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/fileuploader/FileManagerComponent.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/projects/ProjectFilesMenu.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/ProjectView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/utils/ProjectMenuBar.kt

* Added view for file management on project level

ProjectFilesMenu

---

save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/LnkUserOrganizationController.kt

* Removed `authentication` parameter from `/api/$v1/organizations/{organizationName}/users` endpoint

OrganizationView unauthorized fix

---

save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/OrganizationController.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/vulnerability/VulnerabilityController.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/repository/LnkUserOrganizationRepository.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/repository/vulnerability/VulnerabilityRepository.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/service/LnkUserOrganizationService.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/service/vulnerability/VulnerabilityService.kt
save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/info/UserInfo.kt
save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/validation/FrontendRoutes.kt
save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/entities/User.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/topbar/TopBarUserField.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/userprofile/UserProfileView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/userprofile/UserProfileVulnerabilitiesTab.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/externals/fontawesome/BrandIcons.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/externals/fontawesome/Icons.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/routing/BasicRouting.kt
save-frontend/src/test/kotlin/com/saveourtool/save/frontend/components/topbar/TopBarTest.kt

Created user profile view

---

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/UserBoard.kt

**What's done:**
Added a link to the user profile by clicking on the user's avatar in the Organization view and the Project view

Added link to user profile

---

save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/OrganizationController.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/CreateOrganizationView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/utils/RequestUtils.kt

This PR closes #2192
* Added context initialization to `CreateOrganizationView`
* Take a look at `unpackMessage` as it seem to work wrong after IR migration

CreateOrganizationView unauthorized fix

---

save-frontend/build.gradle.kts
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/cpg/GraphEvents.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/cpg/GraphLoader.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/demo/GraphDemoComponent.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/graph/GraphVizVisualizer.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/graph/SigmaGraphVisualizer.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/demo/CpgView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/externals/graph/graphviz/GraphVisualizer.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/externals/graph/graphviz/GraphVizInteractions.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/externals/graph/graphviz/GraphVizLayout.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/externals/graph/graphviz/GraphVizNodeStyle.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/externals/graph/graphviz/GraphVizRenderer.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/externals/graph/sigma/CpgUtils.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/externals/graph/sigma/ReactSigma.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/externals/graph/sigma/layouts/LayoutCircular.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/externals/graph/sigma/layouts/LayoutForceAtlas2.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/externals/graph/sigma/layouts/LayoutInstance.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/externals/graph/sigma/layouts/LayoutRandom.kt
yarn.lock

* Extracted `sigma`-based visualizer into `sigmaGraphVisualizer`
* Added `react-graph-viz-engine` wrappers
* Replace hardcoded graph with `CpgGraph` received from backend
https://github.com/saveourtool/save-cloud/assets/35039155/892b430e-4d01-4bf2-a857-635b2a2d12ec

React Graph Viz Engine Pt.I

---

authentication-service/src/main/kotlin/com/saveourtool/save/authservice/config/WebSecurityConfig.kt
db/test-data/organization-insert.xml
db/test-data/sqlRequests/organization.csv
db/v-2/tables/organization.xml
db/v-2/tables/vulnerability.xml
save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/vulnerability/VulnerabilityController.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/service/vulnerability/VulnerabilityService.kt
save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/entities/OrganizationDto.kt
save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/entities/Organization.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/fossgraph/FossGraphView.kt

- added a rating organization
- added changing the user's rating for adding a vulnerability
- fixed fossGraphView in unauthorized mode

Added a rating organization

---

save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/UsersDetailsController.kt
save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/validation/FrontendRoutes.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/FossGraphIntroductionComponent.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/toprating/OrganizationRatingTab.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/toprating/TopRatingView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/toprating/UserRatingTab.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/routing/BasicRouting.kt

Added a top rating view

---

save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/demo/cpg/CpgGraph.kt
save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/demo/cpg/cytoscape/CytoscapeLayout.kt
save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/demo/cpg/cytoscape/CytoscapeNode.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/demo/GraphDemoComponent.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/graph/CytoscapeVisualizer.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/demo/CpgView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/externals/graph/cytoscape/CytoscapeWrapper.kt

* Fixed layout selector
* Fixed styles a bit
* Fix visuals
* Fix an issue with graph rerender on state change

cytoscape layouts

---

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/topbar/TopBarLinks.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/userprofile/UserProfileView.kt

- fixed user profile props
- fixed size of Vuln archive in top bar

Fixed user profile props and size of Vuln archive in top bar

---

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/graph/CytoscapeVisualizer.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/externals/graph/cytoscape/CytoscapeWrapper.kt

* Fixed a problem with re-rendering
* Implemented onClick (onTap) event handler for cytoscape
* Fix visuals
https://github.com/saveourtool/save-cloud/assets/35039155/ed2888e6-51c3-48c9-ad79-518af23fca03

cytoscape onClick event

---

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/demo/GraphDemoComponent.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/graph/AdditionalInfoDisplayer.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/graph/CytoscapeVisualizer.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/graph/SigmaGraphVisualizer.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/demo/CpgView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/externals/reactace/AceBuilder.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/externals/reactace/ReactAce.kt

* Moved displayCpgNodeAdditionalInfo into a separate file
* Added additional info displaying to cytoscape
* Added basis for future PR - creating AceMarker for selected node
* Fix visuals
https://github.com/saveourtool/save-cloud/assets/35039155/7c75ee86-850b-4b3f-95f0-81ba7c4ba8e6

Added additional info displaying to cytoscape

---

db/test-data/sqlRequests/vulnerability.csv
db/test-data/vulnerability-insert.xml
db/v-2/tables/vulnerability.xml
save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/vulnerability/VulnerabilityController.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/repository/vulnerability/VulnerabilityRepository.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/service/vulnerability/VulnerabilityService.kt
save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/entities/vulnerability/VulnerabilityDto.kt
save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/entities/vulnerabilities/Vulnerability.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/inputform/InputForms.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/inputform/InputTextFormOptional.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/fossgraph/CreateVulnerabilityView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/fossgraph/FossGraphView.kt

- added field Identifier in vulnerability
- added field Identifier on vulnerability view
- added check that a vulnerability with this ID does not yet exist

Added vulnerability identifier

---

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/topbar/TopBar.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/topbar/TopBarLinks.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/contests/ContestsStatistics.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/contests/CreateNewContestTemplate.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/contests/MyProjectsRating.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/contests/NewContests.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/contests/WelcomeToSaveContests.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/projectcollection/Cards.kt
save-frontend/src/main/resources/scss/_root.scss
save-frontend/src/main/resources/scss/save-frontend.scss

- very small change to make views more flexible
- it appeared that we can be very flexible on all windows just with a small css change (font size in "vw")
https://github.com/saveourtool/save-cloud/assets/58667063/03634c9a-6149-4780-b8ac-70d31daf5973

Making flexible size of the text

---

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/fossgraph/CreateVulnerabilityView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/fossgraph/FossGraphView.kt

- hide fields is null in VulnerabilityView
- fixed Vuln. Identifier field in CreateVulnerabilityView

Hide fields is null

---

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/codeeditor/CodeEditorComponent.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/demo/GraphDemoComponent.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/graph/CytoscapeVisualizer.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/demo/CpgView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/externals/reactace/AceBuilder.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/utils/Utils.kt
save-frontend/src/test/kotlin/com/saveourtool/save/frontend/utils/ParsePositionStringTest.kt

* Implemented code highlighting on CpgGraph node click
* Added tests on valid string processing (ParsePositionStringTest)
* Fix visuals
https://github.com/saveourtool/save-cloud/assets/35039155/5880c6fe-2b3b-45a9-b468-e24d6ef0cd4f

CpgDemo code highlighting

---

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/FossGraphIntroductionComponent.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/SelectForm.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/CreationView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/contests/CreateNewContestTemplate.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/fossgraph/CreateVulnerabilityView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/fossgraph/FossGraphCollectionView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/projectcollection/Cards.kt

* Fixed alignment on fossGraphCollectionView
* Fixed text alignment in createVulnerabilityView's language selector
* Fixed text in "Create new contest template" button
* Fixed select form on CreationView

Frontend small fixes

---

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/tables/PagingControl.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/tables/TableComponent.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/fossgraph/FossGraphView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/fossgraph/VulnerabilityBadge.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/fossgraph/VulnerabilityInfoTab.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/fossgraph/VulnerabilityProjectWindow.kt

* Moved vulnerability badge to separate `FC` - `vulnerabilityBadge`
* Improved `vulnerabilityBadge`
* Fixed `tableComponent` visuals
* Slightly improved `fossGraph` visuals
* Fix ugly comments
* Add card layout to `fossGraph`
https://github.com/saveourtool/save-cloud/assets/35039155/f524cd30-6ce2-4412-b764-3172c8bdf357

FossGraphView refactoring

---

save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/entities/CommentDto.kt
save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/entities/Comment.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/Card.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/Forum.kt

- added rating in user comment

Added rating in user comment

---

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/Forum.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/fossgraph/FossGraphView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/fossgraph/VulnerabilityCommentTab.kt

- added avatar for new comment block

Added avatar for new comment block

---

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/Card.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/tables/TableComponent.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/fossgraph/FossGraphView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/fossgraph/VulnerabilityBadge.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/fossgraph/VulnerabilityInfoTab.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/fossgraph/VulnerabilityProjectWindow.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/externals/fontawesome/FontAwesomeIconBuilders.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/externals/fontawesome/FontAwesomeIconProps.kt

* Reworked card with brief info
* Moved tables on info tab
* Added clickable placeholder for table
* Fix ugly comments
https://github.com/saveourtool/save-cloud/assets/35039155/3bd27904-ba7d-4f22-8401-c60925be7dc3

FossGraphView improvements

---

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/fossgraph/VulnerabilityInfoTab.kt

- fixed remove project from vulnerability

Fixed remove project from vulnerability

---

.github/workflows/build_and_test_reusable.yml
.github/workflows/deploy_images_reusable.yml
gradle/plugins/src/main/kotlin/com/saveourtool/save/buildutils/save-cli-configuration.gradle.kts

- removed save-cli-*.kexe as a runtime dependency by default
It closes #2250

Fix local building save-cloud

---

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/fossgraph/FossGraphView.kt

- added organization on FossGraphView

Added organization on FossGraphView

---

save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/vulnerability/VulnerabilityController.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/service/vulnerability/VulnerabilityService.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/fossgraph/CreateVulnerabilityView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/fossgraph/FossGraphView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/fossgraph/VulnerabilityInfoTab.kt

* Implemented passing currentUserInfo to vulnerabilityInfoTab using props
* Hid several buttons if user is unauthorized

vulnerabilityInfoTab should rely on currentUserInfo

---

save-backend/src/main/kotlin/com/saveourtool/save/backend/repository/vulnerability/LnkVulnerabilityUserRepository.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/service/vulnerability/VulnerabilityService.kt
save-backend/src/test/kotlin/com/saveourtool/save/backend/controller/AgentsControllerTest.kt
save-backend/src/test/kotlin/com/saveourtool/save/backend/controller/DeleteEntitiesTest.kt
save-backend/src/test/kotlin/com/saveourtool/save/backend/controller/ExecutionControllerTest.kt
save-backend/src/test/kotlin/com/saveourtool/save/backend/controller/ProjectControllerTest.kt
save-backend/src/test/kotlin/com/saveourtool/save/backend/controller/TestExecutionControllerTest.kt
save-backend/src/test/kotlin/com/saveourtool/save/backend/controller/TestInitializeControllerTest.kt
save-backend/src/test/kotlin/com/saveourtool/save/backend/controller/TestSuitesControllerTest.kt
save-backend/src/test/kotlin/com/saveourtool/save/backend/controller/UsersControllerTest.kt
save-backend/src/test/kotlin/com/saveourtool/save/backend/controller/UsersDetailsControllerTest.kt
save-backend/src/test/kotlin/com/saveourtool/save/backend/controllers/RunExecutionControllerTest.kt
save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/entities/vulnerabilities/LnkVulnerabilityUser.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/fossgraph/CreateVulnerabilityView.kt

- added organization field in CreateVulnerabilityView

Added organization field in CreateVulnerabilityView

---

save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/CommentController.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/repository/CommentRepository.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/security/OrganizationPermissionEvaluator.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/security/UserPermissionEvaluator.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/service/CommentService.kt
save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/entities/Comment.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/Forum.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/fossgraph/VulnerabilityCommentTab.kt

* Implemented comment deletion on backend
* Supported comment deletion on frontend

Comment deletion

---

save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/entities/vulnerability/VulnerabilityDateDto.kt
save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/entities/vulnerability/VulnerabilityProjectDto.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/TimelineComponent.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/contests/ContestCreationComponent.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/inputform/InputForms.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/fossgraph/FossGraphView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/fossgraph/VulnerabilityDateModal.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/fossgraph/VulnerabilityInfoTab.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/utils/Utils.kt
save-frontend/src/main/resources/scss/utilities/_timeline.scss

* Removed save button on `vulnerabilityInfoTab`
* Implemented `vulnerabilityDateModal`
* Added add button to `timelineComponent`
* Improved `timelineComponent` styles
* Added placeholder for empty `timelineComponent`
https://github.com/saveourtool/save-cloud/assets/35039155/39bcd0fe-9041-4c16-b7a6-c10a38dd4719

timelineComponent should be functional

---

db/test-data/sqlRequests/vulnerability.csv
db/test-data/vulnerability-insert.xml
db/v-2/tables/vulnerability.xml
save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/vulnerability/VulnerabilityController.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/repository/vulnerability/VulnerabilityRepository.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/service/vulnerability/VulnerabilityService.kt
save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/entities/vulnerability/VulnerabilityDto.kt
save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/entities/vulnerability/VulnerabilityLanguage.kt
save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/entities/vulnerability/VulnerabilityStatus.kt
save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/filters/VulnerabilityFilter.kt
save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/entities/vulnerabilities/Vulnerability.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/Forum.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/projects/CreateProjectProblemView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/projects/EditProjectProblemWindow.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/fossgraph/CreateVulnerabilityView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/fossgraph/FossGraphCollectionView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/fossgraph/FossGraphView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/userprofile/UserProfileVulnerabilitiesTab.kt

- added vulnerability status
- added link to user from comment
- added new language for vulnerability

Added vulnerability status

---

save-backend/src/main/kotlin/com/saveourtool/save/backend/repository/vulnerability/VulnerabilityDateRepository.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/service/vulnerability/VulnerabilityService.kt
save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/entities/vulnerabilities/Vulnerability.kt

Refactoring vulnerability dates

---

save-backend/src/main/kotlin/com/saveourtool/save/backend/service/vulnerability/VulnerabilityService.kt
save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/entities/vulnerability/VulnerabilityDto.kt
save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/entities/vulnerabilities/Vulnerability.kt

Added participants in vulnerability dto

Added participants in vulnerability dto

---

save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/vulnerability/VulnerabilityController.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/Carousel.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/Forum.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/TimelineComponent.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/fossgraph/FossGraphView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/fossgraph/VulnerabilityInfoTab.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/externals/fontawesome/Icons.kt

This PR closes #2287
* Implemented cards for projects on `vulnerabilityInfoTab`
* Added confirmation on comment deletion
* Added confirmation on date deletion

vulnerabilityInfoTab card mode

---

api-gateway/src/main/kotlin/com/saveourtool/save/gateway/utils/ConvertAuthorizationHeaderGatewayFilterFactory.kt
authentication-service/src/main/kotlin/com/saveourtool/save/authservice/security/CustomAuthenticationBasicConverter.kt
save-api/src/main/kotlin/com/saveourtool/save/api/SaveCloudClientEx.kt
save-api/src/main/kotlin/com/saveourtool/save/api/impl/DefaultSaveCloudClient.kt
save-api/src/main/kotlin/com/saveourtool/save/api/utils/RequestUtils.kt
save-backend/src/test/kotlin/com/saveourtool/save/backend/security/ConverterTest.kt
save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/utils/Constants.kt
save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/configs/ApiSwaggerSupport.kt

- Reflected the changes made to the back-end over the last 6 months.

Make `SaveCloudClientEx` compatible with the current state of the back-end

---

save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/CommentController.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/vulnerability/VulnerabilityController.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/repository/vulnerability/LnkVulnerabilityUserRepository.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/security/CommentPermissionEvaluator.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/service/vulnerability/VulnerabilityService.kt

- added controller for participants in vulnerability

Added controller for participants in vulnerability

---

api-gateway/src/main/kotlin/com/saveourtool/save/gateway/security/WebSecurityConfig.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/index/IndexLogoButtons.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/index/IndexView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/index/IndexViewAuth.kt
save-frontend/src/main/resources/particles.json
save-frontend/src/main/resources/scss/_glow.scss

- changed default redirection
- adding perfect animation to Index view
https://github.com/saveourtool/save-cloud/assets/58667063/9c1f502a-fe0c-48aa-80ea-da6001b00d72

Polishing index view animation

---

authentication-service/src/main/kotlin/com/saveourtool/save/authservice/config/WebSecurityConfig.kt

Fixed vulnerabilities user top-rating for not logged-in users

---

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/ManageUserRoleCard.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/organizations/testsuitespermissions/ManageTestSuitePermissionsCard.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/inputform/InputWithDebounce.kt

* `inputWithDebounce` now suggests elements with custom `div`s
https://github.com/saveourtool/save-cloud/assets/35039155/7b7ee65e-2335-4787-8156-cf219aa7caab

inputWithDebounce refactoring

---

save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/UsersDetailsController.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/repository/UserRepository.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/AddUserComponent.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/inputform/InputTextFormOptional.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/inputform/InputWithDebounce.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/fossgraph/CreateVulnerabilityView.kt

* Implemented `addUserComponent` based on `inputWithDebounce`
* Supported option fetch from backend
* Fixed `createVulnerabilityView` paddings
https://github.com/saveourtool/save-cloud/assets/35039155/9162b577-eb38-4d96-96ca-613df85cc732

Add users to vulnerability

---

save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/vulnerability/VulnerabilityController.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/security/VulnerabilityPermissionEvaluator.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/service/vulnerability/VulnerabilityService.kt

Added vulnerability permission

Added vulnerability permission

---

save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/entities/vulnerability/VulnerabilityDto.kt
save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/entities/vulnerabilities/Vulnerability.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/fossgraph/FossGraphView.kt

* Added creation date and last updated date to `VulnerabilityDto
* Added creation date to `fossGraph` view
* Added last updated date to `fossGraph` view

Added creation date and last updated date labels

---

api-gateway/src/main/resources/application-dev.yml
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/App.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/AvatarRenderers.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/Forum.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/UserBoard.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/modal/ModalStyles.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/topbar/TopBarUserField.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/OrganizationView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/RegistrationView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/index/IndexLogoButtons.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/index/IndexViewAuth.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/toprating/UserRatingTab.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/userprofile/UserProfileView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/usersettings/UserSettingsView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/welcome/WelcomeView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/utils/Utils.kt
save-frontend/src/main/resources/scss/_glow.scss
save-frontend/src/test/kotlin/com/saveourtool/save/frontend/components/topbar/TopBarTest.kt

- Fix for registration of new users
- Polishing formating of auth providers
- Dev configuration for Gitee OAUTH (avatars and production auth keys will be updated later in next PRs)
https://github.com/saveourtool/save-cloud/assets/58667063/a899650b-a00e-4ef2-a5fa-498815906932

Authorization with other source providers

---

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/fossgraph/CreateVulnerabilityView.kt

* Fixed for broken validation on vulnerability creation - reused `isValidUrl` - extension function of `String`

Fix for broken validation on vulnerability creation

---

save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/vulnerability/VulnerabilityController.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/repository/vulnerability/VulnerabilityRepository.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/service/vulnerability/VulnerabilityService.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/organizations/OrganizationVulnerabilitiesMenu.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/OrganizationView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/utils/OrganizationMenuBar.kt

Added vulnerabilities tab in organization

---

save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/vulnerability/VulnerabilityController.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/service/vulnerability/VulnerabilityService.kt
save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/entities/vulnerability/VulnerabilityDto.kt
save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/entities/vulnerabilities/Vulnerability.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/tables/TableComponent.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/fossgraph/CreateVulnerabilityView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/fossgraph/FossGraphCollectionView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/fossgraph/FossGraphView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/fossgraph/VulnerabilityInfoTab.kt

* Fixed table bottom margins
* Replaced `userId` with `userInfo` in `VulnerabilityDto`
* Added more info to `Vulnerability` table on `fossGraphCollectionView`
* Fixed frontend permissions
* Fixed placeholders on `fossGraph` view

fossGraphCollectionView table should be more informative

---

save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/vulnerability/VulnerabilityController.kt

Added permission for add vulnerability projects

Added permission for add vulnerability projects

---

save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/vulnerability/VulnerabilityController.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/repository/vulnerability/VulnerabilityRepository.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/service/vulnerability/VulnerabilityService.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/userprofile/UserProfileVulnerabilitiesTab.kt

Added new fields in vulnerability table in user profile view

Added new fields in vulnerability table in user profile view

---

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/App.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/topbar/TopBar.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/utils/LocationUtils.kt

- Removed top bar from Registration and Welcome view

Removed top bar from Registration and Welcome view

---

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/mobile/SaveWelcomeMobileView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/AbstractView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/welcome/MarketingTitles.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/welcome/SaveWelcomeView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/welcome/WelcomeUtils.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/welcome/pagers/WelcomePager.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/utils/JsUtils.kt

* Moved gradients to const strings
* Moved useful welcome menu functions to external `WelcomeUtils.kt` file

Minor refactoring for welcome view

---

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/FossGraphIntroductionComponent.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/table/filters/NameFiltersRow.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/table/filters/TestExecutionFilter.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/table/filters/VulnerabilitiesFiltersRow.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/ExecutionView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/contests/ContestGlobalRatingView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/toprating/OrganizationRatingTab.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/vuln/VulnerabilityCollectionView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/externals/fontawesome/Icons.kt

STEP 1: We will need to add A LOT of filters on this page, but now we should at least refactor and split filters for it
- updating filters
- polishing vuln. collection view

Changing filters for vulnerability view

---

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/contests/GlobalRating.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/toprating/OrganizationRatingTab.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/welcome/WelcomeUtils.kt

* Removed hash symbol from `Link`'s `to` prop

Hotfix for broken links

---

save-frontend/src/test/kotlin/com/saveourtool/save/frontend/components/FooterTest.kt

Tests were broken in #2348 
* Fixed `FooterTest`

Hotfix for broken frontend tests

---

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/RegistrationView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/utils/CustomHooks.kt

* Added page reload on successful registration
* Started to process emails

Hotfix for lack of page reload on registrationView

---

authentication-service/src/main/kotlin/com/saveourtool/save/authservice/repository/AuthenticationUserRepository.kt
authentication-service/src/main/kotlin/com/saveourtool/save/authservice/security/ConvertingAuthenticationManager.kt
authentication-service/src/main/kotlin/com/saveourtool/save/authservice/service/AuthenticationUserDetailsService.kt
save-backend/src/test/kotlin/com/saveourtool/save/backend/security/BasicSecurityTest.kt
save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/utils/Constants.kt

Fixed user renamed
Closes #2337

Fixed user renamed

---

api-gateway/src/main/kotlin/com/saveourtool/save/gateway/utils/StoringServerAuthenticationSuccessHandler.kt
authentication-service/src/main/kotlin/com/saveourtool/save/authservice/utils/SecurityUtils.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/LnkUserOrganizationController.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/PermissionController.kt

- a small refactoring
It's part of #2336

Replace `Authentication.toUser().name` by `Authentication.username()`

---

db/v-2/tables/vulnerability.xml
save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/vulnerability/VulnerabilityController.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/service/vulnerability/VulnerabilityService.kt
save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/entities/vulnerability/VulnerabilityDto.kt
save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/filters/VulnerabilityFilter.kt
save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/entities/vulnerabilities/Vulnerability.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/vuln/VulnerabilityGeneralInfo.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/vuln/VulnerabilityTagsComponent.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/vuln/VulnerabilityView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/utils/ChildrenBuilderUtils.kt

* Added tags column in vulnerability table
* Added field to `Vulnerability` entity
* Added field to `VulnerabilityDto`
* Supported tags displaying
* Supported adding tags to existed vulnerabilities
* Fixed buttons with icons to be vertically aligned
https://github.com/saveourtool/save-cloud/assets/35039155/3ccf5525-e366-40e0-8689-a0d0c1308945

Vulnerability tags

---

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/organizations/OrganizationContestsMenu.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/organizations/OrganizationVulnerabilitiesTab.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/vuln/VulnerabilityInfoTab.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/utils/ChildrenBuilderUtils.kt

* Added table placeholders
* Fixed table sizes

Table placeholders on OrganizationView

---

api-gateway/src/main/resources/application.yml
save-frontend/src/main/resources/index.html

* Fixed `gateway` routing
* Removed useless tags from `index.html`

Gateway should redirect all unmatched to save-frontend

---

api-gateway/src/main/kotlin/com/saveourtool/save/gateway/security/WebSecurityConfig.kt

* Fixed `api-gateway` authorization check for frontend routes

Gateway should permit save-frontend redirects

---

save-frontend/nginx.conf

Frontend nginx should almost always return index.html

---

save-frontend/nginx.conf

Frontend nginx should return index.html when resource is not found

---

save-frontend/nginx.conf

Hotfix for "/workspace/staticindex.html" failed

---

authentication-service/src/main/kotlin/com/saveourtool/save/authservice/config/WebSecurityConfig.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/ProjectController.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/service/ProjectService.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/http/Requests.kt

* Added `/projects/get/organization-name` to public endpoints list
* Removed `@RequiresAuthorizationSourceHeader` annotation from `ProjectController::getProjectByNameAndOrganizationName`

Should return 404 instead of 401 when Project does not exist

---

api-gateway/README.md
save-frontend/README.md

* Added documentation for cluster routing to `README.md` of `api-gateway`
* Added frontend documentation to `README.md` of `save-frontend`

Documenting cluster routing

---

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/usersettings/right/Organizations.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/usersettings/right/Profile.kt

Hotfix for organization management view

---

save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/utils/Constants.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/AvatarForm.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/usersettings/SettingsView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/usersettings/SettingsViewLeftColumn.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/usersettings/SettingsViewRightColumn.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/usersettings/right/Profile.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/externals/fontawesome/Icons.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/utils/RequestUtils.kt

- UseRequest appears to be not working with avatars cropper, so need to create a quick hotfix for it
- Polishing of settings views

Hotfix for avatars uploading in settings view

---

authentication-service/src/main/kotlin/com/saveourtool/save/authservice/config/WebSecurityConfig.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/TagController.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/repository/vulnerability/LnkVulnerabilityTagRepository.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/service/TagService.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/service/vulnerability/VulnerabilityService.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/table/filters/VulnerabilitiesFiltersRow.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/inputform/InputWithDebounce.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/vuln/VulnerabilityCollectionView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/utils/Utils.kt

* Implemented tags as a part of filter search on `backend`
* Supported tags search on `frontend`
* Added placeholder for `inputWithDebounce` empty option list
https://github.com/saveourtool/save-cloud/assets/35039155/856986db-64f1-485c-99c3-b26749b40ebe

Vulnerability filter search

---

save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/validation/FrontendRoutes.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/topbar/TopBar.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/topbar/TopBarLinks.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/utils/LocationUtils.kt

* Removed topbar links from `/terms-of-use` view
* Added new topbar links - `generalTopbarLinks`

Minor topbar changes

---

save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/OrganizationController.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/UsersDetailsController.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/service/UserDetailsService.kt
save-backend/src/test/kotlin/com/saveourtool/save/backend/controller/UsersDetailsControllerTest.kt
save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/domain/UserSaveStatus.kt
save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/validation/FrontendRoutes.kt
save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/validation/ValidationErrorMessages.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/AvatarRenderers.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/contests/ContestCreationComponent.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/inputform/InputForms.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/topbar/TopBarLinks.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/CreateOrganizationView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/CreationView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/RegistrationView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/toprating/UserRatingTab.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/usersettings/SettingsView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/usersettings/right/Email.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/usersettings/right/Organizations.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/usersettings/right/SettingsInputFields.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/usersettings/right/Token.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/utils/LocationUtils.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/utils/RequestUtils.kt

- Validation of new User, Organization and Project is now working correctly
- Settings view updated: organizations and email

Fixes for names (orgs, users, projects) validation and polishing of Setting Views

---

save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/OrganizationController.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/repository/OrganizationRepository.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/service/OrganizationService.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/service/vulnerability/VulnerabilityService.kt
save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/filters/VulnerabilityFilter.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/organizations/testsuitespermissions/ManageTestSuitePermissionsCard.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/table/filters/VulnerabilitiesFiltersRow.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/inputform/InputWithDebounce.kt

Part of #2430 
* Added author name filter
* Added organization name filter
* Added `isDisabled` flag to `InputWithDebounceProps`
* Display vulnerability filters in table
https://github.com/saveourtool/save-cloud/assets/35039155/9a5c74de-8a7b-419a-adea-b8fdeeedc62f

Vulnerability filters part III

---

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/FossGraphIntroductionComponent.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/table/filters/NameFiltersRow.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/toprating/OrganizationRatingTab.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/toprating/RatingUtils.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/toprating/UserRatingTab.kt

This PR closes #2426
* Added filtering for `userRatingTable`
* Fixed top numeration in `organizationRatingTab`
* Slightly improved `nameFiltersRow` styles
https://github.com/saveourtool/save-cloud/assets/35039155/f8f9b137-e566-4b01-920d-0aa0ddc51ad2

Top Rating filtering

---

save-backend/src/main/kotlin/com/saveourtool/save/backend/repository/vulnerability/LnkVulnerabilityTagRepository.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/service/vulnerability/VulnerabilityService.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/vuln/VulnerabilityCollectionView.kt

This PR closes #2430
* Started to display tags on `vulnerabilityCollectionView`

Vulnerability filters part IV

---

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/welcome/VulnerabilityWelcomeView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/welcome/pagers/vuln/WhatIsVuln.kt

* Added `Useful links` card to `VulnerabilityWelcomeView.kt`

Add useful links to VulnerabilityWelcomeView.kt

---

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/AvatarRenderers.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/modal/ModalStyles.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/vuln/VulnerabilityCommentTab.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/vuln/VulnerabilityGeneralInfo.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/vuln/VulnerabilityInfoTab.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/vuln/VulnerabilityTagsComponent.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/vuln/VulnerabilityView.kt

- Fixed info fonts
- Fixed alignments, removed steps
- Moved buttons to a common block

[FixMe: hotfix, need to rework] Polishing alignments for Vulnerabiliy view

---

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/toprating/OrganizationRatingTab.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/welcome/VulnerabilityWelcomeView.kt

* Added `pageSize` param to organization fetch request

Hotfix for organizationRatingTab

---

save-backend/src/main/kotlin/com/saveourtool/save/backend/service/vulnerability/VulnerabilityService.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/vuln/VulnerabilityCollectionView.kt

* Added tags fetch on vuln fetch for unauthorized

Hotfix for vulnerability tags for unauthorized

---

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/vuln/CreateVulnerabilityView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/vuln/VulnerabilityGeneralInfo.kt

* Renamed `users` to `collaborators`

`users` -> `collaborators`

---

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/ManageUserRoleCard.kt

* Refactored columns so that the column without delete button does not disappear

Fix for missing column in manageUserRoleCardComponent

---

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/vuln/VulnerabilityCommentTab.kt

* Added margin for `newCommentWindow`

Fix for newCommentWindow margin

---

save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/validation/ValidationErrorMessages.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/vuln/CreateVulnerabilityView.kt

* Fixed a problem with `float` criticality - 0.5 used to be ok as criticality
* Fixed url validation message

Vulnerability creation validation improvements

---

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/tables/TableComponent.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/ExecutionView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/contests/ContestGlobalRatingView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/toprating/OrganizationRatingTab.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/toprating/UserRatingTab.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/vuln/VulnerabilityCollectionView.kt

This PR closes #2437
* Moved `commonHeader` of `tableComponent` to props
* Wrapped `vulnerabilityCollectionView` table into `useMemo`

VulnCollectionView table should show user and org names

---

save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/entities/vulnerability/VulnerabilityDto.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/TimelineComponent.kt

* Replaces dates map keys and values (`Map<LocalDateTime, String>` -> `Map<String, LocalDateTime>`)

Vulnerability missing timestamp fix

---

README.md
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/TimelineComponent.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/vuln/VulnerabilityBadge.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/vuln/VulnerabilityGeneralInfo.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/vuln/VulnerabilityInfoTab.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/vuln/VulnerabilityView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/externals/progressbar/ReactCircle.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/externals/progressbar/ReactCircleBuilder.kt
save-frontend/src/main/resources/scss/_cards.scss
save-frontend/src/main/resources/scss/utilities/_timeline.scss

And + two animations: 
- on timeline
- on addition of libs

Polishing rendering of vulnerability view part #1

---

save-frontend/build.gradle.kts
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/App.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/index/IndexViewUserInfo.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/externals/i18next/InitI18n.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/externals/i18next/Translation.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/externals/i18next/UseTranslation.kt
save-frontend/src/test/kotlin/com/saveourtool/save/frontend/BasicRoutingTest.kt
yarn.lock

* Added `i18n`
* Added `react-i18n`
* Added kotlin wrapper for `useTranslation` hook

First steps into localization

---

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/vuln/VulnerabilityCollectionView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/vuln/VulnerabilityGeneralInfo.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/vuln/VulnerabilityTagsComponent.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/vuln/VulnerabilityView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/routing/BasicRouting.kt

- edit button only for owners and admins
- layout

Edit button on vulnerabilities view

---

save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/validation/FrontendRoutes.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/topbar/TopBarUrlSplits.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/vuln/VulnerabilityCollectionView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/vuln/VulnerabilityGeneralInfo.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/vuln/VulnerabilityTagsComponent.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/routing/BasicRouting.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/utils/FilterParamUtils.kt

- if user has no permissions to edit tags, he will be redirected to FILTERED page with vulnerabilities by proper URL: `vuln/list?tags=hu`

Tags should not be clickable without permissions

---

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/topbar/TopBarLinks.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/externals/i18next/InitI18n.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/externals/i18next/locales/Translations.kt

* Removed `width` from `TopBarLink` - now it is useless
* Fixed width of top bar links
* Added russian translation

Topbar localization

---

authentication-service/src/main/kotlin/com/saveourtool/save/authservice/config/WebSecurityConfig.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/vulnerability/VulnerabilityController.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/table/filters/VulnerabilitiesFiltersRow.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/vuln/VulnerabilityCollectionView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/welcome/VulnerabilityWelcomeView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/utils/LoginUtils.kt

- small fixes to fix The 405 Method Not Allowed error

Hotfix for vulnerabilities card with the number of vulnerabilities

---

db/v-2/tables/cosv-metadata.xml
db/v-2/tables/db.changelog-tables.xml
save-backend/src/main/kotlin/com/saveourtool/save/backend/service/OrganizationService.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/service/UserDetailsService.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/service/vulnerability/VulnerabilityService.kt
save-backend/src/test/kotlin/com/saveourtool/save/backend/DatabaseTest.kt
save-backend/src/test/kotlin/com/saveourtool/save/backend/DownloadFilesTest.kt
save-backend/src/test/kotlin/com/saveourtool/save/backend/controller/JpaSpecificationTest.kt
save-backend/src/test/kotlin/com/saveourtool/save/backend/controller/LnkUserOrganizationControllerTest.kt
save-backend/src/test/kotlin/com/saveourtool/save/backend/controller/OrganizationControllerTest.kt
save-backend/src/test/kotlin/com/saveourtool/save/backend/controller/PermissionControllerTest.kt
save-cloud-common/build.gradle.kts
save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/entities/cosv/CosvMetadataDto.kt
save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/entities/cosv/CosvMetadata.kt
save-cosv/build.gradle.kts
save-cosv/src/main/kotlin/com/saveourtool/save/backend/service/IOrganizationService.kt
save-cosv/src/main/kotlin/com/saveourtool/save/backend/service/IUserService.kt
save-cosv/src/main/kotlin/com/saveourtool/save/backend/service/IVulnerabilityService.kt
save-cosv/src/main/kotlin/com/saveourtool/save/cosv/CosvConfiguration.kt
save-cosv/src/main/kotlin/com/saveourtool/save/cosv/controllers/CosvController.kt
save-cosv/src/main/kotlin/com/saveourtool/save/cosv/processor/AbstractCosvProcessor.kt
save-cosv/src/main/kotlin/com/saveourtool/save/cosv/processor/CosvProcessor.kt
save-cosv/src/main/kotlin/com/saveourtool/save/cosv/processor/CosvProcessorHolder.kt
save-cosv/src/main/kotlin/com/saveourtool/save/cosv/processor/go/GoCosvProcessor.kt
save-cosv/src/main/kotlin/com/saveourtool/save/cosv/repository/CosvMetadataRepository.kt
save-cosv/src/main/kotlin/com/saveourtool/save/cosv/repository/CosvRepository.kt
save-cosv/src/main/kotlin/com/saveourtool/save/cosv/repository/CosvRepositoryInStorage.kt
save-cosv/src/main/kotlin/com/saveourtool/save/cosv/service/CosvService.kt
save-cosv/src/main/kotlin/com/saveourtool/save/cosv/storage/CosvStorage.kt

- added new table cosv_metadata
- re-used cosv_metadata on saving cosv
It closes #2508

Introduced CosvMetadata

---

save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/OrganizationController.kt
save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/entities/Organization.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/organizations/OrganizationSettingsMenu.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/OrganizationView.kt

Added bulk upload files

---

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/organizations/OrganizationVulnerabilitiesTab.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/userprofile/UserProfileVulnerabilitiesTab.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/vuln/VulnerabilityCollectionView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/vuln/VulnerabilityHeader.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/vuln/VulnerabilityView.kt

- Just simple refactoring: moved a block of of code to a separate method
- Also fixed links to /vuln/collection on some pages

Refactoring vulnerability view to split header in the separate file

---

save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/vulnerability/VulnerabilityController.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/vuln/CreateVulnerabilityView.kt

This PR is a part of #2514
* Added `Generate identifier` checkbox
* Added backend check: identifier should either be auto-generated or have `CVE-` prefix

Generate identifier checkbox

---

authentication-service/src/main/kotlin/com/saveourtool/save/authservice/config/WebSecurityConfig.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/vulnerability/VulnerabilityController.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/service/vulnerability/VulnerabilityService.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/vuln/VulnerabilityCollectionView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/vuln/VulnerabilityHeader.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/welcome/VulnerabilityWelcomeView.kt

- renamed Filters to Filter
- removed using VulnerabilityDto in /approve and /reject
- removed saveAll
It closes #2521

Cleanup Vulnerability endpoints

---

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/vuln/CreateVulnerabilityView.kt

* Fixed invalid request params on frontend

Invalid request params

---

db/v-2/tables/cosv-metadata.xml
save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/vulnerability/VulnerabilityController.kt
save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/utils/CosvSchemaUtils.kt
save-cosv/src/main/kotlin/com/saveourtool/save/cosv/repository/CosvRepository.kt
save-cosv/src/main/kotlin/com/saveourtool/save/cosv/repository/CosvRepositoryInStorage.kt
save-cosv/src/main/kotlin/com/saveourtool/save/cosv/service/CosvService.kt

- supported generating COSV for VulnerabilityDto
- fixed liquibase script
It closes #2543

Generating COSV for manually created vulnerabilities

---

save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/UserPermissionController.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/repository/LnkUserOrganizationRepository.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/security/UserPermissionEvaluator.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/service/LnkUserOrganizationService.kt
save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/info/UserPermissions.kt
save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/info/UserPermissionsInOrganization.kt

Added user permissions

---

buildSrc/src/main/kotlin/com/saveourtool/save/buildutils/DockerStackConfiguration.kt

- added a new service to copy files to minio on start
It closes #2554

Added copying files to minio for local run

---

api-gateway/src/main/kotlin/com/saveourtool/save/gateway/security/WebSecurityConfig.kt
authentication-service/src/main/kotlin/com/saveourtool/save/authservice/utils/SaveUserDetails.kt
authentication-service/src/main/kotlin/com/saveourtool/save/authservice/utils/SecurityUtils.kt
authentication-service/src/test/kotlin/com/saveourtool/save/authservice/utils/SaveUserDetailsTest.kt
save-backend/src/test/kotlin/com/saveourtool/save/backend/security/OrganizationPermissionEvaluatorTest.kt
save-backend/src/test/kotlin/com/saveourtool/save/backend/security/ProjectPermissionEvaluatorTest.kt
save-backend/src/test/kotlin/com/saveourtool/save/backend/utils/SecurityTestingUtils.kt
save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/utils/Constants.kt
save-frontend/README.md
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/usersettings/right/Token.kt
save-frontend/webpack.config.d/dev-server.js

* Added `status` field to `SaveUserDetails`
* Forbade most endpoints to be used by inactive users

Added UserStatus check to gateway

---

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/inputform/InputForms.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/RegistrationView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/routing/BasicRouting.kt

registrationView follow-ups

---

db/v-2/tables/cosv-metadata.xml
save-backend/src/main/kotlin/com/saveourtool/save/backend/service/vulnerability/VulnerabilityService.kt
save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/entities/cosv/CosvMetadataDto.kt
save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/entities/vulnerability/VulnerabilityDto.kt
save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/validation/ValidationErrorMessages.kt
save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/entities/cosv/CosvMetadata.kt
save-cosv/src/main/kotlin/com/saveourtool/save/cosv/repository/CosvRepositoryInStorage.kt
save-cosv/src/main/kotlin/com/saveourtool/save/cosv/service/CosvService.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/inputform/InputForms.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/vuln/CreateVulnerabilityView.kt

Severity score vector is a group of indicators that show the importance of vulnerability. They are necessary to calculate the criticality rating.

Added severity score vector

---

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/index/IndexViewUserInfo.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/vuln/CreateVulnerabilityView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/externals/i18next/InitI18n.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/externals/i18next/locales/Translations.kt

This PR closes #2514 
* Added identifier validation on frontend
* Added missing russian localizations

Validate vuln identifier on frontend

---

api-gateway/src/main/kotlin/com/saveourtool/save/gateway/controller/SecurityInfoController.kt
api-gateway/src/main/kotlin/com/saveourtool/save/gateway/security/WebSecurityConfig.kt
api-gateway/src/main/kotlin/com/saveourtool/save/gateway/service/BackendService.kt

* Moved logic connected with authorization cast to `BackendService`
* Replaced `BackendService#findByName` with `BackendService#findByAuthentication`

Hotfix for 403 when user changed name

---

api-gateway/src/main/kotlin/com/saveourtool/save/gateway/controller/SecurityInfoController.kt
api-gateway/src/main/kotlin/com/saveourtool/save/gateway/security/WebSecurityConfig.kt
api-gateway/src/main/kotlin/com/saveourtool/save/gateway/service/BackendService.kt
api-gateway/src/main/kotlin/com/saveourtool/save/gateway/utils/AuthorizationHeadersGatewayFilterFactory.kt
api-gateway/src/main/kotlin/com/saveourtool/save/gateway/utils/StoringServerAuthenticationSuccessHandler.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/internal/UsersController.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/service/UserDetailsService.kt
save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/utils/Constants.kt

- added an attibute for `SaveUserDetails`
- refactored method createNewIfRequired -- now it returns `User`
- `SaveUserDetails` is stored in `WebSession` for OAuth2
It's follow up after #2575

Deduplicate logic with SaveUserDetails in api-gateway

---

.run/save-cloud [startMinio].run.xml
.run/save-cloud [startMysqlDb].run.xml
db/v-2/events/event_scheduler.xml
save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/entities/cosv/RawCosvFileDto.kt
save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/entities/cosv/RawCosvFile.kt
save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/storage/BackupStorageUtils.kt
save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/storage/ReactiveStorageWithDatabase.kt
save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/storage/SuspendingStorageWithDatabase.kt
save-cosv/src/main/kotlin/com/saveourtool/save/cosv/storage/CosvKey.kt
save-cosv/src/main/kotlin/com/saveourtool/save/cosv/storage/CosvStorage.kt
save-cosv/src/main/kotlin/com/saveourtool/save/cosv/storage/RawCosvFileStorage.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/fileuploader/CosvFileManagerComponent.kt

- added an event to delete processed RawCosvFile after 7 days
- refactored deleting and backing up unexpected keys in storage
It closes #2586

Delete processed files

---

save-deploy/base-images/Dockerfile

A try to fix Dockerfile

---

.github/workflows/build-base-images.yaml
save-agent/src/commonMain/kotlin/com/saveourtool/save/agent/SaveAgent.kt
save-deploy/base-images/Dockerfile

Another try to fix Dockerfile

---

save-deploy/base-images/Dockerfile

- changed condition in if for python

Fixed Dockerfile for python

---

save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/testsuite/TestSuitesSourceDto.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/projects/ProjectRunMenu.kt

- added distinct
- added gitDto validation
It closes #2628

Fixed issue with multiple select of test suites

---

authentication-service/src/main/kotlin/com/saveourtool/save/authservice/config/WebSecurityConfig.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/vulnerability/VulnerabilityController.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/security/VulnerabilityPermissionEvaluator.kt

- added `/vulnerabilities/download` to public endpoints
- changed `VulnerabilityPermissionEvaluator` -- read is available for non-authorized users
It closes #2644

Allow to download vulnerability for all users

---

api-gateway/src/main/resources/application-dev.yml
api-gateway/src/main/resources/application.yml
db/v-2/tables/original-login.xml
db/v-2/tables/user.xml

- added JWT uri
- updated UserInfo uri
- set user-info-authentication-method
- set scope as profile, since openId doesn't work
It closes #2101

Supported OAuth2 via Huawei

---

save-backend/src/main/kotlin/com/saveourtool/save/backend/configs/ConfigProperties.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/service/BackendForCosvService.kt
save-backend/src/main/resources/application-dev.properties
save-backend/src/main/resources/application-mac.properties
save-backend/src/main/resources/application.properties
save-backend/src/test/resources/application.properties
save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/utils/ArchiveUtils.kt
save-cosv/src/main/kotlin/com/saveourtool/save/backend/service/IBackendService.kt
save-cosv/src/main/kotlin/com/saveourtool/save/cosv/controllers/CosvController.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/fileuploader/CosvFileManagerComponent.kt

- supported processing ZIP files via local files
- added a button for reloading files
It closes #2661

Supported archive uploading for COSV files

---

save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/entities/cosv/CosvFileDto.kt
save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/utils/DateTimeUtils.kt
save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/entities/cosv/CosvFile.kt
save-cosv/src/main/kotlin/com/saveourtool/save/cosv/controllers/CosvController.kt
save-cosv/src/main/kotlin/com/saveourtool/save/cosv/repository/CosvRepository.kt
save-cosv/src/main/kotlin/com/saveourtool/save/cosv/repository/CosvRepositoryInStorage.kt
save-cosv/src/main/kotlin/com/saveourtool/save/cosv/service/CosvService.kt
save-cosv/src/main/kotlin/com/saveourtool/save/cosv/service/VulnerabilityMetadataService.kt
save-cosv/src/main/kotlin/com/saveourtool/save/cosv/storage/CosvFileStorage.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/vuln/VulnerabilityChangesTab.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/vuln/VulnerabilityGeneralInfoProps.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/vuln/VulnerabilityHistoryTab.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/vuln/VulnerabilityView.kt
save-frontend/src/main/resources/locales/en/table-headers.json
save-frontend/src/main/resources/locales/ru/table-headers.json

- added history tab
- added changes tab

Added diff on vulnerability view

---

save-cosv/src/main/kotlin/com/saveourtool/save/cosv/controllers/CosvController.kt

- removed `.parallel()`
It's part of #2676

Remove parallel upload

---

save-cloud-charts/save-cloud/templates/backend-deployment.yaml

- increased resources.limits.memory to 2G
- increased resources.requests.memory to 1G
It closes #2693

Increased memory for backend

---

save-cosv/src/main/kotlin/com/saveourtool/save/cosv/service/VulnerabilityMetadataService.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/vuln/VulnerabilityInfoTab.kt

Fixed criticality score

---

save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/storage/DefaultStorageProjectReactor.kt
save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/storage/key/AbstractS3KeyDtoManager.kt
save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/storage/key/AbstractS3KeyEntityManager.kt
save-cosv/src/main/kotlin/com/saveourtool/save/cosv/controllers/CosvController.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/fileuploader/CosvFileManagerComponent.kt

- added a new endpoint to delete all processed files
- added a button on UI
It closes #2696

Added a button to delete all processed files

---

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/vuln/CosvSchemaView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/vuln/utils/CosvFieldsToDescriptions.kt

* Fill with another color keys from cosv

Fill with another color keys from cosv

---

save-cosv/src/main/kotlin/com/saveourtool/save/cosv/controllers/CosvController.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/fileuploader/CosvFileManagerComponent.kt

- added a new endpoint
- added a new button
- removed the button "Select all"
- removed fetching files after submitting -- user should do it manually
It closes #2702

Added "Submit all uploaded by you"

---

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/vuln/VulnerabilityInfoTab.kt

Added fix commit table

---

save-backend/src/main/kotlin/com/saveourtool/save/backend/service/vulnerability/VulnerabilityService.kt
save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/filters/VulnerabilityFilter.kt
save-frontend/build.gradle.kts
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/table/filters/VulnerabilitiesFiltersRow.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/externals/slider/MultiRangeSlider.kt
yarn.lock

- added MultiRangeSlider for criticality filtering for vulnerabilities.
- rearranged filters for vulnerabilities in `VulnerabilitiesFiltersRow`.
Closes #2495

Added criticality filtering for vulnerabilities.

---

save-cosv/src/main/kotlin/com/saveourtool/save/cosv/controllers/CosvController.kt
save-cosv/src/main/kotlin/com/saveourtool/save/cosv/repository/RawCosvFileRepository.kt
save-cosv/src/main/kotlin/com/saveourtool/save/cosv/storage/RawCosvFileS3KeyManager.kt
save-cosv/src/main/kotlin/com/saveourtool/save/cosv/storage/RawCosvFileStorage.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/fileuploader/CosvFileManagerComponent.kt

- added userName to all methods with rawCosvFile
- updated title name in button
- disabled buttons when there are no files with required status
It closes #2711

User can operate only with files uploaded by itself

---

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/userprofile/UserProfileView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/userprofile/UserProfileVulnerabilitiesTab.kt

Added pagination on user profile view

Added pagination on user profile view

---

authentication-service/src/main/kotlin/com/saveourtool/save/authservice/config/WebSecurityConfig.kt

* Allow access to the History and Changes tabs on vuln view

Allow access to the History and Changes tabs on vuln view

---

save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/validation/FrontendRoutes.kt
save-frontend/build.gradle.kts
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/AvatarRenderers.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/Forum.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/UserBoard.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/topbar/TopBarUserField.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/index/CardUser.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/userprofile/UserProfileView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/usersettings/SettingsViewLeftColumn.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/vuln/VulnerabilityChangesTab.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/vuln/VulnerabilityHeader.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/vuln/VulnerabilityRawDataTab.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/vuln/VulnerabilityView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/externals/jsonview/JsonView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/routing/BasicRouting.kt
yarn.lock

Adding RAW data to the VulnerabilityView

---

save-cosv/src/main/kotlin/com/saveourtool/save/cosv/controllers/RawCosvFileController.kt
save-cosv/src/main/kotlin/com/saveourtool/save/cosv/storage/RawCosvFileS3KeyManager.kt
save-cosv/src/main/kotlin/com/saveourtool/save/cosv/storage/RawCosvFileStorage.kt

- moved checking of error to controller
- fixed setting contentLength

Fixed issue with contentLength

---

save-backend/src/main/kotlin/com/saveourtool/save/backend/service/vulnerability/VulnerabilityService.kt
save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/utils/StringUtils.kt
save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/validation/ValidationUtils.kt
save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/entities/cosv/VulnerabilityMetadataProject.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/inputform/InputForms.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/vuln/CreateVulnerabilityView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/vuln/VulnerabilityInfoTab.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/vuln/VulnerabilityProjectWindow.kt
save-frontend/src/main/resources/locales/cn/proposing.json
save-frontend/src/main/resources/locales/en/proposing.json
save-frontend/src/main/resources/locales/ru/proposing.json

Added vulnerability projects in cosv

---

save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/validation/ValidationRegularExpressions.kt
save-cloud-common/src/jvmTest/kotlin/com/saveourtool/save/validation/ValidationRegularExpressionsTest.kt

Allow dashes (`-`) in host names

---

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/usersettings/right/validation/InputValidationUtils.kt

Fixed location validation

---

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/tables/PagingControl.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/tables/TableComponent.kt

Fixed page size

---

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/fileuploader/CosvFileManagerComponent.kt

- swapped fields for uploading files and submit buttons.
- changed disabling logic for `Submit` button.
- added status bar to display current status of working with files.
- added new visually distinguishable display for duplicate files.
Closes #2774

Added status bar during uploading COSV files

---

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/vuln/VulnerabilityGeneralInfoProps.kt
save-frontend/src/main/resources/locales/en/vulnerability.json
save-frontend/src/main/resources/locales/ru/vulnerability.json

* Add aliases field to the left column
Part of https://github.com/saveourtool/save-cloud/issues/2790

Add aliases field to the left column

---

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/HasErrorModal.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/topbar/TopBar.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/topbar/TopBarUserField.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/BanView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/RegistrationView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/ThanksForRegistrationView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/index/CardAboutUs.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/index/CardServiceInfo.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/index/CardUser.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/index/IndexView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/index/IndexViewAuth.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/index/IndexViewUserInfo.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/usersettings/SettingsView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/usersettings/right/profile/AvatarSelector.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/welcome/SaveWelcomeView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/welcome/VulnerabilityWelcomeView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/routing/BasicRouting.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/utils/UserInfoAwareProps.kt

- added a common props for user info
- reused it in all props
It's part of #2221

Common props for user info

---

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/vuln/VulnerabilityChangesTab.kt

* Default Changes for COSV files should be between different versions
Close #2777

Default Changes for COSV files should be between different versions

---

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/vuln/VulnerabilityGeneralInfoProps.kt

Add ability to change confirm type for admins

---

save-backend/src/main/kotlin/com/saveourtool/save/backend/storage/TestsSourceSnapshotStorage.kt
save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/entities/cosv/RawCosvFileDto.kt
save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/entities/cosv/RawCosvFileStatisticsDto.kt
save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/utils/ArchiveUtils.kt
save-cosv/src/main/kotlin/com/saveourtool/save/cosv/controllers/RawCosvFileController.kt
save-cosv/src/main/kotlin/com/saveourtool/save/cosv/repository/RawCosvFileRepository.kt
save-cosv/src/main/kotlin/com/saveourtool/save/cosv/storage/RawCosvFileS3KeyManager.kt
save-cosv/src/main/kotlin/com/saveourtool/save/cosv/storage/RawCosvFileStorage.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/fileuploader/CosvFileManagerComponent.kt
save-preprocessor/src/main/kotlin/com/saveourtool/save/preprocessor/service/GitPreprocessorService.kt
save-sandbox/src/main/kotlin/com/saveourtool/save/sandbox/controller/SandboxInternalController.kt

- added `GET` request to get statistics for raw cosv files.
- fixed statistics display.
Closes #2798

Fixed statistics display during uploading COSV files

---

save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/UsersDetailsController.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/repository/UserRepository.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/userprofile/UserProfileView.kt

Added display of the number of new users

---

save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/NotificationController.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/repository/NotificationRepository.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/service/NotificationService.kt
save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/entities/NotificationDto.kt
save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/entities/Notification.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/index/IndexViewUserInfo.kt

- added notification display
- added deleting notification

Added notification display

---

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/table/filters/VulnerabilitiesFiltersRow.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/vuln/VulnerabilityCollectionView.kt

* Owner tab: COSV Submitter is always the current user, omit it

Owner tab: COSV Submitter is always the current user, omit it

---

save-frontend/build.gradle.kts

[Tactic] Frontend misses index.html

---

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/ErrorBoundary.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/vuln/component/UploadCosvButton.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/externals/i18next/InitI18n.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/utils/RouterUtils.kt

- added error message to ErrorBoundary
- added missing namespace for translation
It closes #2832

Fixed error on vulnerability page

---

save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/vulnerability/event/VulnerabilityMetadataListener.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/event/VulnerabilityMetadataListener.kt
save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/entities/cosv/evententities/VulnerabilityMetadataEvent.kt
save-cosv/src/main/kotlin/com/saveourtool/save/cosv/service/VulnerabilityMetadataService.kt

Added notification for propose new vulnerability

Added notification for propose new vulnerability

---

save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/vulnerability/event/VulnerabilityMetadataListener.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/security/VulnerabilityPermissionEvaluator.kt
save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/entities/vulnerability/VulnerabilityStatus.kt
save-cosv/src/main/kotlin/com/saveourtool/save/cosv/service/VulnerabilityMetadataService.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/vuln/VulnerabilityCollectionView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/vuln/VulnerabilityHeader.kt

- Added CREATED status for new vulnerability

Added CREATED status for new vulnerability

---

save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/vulnerability/event/VulnerabilityMetadataListener.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/event/UserListener.kt
save-backend/src/main/kotlin/com/saveourtool/save/backend/service/UserDetailsService.kt
save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/evententities/UserEvent.kt

- added notification for ban user
- added notification for auto approve and updated vulnerability
- added UserEvent class

Added new Notifications

---

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/index/IndexViewUserInfo.kt

Fixed not logged in

---

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/externals/i18next/InitI18n.kt

* Fix ERROR after clicking on the buttons to go to Customize profile, Settings, Manage organizations

Fix error after clicking on the buttons to go to Customize profile, Settings, Manage organizations

---

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/vuln/VulnerabilityInfoTab.kt

Fix vuln carousel

---

save-backend/src/test/resources/minio/cosv/5
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/vuln/VulnerabilityGeneralInfoProps.kt

* Distinct user in Contributors and Credits on vulnerability page

Distinct user in Contributors and Credits on vulnerability page

---

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/Footer.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/vuln/VulnerabilityTableComponent.kt

* Fix Vulnerability table width
Before 
After

Fix Vulnerability table width

---

.github/workflows/deploy_images.yml

Fix `deploy_images.yml`

---

.github/workflows/build_save-agent_reusable.yml

- fixed module name for `save-demo-agent`

Fix `build_save-agent_reusable.yml`

---

.gitignore

Fix version of docker images

---

save-frontend-common/build.gradle.kts
save-frontend-common/karma.config.d/custom-config.js

Fixed `save-frontend-common`

---

gradle/libs.versions.toml

Set release version of save-cli

---

cosv-backend/src/main/kotlin/com/saveourtool/cosv/backend/controllers/AvatarController.kt

Added avatar controller to cosv

Fixed upload avatar

---

cosv-frontend/src/main/kotlin/com/saveourtool/cosv/frontend/routing/BasicRouting.kt
frontend-common/src/main/kotlin/com/saveourtool/frontend/common/components/views/ThanksForRegistrationView.kt
save-frontend/src/main/kotlin/com/saveourtool/save/frontend/routing/BasicRouting.kt

Added Thanks for registration view in cosv module

---

cosv-frontend/src/main/kotlin/com/saveourtool/cosv/frontend/components/topbar/TopBarUserField.kt
frontend-common/src/main/kotlin/com/saveourtool/frontend/common/components/basic/AvatarRenderers.kt
frontend-common/src/main/kotlin/com/saveourtool/frontend/common/components/views/userprofile/UserProfileView.kt

Added default avatar

---

save-cloud-charts/save-cloud/templates/agent.yaml
save-cloud-charts/save-cloud/templates/gateway.yaml
save-cloud-charts/save-cloud/templates/mysql-service.yaml
save-cloud-charts/save-cloud/values.yaml

- added deployment of mysql service
- rename his-certs to ca certs
- remove cosv service from backend deployment

fix mysql endpoint, secrets, doubling of cosv service
