build.gradle.kts, buildSrc/build.gradle.kts, buildSrc/src/main/kotlin/Versions.kt, save-common/build.gradle.kts, save-frontend/build.gradle.kts, save-frontend/src/main/kotlin/org/cqfn/save/frontend/App.kt, save-orchestrator/build.gradle.kts
* Switched frontend from bintray to kotlin space
* Bump kotlin-js-wrappers version
* Fixed App.kt
* Removed bintray repo for kotlinx.datetime
* Removed jcenter repository from buildSrc and root build.gradle.kts
Bintray will be shut down soon, need to remove it from project dependencies. All of our dependencies have already migrated, so it's safe.
=> Infra: Remove dependencies on bintray

buildSrc/src/main/kotlin/org/cqfn/save/buildutils/SpringBootConfiguration.kt
* Use LIFO leasing strategy and max idle timeout for netty connection pool
Possible fix for `readAddress(..) failed: Connection reset by peer`. According to https://github.com/reactor/reactor-netty/issues/564, these options should fix the error. It seems, that docker environent is closing idle connections from netty's pool after some time. Anyway, after these options have been enabled, I haven't observed the issue, which would randomly occur the day before.
Closes #150
=> Change reactor-netty configuration parameters

save-agent/build.gradle.kts, save-agent/src/nativeMain/kotlin/org/cqfn/save/agent/AgentConfiguration.kt, save-agent/src/nativeMain/kotlin/org/cqfn/save/agent/SaveAgent.kt, save-agent/src/nativeMain/resources/agent.properties, save-backend/src/main/kotlin/org/cqfn/save/backend/controllers/AgentsController.kt, save-backend/src/main/kotlin/org/cqfn/save/backend/service/TestSuitesService.kt, save-backend/src/test/kotlin/org/cqfn/save/backend/controller/AgentsControllerTest.kt, save-cloud-common/src/jvmMain/kotlin/org/cqfn/save/entities/AgentStatus.kt, save-frontend/build.gradle.kts, save-orchestrator/build.gradle.kts, save-orchestrator/src/main/kotlin/org/cqfn/save/orchestrator/SaveOrchestrator.kt, save-orchestrator/src/main/kotlin/org/cqfn/save/orchestrator/controller/HeartbeatController.kt, save-orchestrator/src/main/kotlin/org/cqfn/save/orchestrator/service/AgentService.kt, save-orchestrator/src/main/kotlin/org/cqfn/save/orchestrator/service/DockerService.kt, save-orchestrator/src/test/kotlin/org/cqfn/save/orchestrator/controller/heartbeat/HeartbeatControllerTest.kt, save-preprocessor/src/main/kotlin/org/cqfn/save/preprocessor/service/TestDiscoveringService.kt, save-preprocessor/src/main/resources/application.properties
* Execution and AgentsStatus are marked as FINISHED after agents shutdown
* Enabled debug for save-agent
* Fix property file path in backend saveTestSuite
* Added inputs for code generation tasks in gradle
* Added more logging for TestDiscoveringService, enabled debug logging in application.properties
* Publish agent's version instead of cli version
Closes #145
=> Orchestrator: Fixes for agents shutdown logic

save-frontend/build.gradle.kts, save-frontend/src/main/kotlin/org/cqfn/save/frontend/App.kt, save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/TopBar.kt, save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/basic/Card.kt, save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/basic/ScrollToTopButton.kt, save-frontend/src/main/kotlin/org/cqfn/save/frontend/externals/fontawesome/FaSetup.kt, save-frontend/src/main/kotlin/org/cqfn/save/frontend/externals/fontawesome/FontAusomeIconBuilders.kt, save-frontend/src/main/kotlin/org/cqfn/save/frontend/externals/fontawesome/FontAwesomeIcon.kt, save-frontend/src/main/kotlin/org/cqfn/save/frontend/externals/fontawesome/FontAwesomeIconProps.kt, save-frontend/src/main/kotlin/org/cqfn/save/frontend/externals/fontawesome/Icons.kt, save-frontend/src/main/resources/index.html, save-frontend/src/main/resources/scss/_variables.scss, save-frontend/src/main/resources/scss/save-frontend.scss, save-frontend/webpack.config.d/css.js, save-frontend/webpack.config.d/optimizations.js, save-frontend/webpack.config.d/plugins.js
* Added dependecnies
* Added react components
* Use postcss to compile bootstrap scss
* Removed task for copying webfonts during build, because they are no more used
* Added separate chunks for own code and for vendors bundle
The first change reduces bundle size from 3.17 MB to 2.44 MB, using postcss reduces it further to 2.35 MB.
It is further split into two assets:
```
Assets: 
save-frontend.js (1.1 MiB)
save-frontend-vendors.js (1.26 MiB)
```
Also, First Paint time is reduced from >10 sec to ~5 sec!
Further improvements can be achieved if we migrate from bootsrap+jquery to react-bootstrap
Addresses and partially closes #141
=> Improve frontend bundle packaging and size

save-agent/src/nativeMain/kotlin/org/cqfn/save/agent/SaveAgent.kt, save-agent/src/nativeTest/kotlin/org/cqfn/save/agent/SaveAgentTest.kt, save-cloud-common/src/commonMain/kotlin/org/cqfn/save/agent/AgentState.kt, save-orchestrator/src/main/kotlin/org/cqfn/save/orchestrator/controller/HeartbeatController.kt, save-orchestrator/src/test/kotlin/org/cqfn/save/orchestrator/controller/heartbeat/HeartbeatControllerTest.kt
* Added state STARTING
* Added tests
Previousely we had the following case:
- Agents are started
- The first agent sends IDLE, gets a batch of tests
- The second agent sends IDLE, there are no more tests
- Shutdown sequence is initiated; because all agents have IDLE in DB they all are subjects for termination
- First agent is stopped whether it has finished execution or not
This PR proposes a new state for the very first heartbeat, and for this state orchestrator doesn't check shutdown conditions.
This is part of #156
=> Add AgentState.STARTING for initial agent's heartbeat

db/changelog/v-1/11-changeset-test-agent-insert-data.xml, save-backend/src/main/kotlin/org/cqfn/save/backend/SaveApplication.kt, save-backend/src/main/kotlin/org/cqfn/save/backend/controllers/AgentsController.kt, save-backend/src/main/kotlin/org/cqfn/save/backend/controllers/ExecutionController.kt, save-backend/src/main/kotlin/org/cqfn/save/backend/repository/AgentStatusRepository.kt, save-backend/src/main/kotlin/org/cqfn/save/backend/repository/TestSuiteRepository.kt, save-backend/src/main/kotlin/org/cqfn/save/backend/service/ExecutionService.kt, save-backend/src/main/kotlin/org/cqfn/save/backend/service/TestSuitesService.kt, save-backend/src/test/kotlin/org/cqfn/save/backend/controller/ExecutionControllerTest.kt, save-cloud-common/src/commonMain/kotlin/org/cqfn/save/execution/ExecutionDto.kt, save-cloud-common/src/jvmMain/kotlin/org/cqfn/save/entities/Execution.kt, save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/views/ExecutionView.kt, save-orchestrator/src/main/kotlin/org/cqfn/save/orchestrator/SaveOrchestrator.kt, save-orchestrator/src/main/kotlin/org/cqfn/save/orchestrator/controller/AgentsController.kt, save-orchestrator/src/main/kotlin/org/cqfn/save/orchestrator/service/AgentService.kt, save-orchestrator/src/main/kotlin/org/cqfn/save/orchestrator/service/DockerService.kt, save-orchestrator/src/test/kotlin/org/cqfn/save/orchestrator/controller/agents/AgentsControllerTest.kt, save-preprocessor/src/main/kotlin/org/cqfn/save/preprocessor/controllers/DownloadProjectController.kt, save-preprocessor/src/test/kotlin/org/cqfn/save/preprocessor/DownloadProjectTest.kt
* Added endpoint in backend
* Added button on frontend
* Logic in preprocessor
* Endpoint for cleanup in orchestrator
This change covers only executions with type `GIT`. Executions with type `STANDARD` need to be covered separately, after they are supported in #199 
Caveats:
* TestRootPath is deduced for executions with `testSuiteIds == ALL` based on their proeprties file path. This seems like a hack and needs to be sorted along with #205 
* Current implementation discards all artifacts from previous runs (cloned repo, image, container)
Closes #216
=> Rerun executions with GIT type

docker-compose.yaml.template, save-backend/src/main/kotlin/org/cqfn/save/backend/controllers/CloneRepositoryController.kt, save-backend/src/main/kotlin/org/cqfn/save/backend/controllers/DownloadFilesController.kt, save-backend/src/main/kotlin/org/cqfn/save/backend/repository/FileSystemRepository.kt, save-backend/src/test/kotlin/org/cqfn/save/backend/DownloadFilesTest.kt, save-backend/src/test/kotlin/org/cqfn/save/backend/controller/CloningRepositoryControllerTest.kt, save-cloud-common/src/jvmMain/kotlin/org/cqfn/save/domain/FileInfoJvm.kt, save-frontend/build.gradle.kts, save-frontend/src/main/kotlin/org/cqfn/save/frontend/App.kt, save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/basic/FileUploader.kt, save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/views/ProjectView.kt, save-frontend/src/main/kotlin/org/cqfn/save/frontend/externals/fontawesome/Icons.kt, save-frontend/src/main/kotlin/org/cqfn/save/frontend/utils/Utils.kt, save-frontend/webpack.config.d/dev-server.js
* Upload file after submission from frontend
* Return FileInfo after uploading file
* Select files from the list of available
* Accept Flux of `FileInfo`s on backend in `/submit*` handlers
* Added devServer proxy for local development of save-frontend
* Make fonts in ProjectView on the right side smaller
Closes #210
=> Persistent file storage

save-preprocessor/src/main/kotlin/org/cqfn/save/preprocessor/service/TestDiscoveringService.kt
* Update usage of SAVE api in preprocessor after latest changes
=> Hotfix: Update usage of SAVE api in preprocessor after latest changes

save-agent/src/linuxX64Main/kotlin/org/cqfn/save/agent/SaveAgent.kt, save-preprocessor/src/main/kotlin/org/cqfn/save/preprocessor/controllers/DownloadProjectController.kt, save-preprocessor/src/test/kotlin/org/cqfn/save/preprocessor/DownloadProjectTest.kt, save-preprocessor/src/test/kotlin/org/cqfn/save/preprocessor/utils/RepositoryVolume.kt
* Changed logic
* Minor refactoring
We didn't close `Git` object after it has been used, which sometimes lead to inability to delete directory. It may be the reason, why tests in preprocessor were flaky.
=> Preprocessor: Close `Git` object

save-orchestrator/src/main/kotlin/org/cqfn/save/orchestrator/controller/HeartbeatController.kt, save-orchestrator/src/main/kotlin/org/cqfn/save/orchestrator/service/AgentService.kt, save-orchestrator/src/main/kotlin/org/cqfn/save/orchestrator/service/DockerService.kt
* Updated logic
Orchestrator is executed as root (to access docker socket), but files are in a shared volume, so they need to have correct ownership.
=> Orchestrator: Chown copied files to `cnb:cnb`

db/changelog/v-2/03-changeset-test-suite.xml, gradle.properties, save-backend/src/main/kotlin/org/cqfn/save/backend/service/TestSuitesService.kt, save-backend/src/test/kotlin/org/cqfn/save/backend/controller/TestSuitesControllerTest.kt, save-cloud-common/src/commonMain/kotlin/org/cqfn/save/testsuite/TestSuiteDto.kt, save-cloud-common/src/jvmMain/kotlin/org/cqfn/save/entities/TestSuite.kt, save-frontend/build.gradle.kts, save-frontend/src/main/kotlin/org/cqfn/save/frontend/App.kt, save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/basic/CheckBoxGrid.kt, save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/basic/SuiteDescription.kt, save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/views/CollectionView.kt, save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/views/ProjectView.kt, save-frontend/src/main/kotlin/org/cqfn/save/frontend/externals/fontawesome/Icons.kt, save-frontend/src/main/resources/scss/save-frontend.scss, save-preprocessor/src/main/kotlin/org/cqfn/save/preprocessor/controllers/DownloadProjectController.kt, save-preprocessor/src/main/kotlin/org/cqfn/save/preprocessor/service/TestDiscoveringService.kt, save-preprocessor/src/test/kotlin/org/cqfn/save/preprocessor/DownloadProjectTest.kt, save-preprocessor/src/test/kotlin/org/cqfn/save/preprocessor/service/TestDiscoveringServiceTest.kt
* Save description in the DB
* Save only distinct test suites
* Display description on hover on frontend
Closes #247
=> Display description of test suites

save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/views/CollectionView.kt, save-orchestrator/src/main/kotlin/org/cqfn/save/orchestrator/service/DockerService.kt, save-preprocessor/src/main/kotlin/org/cqfn/save/preprocessor/controllers/DownloadProjectController.kt, save-preprocessor/src/test/kotlin/org/cqfn/save/preprocessor/service/TestDiscoveringServiceTest.kt
* Added check on save.properties exist
Close #274
=> Preprocessor: Don't crash if save.properties doesn't exist in the repo

docker-compose.yaml.template, save-orchestrator/src/main/kotlin/org/cqfn/save/orchestrator/docker/ContainerManager.kt
* Updated docker-compose.yaml.template
* Updated ContainerManager.kt
This should help to prevent freezing of container, when loki server is unavailable
=> Use non-blocking mode for loki docker logging driver

save-backend/src/main/kotlin/org/cqfn/save/backend/controllers/TestExecutionController.kt, save-backend/src/main/kotlin/org/cqfn/save/backend/service/TestExecutionService.kt, save-frontend/src/main/kotlin/org/cqfn/save/frontend/App.kt, save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/basic/TestStatusComponent.kt, save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/views/ExecutionView.kt, save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/views/TestExecutionDetailsView.kt, save-frontend/src/main/kotlin/org/cqfn/save/frontend/http/Requests.kt, save-frontend/src/main/kotlin/org/cqfn/save/frontend/utils/Utils.kt
* Added endpoint in TestExecutionController
* Created Requests.kt for common HTTP requests
* Added TestExecutionDetailsView
Continuation of #183 , closes #368
=> Frontend: Add view with verbose test execution data

save-frontend/src/main/kotlin/org/cqfn/save/frontend/App.kt
Other than `exact = false`, react-router requires regex-like setting for repeated params group
=> Hotfix: Capture filePath as repeated parameter

save-backend/src/main/kotlin/org/cqfn/save/backend/scheduling/StandardSuitesUpdateScheduler.kt
* Fix in `StandardSuitesUpdateScheduler`
After https://github.com/diktat-static-analysis/save-cloud/commit/20c706873213ca1c8166d26338ced7cb7b5e1e04 quartz scheduler doesn't start with the following error:
```
Caused by: org.quartz.ObjectAlreadyExistsException: Unable to store Job : 'DEFAULT.UpdateJob', because one already exists with this identification.
```
I wasn't able to figure out, why it wasn't crashing before, because newer spring boot (2.5.4 -> 2.6.0) uses the same version of quartz, 2.3.2.
=> Hotfix: schedule job only if not already scheduled

save-orchestrator/src/main/kotlin/org/cqfn/save/orchestrator/LinuxUtils.kt, save-orchestrator/src/main/kotlin/org/cqfn/save/orchestrator/docker/ContainerManager.kt, save-orchestrator/src/main/kotlin/org/cqfn/save/orchestrator/service/DockerService.kt
Both `kotlin.io.copyRecursively` and `FileUtils.copyDirectory` discard file attributes. I didn't find any ready-to-use solution other than invoking `Files.copy` manually.
Closes #433
=> Bugfix: Keep original file permissions when making recursive copy

gradle/libs.versions.toml, save-agent/src/linuxX64Main/kotlin/org/cqfn/save/agent/SaveAgent.kt, save-backend/src/main/kotlin/org/cqfn/save/backend/service/TestExecutionService.kt, save-cloud-common/src/commonMain/kotlin/org/cqfn/save/utils/TestResultUtils.kt, save-orchestrator/src/main/kotlin/org/cqfn/save/orchestrator/config/ConfigProperties.kt, save-orchestrator/src/main/kotlin/org/cqfn/save/orchestrator/service/DockerService.kt, save-orchestrator/src/test/kotlin/org/cqfn/save/orchestrator/service/DockerServiceTest.kt, save-orchestrator/src/test/resources/application.properties, save-preprocessor/src/main/kotlin/org/cqfn/save/preprocessor/controllers/DownloadProjectController.kt
* Moved trimming of `STANDARD_` prefix from `TestExecutionService` to common utils
* Call it from Agent for both test results and debug info
* Fix setting owner/group in `DockerService`
* Add more logging in agent
=> Remove `STANDARD_` prefix from path when reading it in agent

api-gateway/src/main/kotlin/org/cqfn/save/gateway/security/WebSecurityConfig.kt, save-frontend/src/main/kotlin/org/cqfn/save/frontend/utils/RequestUtils.kt
* Gateway: return 401 for unathorized requests instead of redirect to login
* Handle 401 on frontend - if any request fails with 401, redirect to main page
* After authentication, redirect to `/#/projects` instead of main page
Closes #443
=> Redirect unauthorized requests from FE to login page

save-agent/src/linuxX64Main/kotlin/org/cqfn/save/agent/Main.kt, save-agent/src/linuxX64Main/kotlin/org/cqfn/save/agent/SaveAgent.kt, save-agent/src/linuxX64Main/kotlin/org/cqfn/save/agent/utils/FileUtils.kt, save-agent/src/linuxX64Main/kotlin/org/cqfn/save/agent/utils/HttpUtils.kt, save-agent/src/linuxX64Main/kotlin/org/cqfn/save/agent/utils/Logging.kt
* More logging: log thread id in save-agent
* Run save in a separate single-threaded context (should lead to regular heartbeats while save is being executed)
* Add logs of save-cli into stdout of save-agent
Closes #315
=> Enable multithreading in save-agent

.github/workflows/build_and_test.yml, .github/workflows/deploy_images.yml, .github/workflows/detekt.yml, .gitmodules, settings.gradle.kts
New versions of save-warn-plugin have sarif4k as a transitive dependency. But for now it's not available anywhere.
=> Add sarif4k as a submodule

build.gradle.kts, save-backend/src/main/kotlin/org/cqfn/save/backend/controllers/ProjectController.kt, save-backend/src/main/kotlin/org/cqfn/save/backend/security/ProjectPermissionEvaluator.kt
* Handle nullable `Authentication` in `ProjectPermissionEvaluator`
* Run liquibase on Java 11
Closes #542
=> Support `/projects/non-deleted` for unauthorized requests

docker-compose.yaml.template, save-deploy/loki.yaml, save-deploy/reverse-proxy.conf
* Update reverse-proxy.conf
* Fix websocket connection for loki
* Add loki.yaml, update to 2.4.2
=> infra: Update reverse-proxy.conf to support SSL, fix loki

buildSrc/src/main/kotlin/org/cqfn/save/buildutils/DockerStackConfiguration.kt, docker-compose.yaml, renovate.json
* Rename docker-compose.yaml.template to docker-compose.yaml
* Update DockerStackConfiguration.kt
* Add explicit versions for 3rd party docker images
* Add renovate config for docker images
Initially it seemed to be a good idea to have complete control over compose file while generating it from a template. However, with standard docker way of doing it (via environment variables/environment files) we will be able to use standard tooling (syntax highlighting / format validation / auth-updates etc.). Fixing versions of 3rd party images should also improve stability of deployments.
=> infra: Use env variables in docker-compose.yaml

.github/workflows/detekt.yml, build.gradle.kts, buildSrc/src/main/kotlin/org/cqfn/save/buildutils/DetektConfiguration.kt, buildSrc/src/main/kotlin/org/cqfn/save/buildutils/VersioningConfiguration.kt, detekt.yml, save-agent/build.gradle.kts, save-backend/src/main/kotlin/org/cqfn/save/backend/controllers/DownloadFilesController.kt, save-orchestrator/build.gradle.kts
* Cache save-cli version for 10 minutes in a file in build directory
* Do not apply default diktat configuration for root project (it was leading to diktat being applied on sarif4k files)
* Fix deprecated options in detekt.yml
* Enable SARIF reports for detekt and upload them to Github
Closes #536
=> infra: Cache save-cli version for 10 minutes in a file in build directory

save-agent/src/linuxX64Main/kotlin/org/cqfn/save/agent/Main.kt, save-agent/src/linuxX64Main/kotlin/org/cqfn/save/agent/SaveAgent.kt, save-agent/src/linuxX64Test/kotlin/org/cqfn/save/agent/SaveAgentTest.kt
The problem turned out to be in incorrect usage of `coroutineScope` builder function. Originally, when we had to call `lauch` inside `suspend fun`s and tried to add `CoroutineScope` as a receiver (all launching functions are its extension), IDEA suggested to wrap function body in `coroutineScope` instead, and we followed this suggestion.
However, [docs](https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/coroutine-scope.html) for `coroutineScope` say:
```
This function returns as soon as the given block and all its children coroutines are completed.
```
That's why the caller coroutine got blocked on function call, waiting for all coroutines launched inside `coroutineScope` to finish.
The correct convention of coroutines usage is described …
=> Agent: fix issues with parallel coroutine execution

save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/tables/PagingControl.kt, save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/tables/TableComponent.kt
This is a fix for a regression after #561: every time the table on the ExecutionView renders, there is an error message about job cancellation. It actually happens because the component re-renders, while the previous request is still in progress. This may be an indication of a problem with multiple unnecessary re-renders of table component, but also shouldn't be visible to the users, because eventually data is fetched without problems.
Also, there is no need to call `setPageCount` from `invokeOnCompletion`.
=> Frontend: Remove message about cancellation of data fetching job on ExecutionView

save-frontend/src/main/kotlin/org/cqfn/save/frontend/App.kt, save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/basic/ExecutionStatistics.kt, save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/basic/FileUploader.kt, save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/views/CollectionView.kt, save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/views/ExecutionView.kt, save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/views/HistoryView.kt, save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/views/ProjectView.kt
All functional components shouldn't be called directly from `Component.render` method. Instead, they should be stored in class properties. Explanation of this behavior can be found [here](https://dev.to/igor_bykov/react-calling-functional-components-as-functions-1d3l)
* The following functional components are covered: `executionStatistics`, `testResourcesSelection`, `cardComponent`, `topBar`, `scrollToTopButton`, `executionTestsNotFound`, `testExecutionFiltersRow`, `fileUploader`, `testExecutionDetailsView`, `withRouter`
* function components inside other function components are OK, we need to make sure that top-level function components aren't recreated; `testStatusComponent` shouldn't be extracted, because it's called for a new table row each time
* Make Boolean properties in external …
=> Frontend: Fix recreation of functional components

save-orchestrator/build.gradle.kts, save-orchestrator/src/main/kotlin/org/cqfn/save/orchestrator/Utils.kt, save-orchestrator/src/main/kotlin/org/cqfn/save/orchestrator/docker/ContainerManager.kt, save-orchestrator/src/main/kotlin/org/cqfn/save/orchestrator/service/DockerService.kt, save-orchestrator/src/test/kotlin/org/cqfn/save/orchestrator/docker/ContainerManagerTest.kt, save-orchestrator/src/test/kotlin/org/cqfn/save/orchestrator/service/DockerServiceTest.kt, save-orchestrator/src/test/kotlin/org/cqfn/save/orchestrator/testutils/TestConfiguration.kt
* Measure time of `docker build` command. Will be useful when we need to tune performance in the future.
Related to #344
```
save_orchestrator_docker_build_seconds_max{baseImage="openjdk:11",cmd="BuildImageCmd",} 13.381837036
save_orchestrator_docker_build_seconds_count{baseImage="openjdk:11",cmd="BuildImageCmd",} 1.0
save_orchestrator_docker_build_seconds_sum{baseImage="openjdk:11",cmd="BuildImageCmd",} 13.381837036
```
=> Measure duration of docker commands called from orchestrator

save-backend/src/main/kotlin/org/cqfn/save/backend/repository/LnkUserProjectRepository.kt, save-backend/src/main/kotlin/org/cqfn/save/backend/security/ProjectPermissionEvaluator.kt, save-backend/src/main/kotlin/org/cqfn/save/backend/service/LnkUserProjectService.kt, save-backend/src/test/kotlin/org/cqfn/save/backend/security/ProjectPermissionEvaluatorTest.kt
* Check if the user is project's organization owner
* Use project role instead of list of users with role
* Unit tests for `ProjectPermissionEvaluator`
=> Improvements for ProjectPermissionEvaluator

save-backend/src/main/kotlin/org/cqfn/save/backend/SaveApplication.kt, save-backend/src/main/kotlin/org/cqfn/save/backend/configs/ApplicationConfiguration.kt, save-backend/src/test/kotlin/org/cqfn/save/backend/DatabaseTest.kt, save-backend/src/test/kotlin/org/cqfn/save/backend/DownloadFilesTest.kt, save-backend/src/test/kotlin/org/cqfn/save/backend/controller/CloningRepositoryControllerTest.kt, save-backend/src/test/kotlin/org/cqfn/save/backend/controller/JpaSpecificationTest.kt
This removes necessity to mock all repositories in simple `@WebFluxTest` tests.
=> Extract some spring boot annotations into `ApplicationConfiguration` class

api-gateway/src/main/kotlin/org/cqfn/save/gateway/security/WebSecurityConfig.kt, api-gateway/src/main/resources/application.yml, save-backend/src/main/kotlin/org/cqfn/save/backend/configs/WebConfiguration.kt, save-backend/src/main/kotlin/org/cqfn/save/backend/configs/WebSecurityConfig.kt, save-backend/src/main/resources/application.properties, save-backend/src/test/kotlin/org/cqfn/save/backend/service/PermissionServiceTest.kt, save-frontend/build.gradle.kts, save-frontend/src/main/resources/error.html, save-frontend/src/main/resources/index.html, save-frontend/webpack.config.d/css.js, yarn.lock
* Backend: Add `error.html` and custom error endpoint for spring boot
* Frontend: Change `style-loader` (embeds CSS into JS) to [`mini-css-extract-plugin`](https://webpack.js.org/plugins/mini-css-extract-plugin/)(saves CSS into a separate file), use separate css file instead of bundled into JS
* Gateway: Add custom error endpoint, which delegates to backend's `/error`
Closes #409. After this we can make a dedicated login error page for #626 in a similar way.
=> Add custom error page in backend

save-frontend/build.gradle.kts, yarn.lock
Github Dependabot finds a lot of security vulnerabilities in JS testing dependencies. Even though we don't have proper tests now and these alerts do not actually affect us, we can still bump version from time to time. What makes it more complicated is, that KJS gradle plugin has hardcoded version of a lot of dependencies and they are not analyzed by renovate-bot.
=> Update karma version to resolve security alerts

save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/tables/TableComponent.kt, save-frontend/src/main/kotlin/org/cqfn/save/frontend/http/Exceptions.kt, save-frontend/src/main/kotlin/org/cqfn/save/frontend/utils/RequestUtils.kt
Because displaying non-ok response statuses is now embedded into request methods, it it not necessary to have an additional handler in TableComponent. For other data access exceptions, which can possibly occur, we still need it, though.
=> Display a single error modal on non-ok response statuses

save-backend/src/main/kotlin/org/cqfn/save/backend/controllers/ExecutionController.kt, save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/basic/ProjectStatisticMenu.kt, save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/tables/TableComponent.kt, save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/views/ProjectView.kt
* Update ExecutionController.kt
* Support nullable latestExecutionId on ProjectView and ProjectStatisticMenu
* Fix text position in table header
Closes #635 
Disabled button if latest execution is not available
Placeholder for empty table on execution statistics view
=> Frontend: Support missing latest execution

save-frontend/build.gradle.kts, save-frontend/webpack.config.d/css.js, save-frontend/webpack.config.d/dev-server.js, yarn.lock
* Remove unused `url-loader` from webpack
* Add mocking of `/sec/**` endpoints in webpack-dev-server
* Fix versions of development dependencies
=> Add mocking of `/sec/**` endpoints in webpack-dev-server, cleanup configs

api-gateway/src/main/kotlin/org/cqfn/save/gateway/config/ConfigurationProperties.kt, api-gateway/src/main/kotlin/org/cqfn/save/gateway/security/WebSecurityConfig.kt, save-backend/src/main/kotlin/org/cqfn/save/backend/postprocessor/DockerSecretsDatabaseProcessor.kt
* Gateway/actuator: Don't check password if subnet matches (checking request origin is enough of a security measure, and also authenticated health checks are not supported well enough in Kubernetes)
* Backend/postprocessor: Read secrets base path from env. A bit of un-hardcoding paths from env postprocessor to allow more flexible configuration in other environemtns
Fixme (that we kind of forgot about): logs from postprocessor are not visible, see https://stackoverflow.com/a/42840529
=> Configs for more flexible deployment

save-backend/src/main/kotlin/org/cqfn/save/backend/configs/WebConfiguration.kt, save-backend/src/main/kotlin/org/cqfn/save/backend/utils/LongUtils.kt, yarn.lock
* Support setting `Cache-Control` header for some resources served from backend
* For `/api/avatars` it should work right away, because images with same name shouldn't be changed usually
* For JS, CSS and HTML files we should use more fine-grained controls for caches, currently build timestamp is used as `Last-Modified` value
=> Backend: set `Cache-Control` for static resources

api-gateway/build.gradle.kts, api-gateway/src/main/resources/application.yml, api-gateway/src/main/resources/bootstrap.yml, docker-compose.yaml, gradle/libs.versions.toml, save-backend/build.gradle.kts, save-backend/src/main/kotlin/org/cqfn/save/backend/postprocessor/DockerSecretsDatabaseProcessor.kt, save-backend/src/main/resources/application-kubernetes.properties, save-backend/src/main/resources/application.properties, save-backend/src/main/resources/bootstrap-kubernetes.properties, save-orchestrator/src/main/kotlin/org/cqfn/save/orchestrator/LinuxUtils.kt, save-orchestrator/src/main/kotlin/org/cqfn/save/orchestrator/docker/ContainerManager.kt
Another preparation step for #671
* Gateway: read OAuth properties from secrets in `kubernetes` profile
* Backend: move postprocessor into a separate profile, add kubernetes support for database credentials
* Support setting host IP for orchestrator via env variable `HOST_IP`
=> Integrate spring-cloud-kubernetes

save-orchestrator/src/main/kotlin/org/cqfn/save/orchestrator/LinuxUtils.kt, save-orchestrator/src/main/kotlin/org/cqfn/save/orchestrator/docker/ContainerManager.kt
`host-gateway` is a useful alias for host IP, but it's not always available in Docker and also hard to replicate in systems like Kubernetes. Since we already have functionality to get actual IP representation of host, we can use it here too.
Continuation of #707
=> Orchestrator: Don't rely on `host-gateway`

buildSrc/src/main/kotlin/org/cqfn/save/buildutils/DatabaseUtils.kt, save-backend/src/main/kotlin/org/cqfn/save/backend/postprocessor/DockerSecretsDatabaseProcessor.kt, save-cloud-charts/save-cloud/README.md, save-cloud-charts/save-cloud/templates/backend-deployment.yaml, save-cloud-charts/save-cloud/templates/database-service.yaml, save-cloud-charts/save-cloud/templates/mysql-deployment.yaml, save-cloud-charts/save-cloud/values-minikube.yaml, save-cloud-charts/save-cloud/values.yaml
* Helm: Add init-containers for save-backend Deployment to run database migrations with gradle and liquibase
* Gradle: Reading database credentials using path from environment variable
* Helm: Add configs to deploy MySQL into Kubernetes cluster (enabled by `mysql.external: false` in Helm values), update Secrets for dev profile, update README.md
* Backend: Correctly disable DockerSecretsDatabaseProcessor depending on profiles
* Backend: Use deferred logger in DockerSecretsDatabaseProcessor
Caveats:
* Gradle takes a lot of time to take off inside a container, because it needs to download a lot of dependencies. However, we have a lot of control on reading secrets and still can have depoyment procedures unified for different cases. To mitigate this, we can build our own base image for builds …
=> Kubernetes: Support database migrations using init-containers

save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/basic/OrganizationSettingsMenu.kt, save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/basic/ProjectSettingsMenu.kt, save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/views/OrganizationView.kt, save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/views/ProjectView.kt
=> Bugfix for OrganizationSettingsMenu

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/App.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/TopBar.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/Card.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/FileUploader.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/ScrollToTopButton.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/usersettingsview/UserSettingsView.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/externals/fontawesome/BrandIcons.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/externals/fontawesome/FontAwesomeIconBuilders.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/externals/fontawesome/Icons.kt
Related discussion can be found at https://github.com/FortAwesome/react-fontawesome/issues/70.
We can't use babel to transform imports in existing code, because Kotlin (or Webpack?) hides them and provides already resolved modules to the entrypoint. So instead I'm using a marker interface for FA icons imported from individual modules.
This change leads to the following size reduction: 
- old: `save-frontend-vendors.js (1.79 MiB)`
- new `save-frontend-vendors.js (723 KiB)`
Related issue: #141
=> Import individual font-awesome icons to reduce bundle size

save-preprocessor/src/main/kotlin/com/saveourtool/save/preprocessor/controllers/DownloadProjectController.kt
Support changes after: https://github.com/saveourtool/save-cli/pull/404
* removed reading save.properties -- testRoot cannot be set by this file
The old behavior: `testFiles` is `emptyList()` by default. `testRootDir` cannot be set by `save.properteis`, since we need to have `testRootDir` to read this property
=> Support save-cli 0.4.0

renovate.json
After #867 renovate should be able to use two new managers: [`helmv3`](https://docs.renovatebot.com/modules/manager/helmv3/) and [`helm-values`](https://docs.renovatebot.com/modules/manager/helmv3/)
=> Configure renovate.json to update Helm 3 charts

save-agent/src/linuxX64Main/kotlin/com/saveourtool/save/agent/Main.kt, save-agent/src/linuxX64Main/kotlin/com/saveourtool/save/agent/SaveAgent.kt, save-orchestrator/src/main/kotlin/com/saveourtool/save/orchestrator/docker/DockerAgentRunner.kt, save-orchestrator/src/main/kotlin/com/saveourtool/save/orchestrator/service/HeartBeatInspector.kt
* Agent: launch heartbeats in a nested coroutine scope, because top-level BlockingCoroutine shouldn't be cancelled
* Agent: don't update status while data is being sent to backend
* Orchestrator: Clean up already stopped agents in `HeartBeatInspector`
* Orchestrator: fix `DockerAgentRunner#isAgentStopped` method
Part of #862
=> Fixes for agents shutdown logic

save-agent/src/linuxX64Main/kotlin/com/saveourtool/save/agent/SaveAgent.kt
Currently exception is silently handled inside save-core and we get a new JsonDecodingException. By rethrowing we can handle it in a higher function
=> Agent: Rethrow exception on missing results file

save-agent/src/linuxX64Main/kotlin/com/saveourtool/save/agent/SaveAgent.kt, save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/DownloadFilesController.kt, save-backend/src/main/kotlin/com/saveourtool/save/backend/repository/TestDataFilesystemRepository.kt, save-backend/src/main/kotlin/com/saveourtool/save/backend/service/ExecutionService.kt, save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/agent/TestExecutionDto.kt, save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/execution/ExecutionUpdateDto.kt, save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/entities/TestExecution.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/TestStatusComponent.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/ExecutionView.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/http/Requests.kt, save-orchestrator/src/main/kotlin/com/saveourtool/save/orchestrator/controller/AgentsController.kt, save-orchestrator/src/main/kotlin/com/saveourtool/save/orchestrator/service/AgentService.kt, save-preprocessor/src/main/kotlin/com/saveourtool/save/preprocessor/controllers/DownloadProjectController.kt
What's done:
* add new field failReason in ExecutionUpdateDto
* in case of failure ExecutionUpdateDto is saved in debugInfo folder in execution root
* new endpoint created for ui /get-execution-info
* in case of debug-info is unavailable for the test then in tries to extract and show execution-info
=> Orchestrator: Proper handling for SAVE-cli issues reported by SAVE-agent #778

diktat-analysis.yml, save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/entities/Organization.kt, save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/entities/Contest.kt, save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/entities/Execution.kt, save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/entities/TestSuite.kt
* Ignore `@Entity` for `USE_DATA_CLASS` rule
Part of #820
=> Enable `ignoreAnnotated` option in diktat

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/FileUploader.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/externals/fontawesome/FontAwesomeIconBuilders.kt, save-frontend/src/test/kotlin/com/saveourtool/save/frontend/components/basic/uploader/FileIconTest.kt, save-frontend/src/test/kotlin/com/saveourtool/save/frontend/components/views/OrganizationViewTest.kt, save-frontend/src/test/kotlin/com/saveourtool/save/frontend/components/views/ProjectViewTest.kt
* Change `fontAwesomeIcon` builder to capture the correct instance of `ChildrenBuilder`
* Add test
* ~Increase timeouts for large frontend tests (we don't show `SETTINGS` tab right away anymore; it's only shown after user data with permissions is retrieved)~ Ignore these tests :( They pass locally, but started to fail on CI repeatedly..
=> Fix color of file-icon component

save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/utils/FileUtils.kt
- return Flux.empty() when file doesn't exist
It closes #941
=> ExecutionInfo 404 error

CONTRIBUTING.md, save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/ContestController.kt, save-deploy/README.md, save-deploy/docker-mac-settings.sh, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/ContestEnroller.kt, save-orchestrator/build.gradle.kts, save-orchestrator/src/main/kotlin/com/saveourtool/save/orchestrator/docker/DockerContainerManager.kt, save-orchestrator/src/main/kotlin/com/saveourtool/save/orchestrator/service/DockerService.kt, save-orchestrator/src/main/resources/application-mac.properties
* Specified base agent docker image architecture to be `linux/amd64`
* Updated `mac` profile for `save-orchestrator`
* Updated check in dependencies from `save-orchestrator` (now it checks that current platform is NOT linux)
* Improved `ContestEnroller` on frontend - now you cannot participate in stub contest
* Updated `CONTRIBUTING.md` and `save-deploy/README.md`
* Added shell script for docker tcp listening on Mac
=> Run executions on mac

gradle/libs.versions.toml, save-backend/src/main/kotlin/com/saveourtool/save/backend/service/TestSuitesService.kt, save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/entities/TestSuite.kt
Follow up for #925. We now send tags in `TestSuiteDto`s, but don't use them in `findOne` before saving tests. This leads to errors after data is initially saved and `findOne` starts to return more than one entry.
Also specifies save-core version to `0.3.2` unitl https://github.com/saveourtool/save-cli/issues/429 is implemented. Then it should be integrated in save-cloud (e.g. we should check how cliArgs in orhcestrator will be constructed)
=> Hotfix: respect tags when saving Test Suites

docker-compose.yaml, save-cloud-charts/save-cloud/templates/orchestrator-deployment.yaml, save-orchestrator/src/main/kotlin/com/saveourtool/save/orchestrator/config/ConfigProperties.kt, save-orchestrator/src/main/resources/application-mac.properties, save-orchestrator/src/main/resources/application.properties, save-orchestrator/src/test/kotlin/com/saveourtool/save/orchestrator/service/DockerServiceTest.kt, save-orchestrator/src/test/resources/application-mac.properties, save-orchestrator/src/test/resources/application.properties
After #958 this property is no more used; orchestrator doesn't need a shared mount with preprocessor anymore
* Remove property
* Remove mount in Docker
* Remove mount in k8s; preprocessor and orchestrator probably can run on different nodes now!
=> Remove `test-resources.base-path` in orchestrator because it's no more used

.github/workflows/backend-api-spec-update.yml, save-backend/build.gradle.kts
* Change `jvmArgs` for open api spec only on CI
=> Change `jvmArgs` for open api spec only on CI

save-backend/src/test/resources/files/debugInfo/1/WarnPlugin/test/src/test/suite1/testPath2-debug.json, save-backend/src/test/resources/files/debugInfo/1/WarnPlugin/test/src/test/suite2/testPath4-debug.json, save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/domain/TestResultLocation.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/ExecutionView.kt
* Store additional information in a separate map instead of original object
* Add example debug info into backend's resources
* Make `TestResultDebugInfo.debugInfo` truly optional
Closes #942
=> Fix expanded row on ExecutionView.kt

save-orchestrator/src/main/kotlin/com/saveourtool/save/orchestrator/docker/DockerAgentRunner.kt
Follow-up after #1030. Docker doesn't pull image when creating a container (these commands are combined only in `docker run`, which is part of docker CLI only, not API). If image is already preset, pull cmd is no-op.
=> Pull base image before creating container

save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/LnkContestProjectController.kt, save-backend/src/main/kotlin/com/saveourtool/save/backend/repository/LnkUserProjectRepository.kt, save-backend/src/main/kotlin/com/saveourtool/save/backend/service/LnkUserProjectService.kt, save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/entities/Project.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/ContestEnroller.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/testsuiteselector/TestSuiteSelector.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/CreationView.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/externals/modal/Modal.kt
=> Minor fixes on frontend

save-cloud-charts/save-cloud/templates/backend-deployment.yaml
Part of #727. Running `liquibaseUpdate` using Gradle task takes too much time and resources, because Gradle needs to compile and configure all our buildscripts, including downloading of Kotlin/Native etc. This makes running DB migrations take forever when deploying to Kubernetes. This PR changes it using a ready-to-use image with Liquibase CLI.
=> [Helm] Run liquibase using `liquibase` image instead of Gradle task

save-backend/backend-api-docs.json, save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/TestSuitesSourceController.kt, save-backend/src/main/kotlin/com/saveourtool/save/backend/service/TestSuitesSourceService.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/TestSuiteSourceCreationComponent.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/contests/ContestCreationComponent.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/testsuiteselector/TestSuiteSelector.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/testsuiteselector/TestSuiteSelectorBrowserMode.kt
This PR closes #1079
* Added (returned back) testSuiteSelector for general tests - all the avaliable ones
* Fixed an issue with TestSuiteSelector in browser mode - now input form is cleared when an entity from avaliable list is chosen
* Fixed an issue with unclosing modal - now when TestSuiteSource is successfully created, a new request for a fetch is sent
=> Fixes for `TestSuiteSelector` and `TestSuiteSourceCreationComponent`

.github/workflows/deploy_images.yml
Caused by changes in ded475278ee66d06787741c523777ce25baa84b9, where I've changed configuration for `Download` tasks for save-agent and save-cli. It now works better and doesn't rely on manual copying, like it used to be in this workflow.
Example run with these changes: https://github.com/saveourtool/save-cloud/runs/8017837622?check_suite_focus=true
=> Hotfix: Set correct path to save-cli in `deploy_images.yml`

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/ExecutionLabels.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/contests/ContestSummaryMenu.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/ContestExecutionView.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/ExecutionView.kt
This PR is connected with #1035 
* Slightly improved `ContestSummaryMenu`
* Fixed styles for execution labels for non-contest executions.
=> ContestSummaryMenu improvements

save-cloud-charts/save-cloud/README.md, save-cloud-charts/save-cloud/templates/_helpers.tpl, save-cloud-charts/save-cloud/templates/backend-deployment.yaml, save-cloud-charts/save-cloud/templates/gateway-deployment.yaml, save-cloud-charts/save-cloud/templates/orchestrator-configmap.yaml, save-cloud-charts/save-cloud/templates/orchestrator-deployment.yaml, save-cloud-charts/save-cloud/values-minikube.yaml, save-orchestrator/src/main/kotlin/com/saveourtool/save/orchestrator/config/ConfigProperties.kt, save-orchestrator/src/main/kotlin/com/saveourtool/save/orchestrator/controller/HeartbeatController.kt, save-orchestrator/src/main/kotlin/com/saveourtool/save/orchestrator/kubernetes/KubernetesManager.kt, save-orchestrator/src/main/kotlin/com/saveourtool/save/orchestrator/service/DockerService.kt, save-orchestrator/src/test/kotlin/com/saveourtool/save/orchestrator/docker/KubernetesManagerTest.kt, save-orchestrator/src/test/resources/application-kubernetes.properties
* Remove properties for PVC
* Add properties for agent pod requests/limits (last part of and closes #783)
* Remove `isAgentsStopInProgress` completely (closes #154 as described in the comment there)
* Helm: Make gateway and orchestrator single-replica
* Helm: Add version to common pod labels
* Helm: Support different image versions per service
* Helm: Support running DB migrations from a different branch
=> Various improvements in orchestrator

buildSrc/src/main/kotlin/com/saveourtool/save/buildutils/VersioningConfiguration.kt
Respect values of `-PsaveCliPath` and `-PsaveCliVersion` only if save-core version in `libs.versions.toml` ends with `-SNAPSHOT`
=> [Gradle] Use custom save-cli distribution only with snapshot

save-backend/src/main/kotlin/com/saveourtool/save/backend/service/TestExecutionService.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/ExecutionLabels.kt
* Store aggregated metrics in Execution excluding `NOT_APPLICABLE` metrics from individual test executions (until we can calculate scores for other types of plugins too)
* Change logic of dispaly on frontend: don't calculate metrics only if all test executions under an execution are `NOT_APPLICABLE`; otherwise use filtered data from Execution
Related to #1115
=> Don't recalculate counters in Execution if value is `NOT_APPLICABLE`

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/App.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/CreationView.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/OrganizationView.kt, save-frontend/src/test/kotlin/com/saveourtool/save/frontend/components/views/OrganizationViewTest.kt
- `a()` usages replaced with `Link()` (more router-friendly)
- Fixes #754.
=> When creating a new project, pre-select the organization if possible

buildSrc/src/main/kotlin/com/saveourtool/save/buildutils/GitHookInstallation.kt, save-agent/build.gradle.kts, save-backend/build.gradle.kts
* Do not hardcode paths in `copyAgentDistribution` task configuration
* Change some eager task configurations to lazy
=> [Gradle] Do not hardcode paths in `copyAgentDistribution` task configuration

buildSrc/src/main/kotlin/com/saveourtool/save/buildutils/DockerStackConfiguration.kt, docker-compose.yaml
Now the whole application is always deployed from the same image tag. This change allows overriding some of the tags, for example to avoid recreating services that are not affected by a particular change to be deployed.
=> [docker-compose] Support different image tags for services in docker-compose.yaml

save-cloud-charts/save-cloud/templates/_helpers.tpl, save-cloud-charts/save-cloud/values.yaml
Originally I've added a custom config that suppresses default configs. My intention was to extract service name through a pod label. However, default config is sufficient for this too with the only difference that it doesn't rename the label. Moreover, default configuration automatically configures scraping of all possible cluster targets, including kubelet. These metrics can be used to monitor save-agent pods (e.g. system resources consumption) without any changes in agents.
=> [Helm] Discard custom prometheus config and use default one

save-cloud-charts/save-cloud/templates/mysql-deployment.yaml
If the password is purely numerical (like we have for dev database), then Helm complains that it cannot unmarshal a number into a string. Adding `| quote` transformation solves the issue.
=> [Helm] Hotfix: Add quotes for mysql password

save-backend/build.gradle.kts
If `save-agent.kexe` gets downloaded *before* Gradle (re-)configures the project, then `agentDistro/save-agent.kexe` rather than `agentDistro/` will become a CLASSSPATH entry, resulting in an HTTP 404 when accessing `/internal/files/download-save-agent` in local deployments.
=> Use the `agentDistro/` directory rather than its children as a CLASSPATH entry

save-backend/src/main/kotlin/com/saveourtool/save/backend/configs/ConfigProperties.kt, save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/internal/AgentsController.kt, save-backend/src/main/resources/application-dev.properties, save-backend/src/main/resources/application.properties, save-backend/src/test/resources/application.properties
This change makes sure that the explicitly configured back-end URL (http://docker.host.internal:5800) is always reported by the back-end to agents.
=> Explicitly configure the back-end URL in production, too

save-backend/backend-api-docs.json, save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/LnkOrganizationTestSuiteController.kt, save-backend/src/main/kotlin/com/saveourtool/save/backend/service/TestSuitesService.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/organizations/testsuitespermissions/ManageTestSuitePermissionsCard.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/organizations/testsuitespermissions/PermissionManagerMode.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/utils/ChildrenBuilderUtils.kt
This PR closes #1276
* Improved `manageTestSuitePermissionsComponent` to be able to manage test suite visibility
* Moved `PermissionManagerMode` to separate file
* Added endpoint to make a batch of test suites public/private
https://user-images.githubusercontent.com/35039155/196665399-e8f44921-5049-4426-991b-e8917f82c1fd.mov
=> Make test suites public/private again!

save-cloud-charts/save-cloud/templates/backend-configmap.yaml, save-cloud-charts/save-cloud/templates/orchestrator-configmap.yaml, save-cloud-charts/save-cloud/templates/preprocessor-configmap.yaml, save-cloud-charts/save-cloud/templates/sandbox-configmap.yaml, save-cloud-charts/save-cloud/values.yaml
Extracted from #1238; part of #1049. This PR moves `/actuator` as well as `/swagger-ui.html` to a new port, that would be protected by a `NetworkPolicy` under #1247.
=> [Helm] Set another port as a management port for all JVM services

save-orchestrator/build.gradle.kts
Otherwise, `NCDFE` is thrown when deserializing TestStatus.
=> Add `save-common` to the list of orchestrator dependencies

.github/workflows/build-base-images.yaml, docker-compose.yaml, save-orchestrator-common/src/main/kotlin/com/saveourtool/save/orchestrator/docker/DockerAgentRunner.kt
* Make default docker swarm network `attachable`. This is required to be able to attach agents to this network and use service name based DNS
* Change base images for save-base JDK to ubuntu-focal based images of eclipse-temurin. Containers based on Ubuntu 22 don't work normally (on Ubuntu 20? Or on an older version of Docker?)
=> Make default docker swarm network `attachable`

save-backend/src/main/kotlin/com/saveourtool/save/backend/security/TestSuitePermissionEvaluator.kt, save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/utils/Constants.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/organizations/OrganizationTestsMenu.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/organizations/testsuitespermissions/ManageTestSuitePermissionsCard.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/organizations/testsuitespermissions/PermissionManagerMode.kt
This PR closes #1350
* Removed logic for super admins from `TestSuitePermissionEvaluator`
* Split different modes of permission management (`PUBLISH` and `TRANSFER`)
* Fixed unexpected null in modal title
* Changed default debounce period (`750` -> `250`)
* Changed placeholder for organization name input form
=> Test suite permissions improvements

save-orchestrator/src/main/resources/application-dev.properties
* Returned `orchestrator.agent-settings.backend-url` property into `save-orchestrator`'s `application-dev.properties`
=> Return of the `orchestrator.agent-settings.backend-url`

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/FileUploader.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/ManageUserRoleCard.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/organizations/ManageGitCredentialsCard.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/organizations/OrganizationTestsMenu.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/projects/ProjectSettingsMenu.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/OrganizationView.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/usersettings/DeleteOrganizationButton.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/utils/RequestUtils.kt
As far as in some implementations `DELETE` method might have a body and is some it might not, it is not a good idea to support not-`undefined` body.
* Forbade `DELETE` request method to have anything but `undefined` as its body
=> Body of DELETE request should always be undefined

save-backend/backend-api-docs.json, save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/OrganizationController.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/OrganizationAdminView.kt
=> Support the `onlyActive` parameter for the `/organizations/all` call to avoid client-side filtering

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/testsuiteselector/TestSuiteSelectorBrowserMode.kt
* Made breadcrumb items (except the very last) look like a link (`btn-link`)
=> Minor testSuiteSelectorBrowserMode breadcrumb improvements

save-backend/backend-api-docs.json, save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/LnkOrganizationTestSuiteController.kt, save-backend/src/main/kotlin/com/saveourtool/save/backend/service/TestSuitesService.kt, save-backend/src/test/kotlin/com/saveourtool/save/backend/controller/OrganizationControllerTest.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/organizations/testsuitespermissions/ManageTestSuitePermissionsCard.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/testsuiteselector/TestSuiteSelectorBrowserMode.kt
This PR closes #1413
* Fixed `testSuiteSelectorBrowserMode` to show if no test suites are found
* Fixed endpoint `/test-suites/{organizationName}/available`
* Added `LnkOrganizationTestSuite` creation when fetching source
=> manageTestSuitePermissionsComponent fix

gradle/libs.versions.toml, save-backend/build.gradle.kts, save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/RunExecutionController.kt, save-cloud-common/build.gradle.kts, save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/spring/utils/WebClientUtils.kt, save-orchestrator/src/main/kotlin/com/saveourtool/save/orchestrator/service/BackendAgentRepository.kt, save-preprocessor/src/main/kotlin/com/saveourtool/save/preprocessor/controllers/AwesomeBenchmarksDownloadController.kt, save-preprocessor/src/main/kotlin/com/saveourtool/save/preprocessor/service/TestsPreprocessorToBackendBridge.kt
* Add extension function `WebClient.Builder.applyAll`
* Inject `WebClientCustomizer`s as an iterable
* Throw exception in preprocessor in case backend answers with non-ok code
* Change `${HOME}` to `${user.home}` to make `generateApiDocs` task platform-independent
This PR was originally a part of #1238. As far as IDEA shows, now there is only one customizer other than ours:  `MetricsWebClientCustomizer` which is configured by `HttpClientMetricsAutoConfiguration`.
=> Inject `WebClientCustomizer`s as a collection

save-backend/backend-api-docs.json, save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/OrganizationController.kt, save-backend/src/main/kotlin/com/saveourtool/save/backend/repository/OrganizationRepository.kt, save-backend/src/main/kotlin/com/saveourtool/save/backend/security/OrganizationPermissionEvaluator.kt, save-backend/src/main/kotlin/com/saveourtool/save/backend/security/ProjectPermissionEvaluator.kt, save-backend/src/main/kotlin/com/saveourtool/save/backend/security/TestSuitePermissionEvaluator.kt, save-backend/src/main/kotlin/com/saveourtool/save/backend/service/OrganizationService.kt, save-backend/src/test/kotlin/com/saveourtool/save/backend/controller/LnkUserOrganizationControllerTest.kt, save-backend/src/test/kotlin/com/saveourtool/save/backend/controller/OrganizationControllerTest.kt, save-backend/src/test/kotlin/com/saveourtool/save/backend/controller/PermissionControllerTest.kt, save-backend/src/test/kotlin/com/saveourtool/save/backend/security/OrganizationPermissionEvaluatorTest.kt, save-backend/src/test/kotlin/com/saveourtool/save/backend/security/ProjectPermissionEvaluatorTest.kt, save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/entities/OrganizationStatus.kt, save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/entities/ProjectStatus.kt, save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/permission/Permission.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/OrganizationAdminView.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/usersettings/DeleteOrganizationButton.kt
- Add field ```banned``` in OrganizationStatus and ProjectStatus
- Add deleted, banned and recovery Organization logic
- Add new permission ```BAN```
- Correct tests
This pull request close #1436
=> Add delete, recover and banned Organization logic in backend

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/tables/TableComponent.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/ExecutionView.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/contests/ContestGlobalRatingView.kt
Accidentally broken it again in #1488, but this seems to be a more appropriate fix
* Reset page index after applying filters
* Refactor setting new state of filters
* Pass `navigate` from `tableComponent` to `commonHeader` callback
Closes #1475
=> Reset page index after applying filters

save-backend/src/main/kotlin/com/saveourtool/save/backend/SaveApplication.kt, save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/RunExecutionController.kt, save-backend/src/main/kotlin/com/saveourtool/save/backend/service/TestSuitesSourceService.kt, save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/utils/KotlinUtils.kt, save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/utils/KotlinUtilsJvm.kt, save-orchestrator-common/src/main/kotlin/com/saveourtool/save/orchestrator/Utils.kt, save-orchestrator-common/src/main/kotlin/com/saveourtool/save/orchestrator/config/ConfigProperties.kt, save-orchestrator-common/src/main/kotlin/com/saveourtool/save/orchestrator/controller/AgentsController.kt, save-orchestrator-common/src/main/kotlin/com/saveourtool/save/orchestrator/docker/DockerAgentRunner.kt, save-orchestrator-common/src/main/kotlin/com/saveourtool/save/orchestrator/kubernetes/KubernetesManager.kt, save-orchestrator-common/src/main/kotlin/com/saveourtool/save/orchestrator/service/AgentRepository.kt, save-orchestrator-common/src/main/kotlin/com/saveourtool/save/orchestrator/service/AgentService.kt, save-orchestrator-common/src/main/resources/META-INF/save-orchestrator-common/application-docker-socket.properties, save-orchestrator-common/src/main/resources/META-INF/save-orchestrator-common/application-docker-tcp.properties, save-orchestrator-common/src/test/resources/application.properties, save-preprocessor/src/main/kotlin/com/saveourtool/save/preprocessor/SavePreprocessor.kt, save-preprocessor/src/main/kotlin/com/saveourtool/save/preprocessor/service/TestDiscoveringService.kt, save-preprocessor/src/main/kotlin/com/saveourtool/save/preprocessor/service/TestsPreprocessorToBackendBridge.kt, save-sandbox/src/main/resources/application.properties
Refactoring logging (extracted from #1368):
* changed `log-driver` to `use-loki`
* make prefix for save agent configurable: to distinguish save agent for sandbox and save-cloud 
* remove random number for container name: now we copy an execution by creating a new one
=> Changed logDriver to useLoki property

db/v-2/tables/lnk-contest-project.xml, save-backend/src/main/kotlin/com/saveourtool/save/backend/service/LnkContestProjectService.kt, save-backend/src/test/kotlin/com/saveourtool/save/backend/service/LnkContestProjectServiceTest.kt, save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/entities/LnkContestProject.kt
* Remove best score field from lnk_contest_project
=> Remove best_score field from lnk_contest_project

.github/workflows/save-api-release.yml
* Requires no manual actions with https://oss.sonatype.org
* See https://github.com/gradle-nexus/publish-plugin for more details.
=> Use the `closeAndReleaseSonatypeStagingRepository` task when releasing

db/v-2/events/event_scheduler.xml, save-backend/src/main/kotlin/com/saveourtool/save/backend/service/LnkExecutionTestSuiteService.kt, save-backend/src/main/kotlin/com/saveourtool/save/backend/service/TestSuitesService.kt, save-backend/src/test/kotlin/com/saveourtool/save/backend/controller/OrganizationControllerTest.kt
Due to cascade deleting, executionIds is empty on deleting `TestSuite` .
* Moved calculating executionId on early state
It closes #1579
=> Update `Execution.STATUS` on deleting `TestSuite`

save-demo/src/main/kotlin/com/saveourtool/save/demo/utils/Constants.kt
* Renamed `diktat-analysis.yaml` to `diktat-analysis.yml`
=> [DEMO] hotfix for DIKTAT_CONFIG_NAME

gradle.properties
Turns out, `400 Bad Request` from Docker API I was getting locally were caused by querying via HTTP, even though HTTPS should've been enabled. But property value wasn't being read and `http` is being used by default.
=> Fix typo in `gradle.properties`

save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/demo/cpg/CpgGraph.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/cpg/GraphEvents.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/demo/CpgView.kt
* Improved `CpgGraph.removeMultiEdges` by combining anti-directed edges
* Added flag to set `hidden` attribute to unfocused nodes
=> [CPG] parallel edges workaround

db/test-data/contest-insert.xml, db/v-2/tables/contest.xml, db/v-2/tables/execution.xml, db/v-2/tables/organization.xml, save-sandbox/db/tables/execution.xml
TIMESTAMP has a range of '1970-01-01 00:00:01' UTC to '2038-01-19 03:14:07' UTC.
Closes #1586
=> Changed date type of TIMESTAMP to DATETIME

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/topbar/TopBarLinks.kt
* Fixed `SAVE on GitHub` button color to be text-light (as is for all the other buttons in top bar)
=> `SAVE on GitHub` button color in top bar

save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/internal/AgentsController.kt, save-backend/src/main/kotlin/com/saveourtool/save/backend/service/AgentService.kt, save-backend/src/test/kotlin/com/saveourtool/save/backend/controller/AgentsControllerTest.kt, save-orchestrator-common/src/main/kotlin/com/saveourtool/save/orchestrator/service/AgentService.kt, save-orchestrator-common/src/main/kotlin/com/saveourtool/save/orchestrator/service/OrchestratorAgentService.kt, save-orchestrator-common/src/test/kotlin/com/saveourtool/save/orchestrator/controller/agents/AgentsControllerTest.kt, save-orchestrator-common/src/test/kotlin/com/saveourtool/save/orchestrator/controller/heartbeat/HeartbeatControllerTest.kt, save-orchestrator/src/main/kotlin/com/saveourtool/save/orchestrator/service/BackendOrchestratorAgentService.kt, save-sandbox/src/main/kotlin/com/saveourtool/save/sandbox/service/SandboxOrchestratorAgentService.kt
It's part of future task when `Agent` will be created by receiving a first heartbeat and will be created one by one
- refactored `/addAgents` to `/addAgent`
- refactored `/updateAgentStatusesWithDto` to `/updateAgentStatus`
=> Refactored `OrchestratorAgentService`

save-orchestrator-common/src/main/kotlin/com/saveourtool/save/orchestrator/controller/AgentsController.kt, save-orchestrator-common/src/main/kotlin/com/saveourtool/save/orchestrator/controller/HeartbeatController.kt, save-orchestrator-common/src/main/kotlin/com/saveourtool/save/orchestrator/service/AgentService.kt, save-orchestrator-common/src/main/kotlin/com/saveourtool/save/orchestrator/service/ContainerService.kt, save-orchestrator-common/src/main/kotlin/com/saveourtool/save/orchestrator/service/HeartBeatInspector.kt, save-orchestrator-common/src/test/kotlin/com/saveourtool/save/orchestrator/controller/agents/AgentsControllerTest.kt, save-orchestrator-common/src/test/kotlin/com/saveourtool/save/orchestrator/controller/heartbeat/HeartbeatControllerTest.kt
- renamed **isStoppedByContainerId** to **isStopped**
- renamed **cleanup** to **cleanupByExecutionId**
- refactored `getNextRunConfig` to return Mono.empty if there is no job
=> Renaming in ContainerService

authentication-service/build.gradle.kts, build.gradle.kts, save-agent/build.gradle.kts, save-api-cli/build.gradle.kts, save-api/build.gradle.kts, save-backend/build.gradle.kts, save-cloud-common/build.gradle.kts, save-demo-cpg/build.gradle.kts, save-demo/build.gradle.kts, save-orchestrator-common/build.gradle.kts, save-orchestrator/build.gradle.kts, save-preprocessor/build.gradle.kts, save-sandbox/build.gradle.kts
* IDEA no longer highlights occurrences of `alias(libs.*)` in the `plugins {}` section in red.
* This is a Gradle issue, see https://github.com/gradle/gradle/issues/22797.
=> Suppress `DSL_SCOPE_VIOLATION` in `.kts` scrips

save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/RunExecutionController.kt, save-backend/src/main/kotlin/com/saveourtool/save/backend/service/ExecutionService.kt, save-backend/src/main/kotlin/com/saveourtool/save/backend/service/LnkContestExecutionService.kt, save-backend/src/main/kotlin/com/saveourtool/save/backend/service/TestSuitesService.kt
- moved `singleSourceName` and `singleVersion` to `ExecutionService`
- moved  `blockingToMono` outside from `createNew` and `createNewCopy`
It's part of #1670
=> Refactored ExecutionService

.github/workflows/deploy_images.yml, save-cloud-charts/save-cloud/Chart.lock, save-demo-cpg/builder/Dockerfile
Using `builder = "ghcr.io/saveourtool/builder@sha256:ea2b2446f665fed9b24f76ca58efd6f36df79da5e6f529b1b8e97597ed72c305"` (which is the last custom builder image to yield successful results) seems to fix the problem with build. It's based on builder `0.3.135-base`; at least this version should work. This version of the builder also contains `cpython@1.8.0` and `pipenv@1.12.0`, as we suspect one of these builders causes problems.
For the record: untagged versions are still listed at https://github.com/saveourtool/save-cloud/pkgs/container/builder/versions; SHA of builder image was logged in https://github.com/saveourtool/save-cloud/actions/runs/3820228701/jobs/6498384602; matching tag can be found at https://hub.docker.com/layers/paketobuildpacks/builder/0.3.135-base/images/sha256-7e3429ba538 …
=> build: Pin version of `paketo` builder to the last working one

.gitignore, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/ExecutionView.kt
Previously, debug info was added to the array as a whole.
=> Fix the way empty debug info is added to each test execution

save-backend/backend-api-docs.json, save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/ContestController.kt, save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/OrganizationController.kt, save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/TestSuitesSourceController.kt, save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/internal/TestController.kt, save-backend/src/main/kotlin/com/saveourtool/save/backend/service/TestsSourceVersionService.kt, save-backend/src/main/kotlin/com/saveourtool/save/backend/storage/TestSuitesSourceSnapshotStorage.kt, save-backend/src/test/kotlin/com/saveourtool/save/backend/controller/OrganizationControllerTest.kt, save-backend/src/test/kotlin/com/saveourtool/save/backend/controller/TestSuitesControllerTest.kt, save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/test/TestsSourceVersionInfo.kt, save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/testsuite/TestSuitesSourceSnapshotKey.kt, save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/utils/DateTimeUtils.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/organizations/OrganizationTestsMenu.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/organizations/TestSuitesSourcesDisplayer.kt
- added `TestsSourceVersionInfo`
- added `TestsSourceVersionService`
- removed direct usage of `TestSuitesSourceSnapshotKey` and `TestSuitesSourceSnapshotStorage`
It's part of #1717
=> Introduced `TestsSourceVersionInfo` as replacement for `TestSuitesSourceSnapshotKey`

save-backend/src/main/kotlin/com/saveourtool/save/backend/repository/LnkExecutionTestSuiteRepository.kt, save-backend/src/main/kotlin/com/saveourtool/save/backend/service/ExecutionService.kt, save-backend/src/main/kotlin/com/saveourtool/save/backend/service/LnkExecutionTestSuiteService.kt, save-backend/src/main/kotlin/com/saveourtool/save/backend/service/TestSuitesService.kt
=> Move marking execution as `OBSOLETE` on deletion of test suites to ExecutionService

gradle/plugins/src/main/kotlin/com/saveourtool/save/buildutils/PublishingConfiguration.kt, gradle/plugins/src/main/kotlin/com/saveourtool/save/buildutils/publishing-configuration.gradle.kts, save-api/build.gradle.kts, test-analysis-core/build.gradle.kts
This fixes an issue when only artifacts (w/o *.asc digital signatures) get uploaded to Sonatype when a new release is created.
=> Make sure artifact signing is applied *after* Maven configurations are created

.github/workflows/save-api-release.yml, gradle/plugins/src/main/kotlin/com/saveourtool/save/buildutils/PublishingConfiguration.kt, gradle/plugins/src/main/kotlin/com/saveourtool/save/buildutils/publishing-configuration.gradle.kts, save-cloud-common/build.gradle.kts
- The previous PR (which partially fixes the issue) is #1754.
- Now, for Kotlin MPP, all 4 publications (`kotlinMultiplatform`, `js`, `jvm`, and `linuxx64`) get signed.
- Added the ability to sign artifacts via either pure-Java _BCPG_ (`signing.keyId`), or via external `gpg` executable (`signing.gnupg.keyName`). Now, it's possible to run `gradle signKotlinMultiplatformPublication signMavenPublication publishToMavenLocal` to test locally whether signing works correctly.
=> Make sure artifact signing is applied after Maven configurations are created (take 2)

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/SdkSelection.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/fileuploader/FileUploaderWrappers.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/fileuploader/HeavyFileUploader.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/fileuploader/SimpleFileUploader.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/projects/ProjectRunMenu.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/SandboxView.kt
* Moved all file uploader wrappers to `FileUploaderWrappers.kt`
* Renamed `fileUploader` to be `heavyFileUploader`
* Added `simpleFileUploader` - will be used when uploading files to `save-demo`
* Added `isDisabled` to `sdkSelection` props
=> File uploader refactoring

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/testsuitessources/fetch/TestSuitesSourceFetcher.kt
=> When fetching test suites, use the overloaded `post()` version and `jso {}` to construct request parameters

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/TestResourcesSelection.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/projects/ProjectRunMenu.kt
This PR closes #1833
* Fixed wrong `batchSizeForAnalyzer` state setting
* Replaced browser checks with our own - this will cause small arrows disappearing (one in the right of the form)
https://user-images.githubusercontent.com/35039155/217200678-5758ef43-f94e-4c30-9a24-b763aca5ceb3.mov
=> Batch size input form fix

save-backend/src/main/kotlin/com/saveourtool/save/backend/service/TestSuitesService.kt, save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/entities/TestSuite.kt
This PR closes #1834
* Fixed `/filtered` endpoint - @nulls has broken it by adding new field to `TestSuite` forgetting about `ExampleMatcher`'s `ignorePaths`
=> TestSuiteSelector search mode fix

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/TestSuitesDisplayer.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/testsuiteselector/TestSuiteSelector.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/testsuiteselector/TestSuiteSelectorBrowserMode.kt
* Now you can't press on Apply button if you don't selected testSuites
* Made all pointers to in the run tab or selector view as clickable
Closes #1832
=> On the "test sources selector view" change the behaviour of "apply" button

gradle/plugins/src/main/kotlin/com/saveourtool/save/buildutils/save-demo-agent-configuration.gradle.kts, save-demo/build.gradle.kts
* Added `save-demo-agent-configuration.gradle.kts`
* Added runtime dependency to `save-demo` (`save-demo` now depends on `save-demo-agent`)
=> save-demo-agent-configuration.gradle.kts

gradle/plugins/src/main/kotlin/com/saveourtool/save/buildutils/DownloadConfiguration.kt, gradle/plugins/src/main/kotlin/com/saveourtool/save/buildutils/save-agent-configuration.gradle.kts, gradle/plugins/src/main/kotlin/com/saveourtool/save/buildutils/save-demo-agent-configuration.gradle.kts
This change also renames the property from `saveDemoAgentDistroFilepath` to `saveDemoAgentDistroFileUrl`.
=> Correct the path/URL manupulation when `saveDemoAgentDistroFileUrl` is unset

save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/utils/FileUtils.kt, save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/utils/FileUtils.kt, save-cloud-common/src/nativeMain/kotlin/com/saveourtool/save/utils/FileUtils.kt, save-demo-agent/src/nativeMain/kotlin/com/saveourtool/save/demo/agent/Main.kt
The root of the problem is that we have `require` call in native implementation of `parseConfig` that checks the file presence (`require` throws `IllegalArgumentException`) while processing `FileNotFoundException`.
* Removed `require` check in `parseConfig`
* Fixed logging in `save-demo-agent`'s entry point
=> save-demo-agent wrong exception catching

save-backend/src/main/kotlin/com/saveourtool/save/backend/storage/DebugInfoStorage.kt, save-backend/src/main/kotlin/com/saveourtool/save/backend/storage/ExecutionInfoStorage.kt, save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/s3/DefaultS3Operations.kt, save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/storage/AbstractMigrationStorage.kt, save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/storage/AbstractS3Storage.kt, save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/storage/AbstractSimpleStorage.kt, save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/storage/StorageInitializer.kt, save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/storage/StorageWithDatabase.kt
* added `StorageInitializer`
* reused it in AbstractMigrationStorage, AbstractSimpleStorage and StorageWithDatabase
It was extracted from #1867
It was done to encapsulate logic of storage initialization to a dedicated class with further reusing in different implementations of Storage: `StorageCoroutines` and `StorageProjectReactor`
=> Introduced `StorageInitializer`

save-orchestrator-common/src/main/kotlin/com/saveourtool/save/orchestrator/config/ConfigProperties.kt, save-orchestrator-common/src/main/kotlin/com/saveourtool/save/orchestrator/kubernetes/KubernetesManager.kt
* Added `ttlSecondsAfterFinished` to job spec (for now hardcoded to be 3 mins = `180`)
* Added `ttlAfterFinished` to `KubernetesSettings`
=> Agent Jobs should be deleted on completion

save-backend/backend-api-docs.json, save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/DemoManagerController.kt, save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/demo/DemoStatus.kt, save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/utils/ReactorUtils.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/projects/ProjectDemoMenu.kt
This PR closes #1925
* Added `backend` endpoints that check permissions and forward them to `save-demo` (for `/start` and `/stop`)
* Finished frontend menu
* Tested locally on `!kubernetes` profile
* Slightly refactored `DemoManagerController`
=> Demo frontend follow-ups

save-cloud-charts/save-cloud/templates/demo-configmap.yaml
* Removed `demo.s3-storage.endpoint` configuration from `demo-configmap.yaml` as on prod the endpoint is not `http://s3`
=> Hotfix for demo url for s3

save-preprocessor/src/main/kotlin/com/saveourtool/save/preprocessor/common/CloneAndProcessDirectoryAction.kt, save-preprocessor/src/main/kotlin/com/saveourtool/save/preprocessor/common/CloneResult.kt, save-preprocessor/src/main/kotlin/com/saveourtool/save/preprocessor/common/GitRepositoryProcessor.kt, save-preprocessor/src/main/kotlin/com/saveourtool/save/preprocessor/controllers/AwesomeBenchmarksDownloadController.kt, save-preprocessor/src/main/kotlin/com/saveourtool/save/preprocessor/controllers/TestSuitesPreprocessorController.kt, save-preprocessor/src/main/kotlin/com/saveourtool/save/preprocessor/service/GitPreprocessorService.kt, save-preprocessor/src/test/kotlin/com/saveourtool/save/preprocessor/controllers/TestSuitesPreprocessorControllerTest.kt
- This converts `CloneAndProcessDirectoryAction`, `GitRepositoryProcessor`, and `CloneResult` into classes/interfaces.
- Additionally, `fetch()` now returns a `Flux<TestSuiteValidationResult>` instead of `Mono<Unit>`.
- Related: #1096
=> Get rid of type aliases

save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/demo/DemoAgentConfig.kt, save-demo-agent/src/nativeMain/kotlin/com/saveourtool/save/demo/agent/SimpleRunner.kt, save-demo/src/main/kotlin/com/saveourtool/save/demo/service/KubernetesService.kt
nulls surely would like a new timeout-related PR
* Added `HttpTimeout` plugin to `save-demo` `HttpClient`
* Set timeout to match `PROCESS_BUILDER_TIMEOUT_MILLIS` of `save-demo-agent` (currently equals to `20_000L millis`)
* Cleaned `SimpleRunner` up - removed log file creating as it is useless - all the info is available without redirecting to file
* Removed `logFileName` from `RunConfiguration`
=> Demo Agent socket timeout exception

save-demo/src/main/kotlin/com/saveourtool/save/demo/utils/KubernetesUtils.kt
* Removed `hostPort` specification - it seems to use node's port which cased `node(s) didn't have free ports for the requested pod ports` error
=> Remove host port from save-demo-agent container spec

save-backend/src/main/kotlin/com/saveourtool/save/backend/service/ProjectService.kt, save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/demo/DemoDto.kt, save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/filters/DemoFilter.kt, save-demo/src/main/kotlin/com/saveourtool/save/demo/controller/DemoController.kt, save-demo/src/main/kotlin/com/saveourtool/save/demo/service/DemoService.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/demo/welcome/DemoListComponent.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/testsuiteselector/TestSuiteSelectorSearchMode.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/inputform/InputWithDebounce.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/demo/DemoMainView.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/utils/CustomHooks.kt
This PR closes #2057
* Replaced stub `demoList` with functional one
* Added demo filtering
* Implemented `useDebouncedDeferredRequest`
https://user-images.githubusercontent.com/35039155/228872066-a0409284-e4d6-403e-9c6a-ea9184bc7b6a.mov
=> Demo search on frontend

.github/workflows/backend-api-spec-update.yml
* Add pull cmd to open api action - will be useful, if branch is stale, which could be when no PR were created for some time
=> Add pull cmd to open api action

save-cloud-charts/save-cloud/templates/agent-namespace.yaml, save-cloud-charts/save-cloud/templates/agent-service.yaml, save-cloud-charts/save-cloud/templates/demo-configmap.yaml, save-cloud-charts/save-cloud/templates/demo-service-account.yaml, save-cloud-charts/save-cloud/values.yaml, save-demo/src/main/kotlin/com/saveourtool/save/demo/config/Beans.kt, save-demo/src/main/kotlin/com/saveourtool/save/demo/config/ConfigProperties.kt, save-demo/src/main/kotlin/com/saveourtool/save/demo/service/KubernetesService.kt, save-demo/src/main/kotlin/com/saveourtool/save/demo/utils/HttpUtils.kt, save-demo/src/main/kotlin/com/saveourtool/save/demo/utils/KubernetesUtils.kt, save-demo/src/main/resources/application-minikube.properties, save-demo/src/test/kotlin/com/saveourtool/save/demo/utils/HttpUtilsTest.kt
This PR is connected with #2002
* Added `agent-namespace.yaml` for namespace creation for `save-demo-agents` (with configurable name)
* Moved `save-demo-agents` to a separate namespace
* Added service `agent-service.yaml` in order to make `http://demo` url be available from `save-demo-agents`
* Added `save-demo-agent` service creation (service is a child of a job)
* Implemented new way of resolving the pod address
=> save-demo-agents isolation pt I

save-agent/src/commonMain/kotlin/com/saveourtool/save/agent/Main.kt, save-agent/src/commonMain/kotlin/com/saveourtool/save/agent/SaveAgent.kt, save-agent/src/commonMain/kotlin/com/saveourtool/save/agent/utils/HttpUtils.kt, save-agent/src/commonMain/kotlin/com/saveourtool/save/agent/utils/PlatformUtils.kt, save-agent/src/jvmMain/kotlin/com/saveourtool/save/agent/utils/PlatformUtils.kt, save-agent/src/linuxX64Main/kotlin/com/saveourtool/save/agent/utils/PlatformUtils.kt, save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/utils/HttpUtils.kt, save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/utils/PlatformUtils.kt, save-cloud-common/src/jsMain/kotlin/com/saveourtool/save/utils/PlatformUtils.kt, save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/utils/PlatformUtils.kt, save-cloud-common/src/nativeMain/kotlin/com/saveourtool/save/utils/PlatformUtils.kt, save-demo-agent/src/nativeMain/kotlin/com/saveourtool/save/demo/agent/utils/HttpUtils.kt, save-demo/src/main/kotlin/com/saveourtool/save/demo/service/DownloadToolService.kt
* Moved `GenericAtomicReference` and `AtomicLong` from `save-agent` to `save-cloud-common`
* Implemented `KubernetesServiceAccountAuthHeaderPlugin` which gets control over kubernetes service-account token and appends it to every request header
=> KubernetesServiceAccountAuthHeaderPlugin

.github/workflows/deploy_images_reusable.yml
- checkout only if inputs.branch is provided
=> Fix deploy_images_reusable.yml

save-cloud-charts/save-cloud/templates/agent-namespace.yaml, save-demo/src/main/kotlin/com/saveourtool/save/demo/config/ConfigProperties.kt, save-demo/src/main/kotlin/com/saveourtool/save/demo/utils/KubernetesUtils.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/topbar/TopBarLinks.kt
* removed `ResourceQuota` for `save-agent` namespace
* Fixed wrong `demo` highlighting in top bar (used to be highlighted when ProjectView->DemoMenu was opened)
* Added default agent cpu limitations
* Fixed logging for `createResourceOrThrow` of save-demo
=> Removed ResourceQuota for save-agent namespace

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/utils/RequestUtils.kt
This PR closes #2207
* Added `decodeFieldFromJsonStringOrNull`
* Reused `decodeFieldFromJsonStringOrNull` in `unpackMessageOrNull`
=> unpackMessage fix

gradle/libs.versions.toml
- downgraded ktor version to 2.3.0 is due to https://github.com/ktorio/ktor/pull/3609 is not released yet
=> Downgraded ktor version

save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/demo/cpg/cytoscape/CytoscapeEdge.kt, save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/demo/cpg/cytoscape/CytoscapeGraph.kt, save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/demo/cpg/cytoscape/CytoscapeLayout.kt, save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/demo/cpg/cytoscape/CytoscapeNode.kt, save-frontend/build.gradle.kts, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/cpg/GraphLoader.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/graph/CytoscapeVisualizer.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/graph/SigmaGraphVisualizer.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/demo/CpgView.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/externals/graph/CpgUtils.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/externals/graph/cytoscape/CytoscapeWrapper.kt, yarn.lock
* Added `cytoscape` wrapper
* Reused `cytoscape` wrapper with `cytoscapeVisualizer` in order to replace `graphVizVisualizer`
* Fix visuals
* Make all selectors on `DemoCpgView` work
=> cytoscape.js

.gitignore
- added save/save-0.4.0-SNAPSHOT-linuxX64.kexe to gitignore to have a clean git repo for reckon version
=> Fix build image for save-backend and save-sandbox

api-gateway/build.gradle.kts, api-gateway/src/main/kotlin/com/saveourtool/save/gateway/config/ConfigurationProperties.kt, api-gateway/src/test/kotlin/com/saveourtool/save/gateway/StartupTest.kt, api-gateway/src/test/resources/application-dev.yml
- fixed gateway typo
- due to the change in snakeyaml API (2.0), api-gateway is not able to start: `Caused by: java.lang.NoSuchMethodError: org.yaml.snakeyaml.constructor.SafeConstructor: method 'void <init>()' not found`
=> Hotfix with a sanity test for api-gateway

save-cloud-charts/save-cloud/Chart.lock
This reverts commit 7240b5b477d76dcf9411decc187f5d121a5f2bda.
The last _Loki_ version tested to be compatible is [**2.7.4**](https://github.com/grafana/loki/releases/tag/v2.7.4) (see [`renovate.json`](https://github.com/saveourtool/save-cloud/blob/master/renovate.json#L76)), while the chart version **4.9.0** upgrades it to [**2.7.5**](https://github.com/grafana/loki/releases/tag/v2.7.5).
See
https://github.com/grafana/loki/blob/main/production/helm/loki/CHANGELOG.md#490 for more details.
=> Revert "Lock file maintenance (#2143)"

save-cloud-charts/save-cloud/templates/preprocessor-deployment.yaml
- changed volume for preprocessor from `hostPath` to `emptyDir`
It closes #2119
=> Changed volume for preprocessor

db/v-2/tables/vulnerability-date.xml, save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/vulnerability/VulnerabilityController.kt, save-backend/src/main/kotlin/com/saveourtool/save/backend/repository/vulnerability/VulnerabilityDateRepository.kt, save-backend/src/main/kotlin/com/saveourtool/save/backend/service/vulnerability/VulnerabilityService.kt, save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/utils/ReactorUtils.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/fossgraph/VulnerabilityDateModal.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/fossgraph/VulnerabilityInfoTab.kt, save-frontend/src/main/resources/scss/utilities/_timeline.scss
* Implemented vulnerability date deletion on backend
* Supported vulnerability date deletion on frontend
* Fixed an issue when timeline labels acted the same as timeline nodes (now labels are not clickable and `onHover` is not triggered on them)
* Added unique constraint on dates in order to prevent saving duplicates
* Added `409 CONFLICT` as possible API response code for `/save-date` in order to handle it on frontend
https://github.com/saveourtool/save-cloud/assets/35039155/393d64f4-a051-4057-b416-350ec84aa2a6
=> Vulnerability dates should be able to be deleted

gradle/plugins/src/main/kotlin/com/saveourtool/save/buildutils/PublishingConfiguration.kt, save-agent/build.gradle.kts, save-cloud-common/build.gradle.kts, save-demo-agent/build.gradle.kts
- Now, `gradle publish` or `gradle publishToMavenLocal` no longer fail when the project is built with Gradle 8.
- See https://github.com/gradle/gradle/issues/17043 for more details.
- This is a Kotlin issue, targeted at Kotlin 1.9 (see https://youtrack.jetbrains.com/issue/KT-46466).
- Fixes #2286.
=> Correct the dependencies between `publish*` and `sign*` tasks in Kotlin/MPP

save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/filters/VulnerabilityFilter.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/fossgraph/FossGraphCollectionView.kt
Added status and language columns
=> Added status and language columns

save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/LnkUserProjectController.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/contests/ContestListCard.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/contests/ContestSampleListCard.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/contests/ContestsStatistics.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/contests/FeaturedContests.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/contests/GlobalRating.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/contests/MyProjectsRating.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/contests/NewContests.kt
This PR closes #2274 (I hope)
* Added `unsafeMap`s in order to escape error response serialization
=> ContestListView serialization error for unauthorized user

save-frontend/src/main/resources/scss/utilities/_timeline.scss
* Changed label paddings
* Changed label color to `info`
=> Timeline style hotfixes

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/Carousel.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/TimelineComponent.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/demo/welcome/FeaturedDemos.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/tables/TableComponent.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/contests/FeaturedContests.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/fossgraph/CreateVulnerabilityView.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/fossgraph/VulnerabilityBadge.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/fossgraph/VulnerabilityInfoTab.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/externals/progressbar/ReactCircleBuilder.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/themes/Colors.kt
* Changed `green`, `yellow` and `red` colors to bootstrap's `success`, `warning` and `danger`
* Fixed style of organization selector on createVulnerabilityView
* Fixed `Affected projects` section
* Fixed `Add date` button positioning on timelineComponent
* Fixed project card corners
=> Minor vulnerability style fixes

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/AvatarRenderers.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/UserBoard.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/projects/ProjectInfoMenu.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/OrganizationView.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/fossgraph/FossGraphView.kt
* Added avatar renderers
* Improved existing `userBoard`
* Reused existing `userBoard` on `fossGraph` view
=> Participants on fossGraph view

api-gateway/src/main/resources/application-dev.yml, api-gateway/src/main/resources/application.yml, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/RegistrationView.kt
- SAVE uses '@' as a special mark to separate user and source https://github.com/saveourtool/save-cloud/issues/2336 so we cannot use e-mail as login in SAVE by for now
https://github.com/saveourtool/save-cloud/assets/58667063/a94ca093-1b58-4c99-915e-5edf2ac392cd
=> Hotfix for Google authorization

authentication-service/src/main/kotlin/com/saveourtool/save/authservice/utils/SecurityUtils.kt, save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/LnkContestProjectController.kt, save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/LnkUserOrganizationController.kt, save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/LnkUserProjectController.kt, save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/OrganizationController.kt, save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/ProjectController.kt, save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/UsersDetailsController.kt, save-backend/src/main/kotlin/com/saveourtool/save/backend/security/OrganizationPermissionEvaluator.kt, save-backend/src/main/kotlin/com/saveourtool/save/backend/security/ProjectPermissionEvaluator.kt, save-backend/src/main/kotlin/com/saveourtool/save/backend/security/VulnerabilityPermissionEvaluator.kt, save-backend/src/main/kotlin/com/saveourtool/save/backend/service/CommentService.kt, save-backend/src/main/kotlin/com/saveourtool/save/backend/service/ContestSampleService.kt, save-backend/src/main/kotlin/com/saveourtool/save/backend/service/LnkUserOrganizationService.kt, save-backend/src/main/kotlin/com/saveourtool/save/backend/service/LnkUserProjectService.kt, save-backend/src/main/kotlin/com/saveourtool/save/backend/service/ProjectProblemService.kt, save-backend/src/main/kotlin/com/saveourtool/save/backend/service/vulnerability/VulnerabilityService.kt, save-backend/src/test/kotlin/com/saveourtool/save/backend/security/ConverterTest.kt
- small refactoring to hide AuthenticationDetails to get userId and identitySource
It's part of #2336
=> Hide `AuthenticationDetails` from BL

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/utils/LoginUtils.kt
* Replaced `Link` with `a` for oauth logging in
=> Hotfix for broken authorization links

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/ManageUserRoleCard.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/contests/ContestCreationComponent.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/organizations/OrganizationContestsMenu.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/organizations/OrganizationVulnerabilitiesTab.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/OrganizationView.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/utils/ChildrenBuilderUtils.kt
* Added placeholder suggestions (e.g. create first contest etc.)
* Replaced old text buttons with new label buttons on `organizationContestsMenu`
https://github.com/saveourtool/save-cloud/assets/35039155/a05b4c79-9268-467c-bc12-33a95ec95274
=> Table placeholders follow-ups

api-gateway/src/main/kotlin/com/saveourtool/save/gateway/security/WebSecurityConfig.kt, api-gateway/src/main/resources/application-dev.yml, api-gateway/src/main/resources/application.yml, authentication-service/src/main/kotlin/com/saveourtool/save/authservice/config/WebSecurityConfig.kt, save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/DemoManagerController.kt, save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/validation/BackendRoutes.kt, save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/validation/ValidationUtils.kt, save-demo-agent/src/nativeMain/kotlin/com/saveourtool/save/demo/agent/utils/SetupUtils.kt, save-demo-cpg/src/main/kotlin/com/saveourtool/save/demo/cpg/controller/CpgController.kt, save-demo/src/main/kotlin/com/saveourtool/save/demo/controller/DemoController.kt, save-demo/src/main/kotlin/com/saveourtool/save/demo/controller/DependencyController.kt, save-demo/src/main/kotlin/com/saveourtool/save/demo/controller/ManagementApiController.kt, save-demo/src/main/kotlin/com/saveourtool/save/demo/controller/ManagementController.kt, save-demo/src/main/kotlin/com/saveourtool/save/demo/utils/KubernetesUtils.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/App.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/OrganizationAdminView.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/SandboxView.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/utils/RequestUtils.kt, save-frontend/webpack.config.d/dev-server.js, save-sandbox/src/main/kotlin/com/saveourtool/save/sandbox/controller/SandboxController.kt, save-sandbox/src/main/kotlin/com/saveourtool/save/sandbox/controller/SandboxInternalController.kt, save-sandbox/src/main/kotlin/com/saveourtool/save/sandbox/service/SandboxOrchestratorAgentService.kt
* Changed `/demo/api` -> `/api/demo`
* Changed `/cpg/api` -> `/api/cpg`
* Changed `/sandbox/api` -> `/api/sandbox`
* Changed `/demo/internal` -> `/internal/demo`
* Changed `/sandbox/internal` -> `/internal/sandbox`
* Added BackendRoutes in order to forbid some high-level url path segments e.g. `api`, `sec`, `grafana` etc.
* Reworked `App` to be `FC`
=> Hide all backend endpoints under `/api` and `/internal`

save-frontend/README.md, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/App.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/RegistrationView.kt
* Removed redirect to `/registration` if user is created and is on `/terms-of-use` view
* Removed `**.ico`, `**.png` from `README.md#Using OAuth with a local deployment` (I'm done with `431` error)
* Made `I agree with terms of use` label be not clickable - you must now click the checkbox
=> Terms of Use view should be available for unregistered users

save-orchestrator-common/src/test/kotlin/com/saveourtool/save/orchestrator/docker/DockerContainerManagerTest.kt
Without any reason this test started to fail. Looks like it happened due to some image update, so the inspectContainerResponse was changed on image side: 
1) run cmd became: 
```
bash
-c
env $(cat /home/save-agent/.env | xargs) sh -c "./script.sh"
```
from 
```
-c
env $(cat /home/save-agent/.env | xargs) sh -c "./script.sh"
```
2) `path = "bash"` -> `path = "/entrypoint.sh"`
=> Hotfix for a DockerContainerManagerTest

db/v-2/tables/tags.xml, save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/TagController.kt
* Now returning only distinct tags
* Added unique constraint to `tag` table for `name` column
=> Hotfix for vulnerability tags duplicates

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/vuln/VulnerabilityView.kt
* Changed redirect from `FrontendRoutes.VULN` to `FrontendRoutes.VULNERABILITIES`
=> Hotfix for redirects after vulnerability reject/deletion

save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/validation/FrontendRoutes.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/App.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/BanView.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/ThanksForRegistrationView.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/externals/i18next/InitI18n.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/externals/i18next/locales/Translations.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/routing/BasicRouting.kt
* Added `thanksForRegistrationView`
* Added translations for `thanksForRegistrationView`
=> ThanksForRegistrationView

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/RegistrationView.kt
* Added `textarea` on `registrationView` to fill personal info
=> Let users add some info on registration

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/inputform/InputTextFormRequired.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/RegistrationView.kt
* Added `GitHub` input field to `registrationView`
* Added website input field to `registrationView`
* Made `GitHub` required for registration
=> Add GitHub on registration

api-gateway/src/main/resources/application.yml, save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/vulnerability/VulnerabilityController.kt, save-backend/src/main/kotlin/com/saveourtool/save/backend/service/vulnerability/VulnerabilityService.kt, save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/entities/vulnerability/VulnerabilityDateType.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/HasErrorModal.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/TimelineComponent.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/usersettings/SettingsView.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/vuln/VulnerabilityGeneralInfo.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/vuln/VulnerabilityHeader.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/vuln/VulnerabilityInfoTab.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/vuln/VulnerabilityTagsComponent.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/vuln/VulnerabilityView.kt, save-frontend/src/main/resources/scss/_utilities.scss, save-frontend/src/main/resources/scss/utilities/_ribbon.scss, save-frontend/src/main/resources/scss/utilities/_timeline.scss
- Minor Spring Security Timeout update (not tested)
- Propagating edit button actions to have a common editable page
- Adding creation date to timeline (so it's always shown)
- Adding ribbon for approved/not approved
- Fix for editing short and long description
- Minor fixes
https://github.com/saveourtool/save-cloud/assets/58667063/c2b7c74c-1c54-4490-a621-5113ddfca1fb
=> Editing view preparations: propagating of edit flag to children components

api-gateway/src/main/kotlin/com/saveourtool/save/gateway/security/WebSecurityConfig.kt
* Added `/api/$v1/avatar/**` to `allowedForInactiveEndpoints`
* Supported unauthorized users in gateway `WebSecurityConfig`
=> Hotfix for gateway user status check

save-agent/src/commonMain/kotlin/com/saveourtool/save/agent/SaveAgent.kt
- Setup.sh will be executed only from `TEST_SUITES_DIR_NAME`
=> Hotfix for agent setup.sh execution

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/RegistrationView.kt
- When status is undefined on first rendering we make a loop of redirections
=> Hotfix for registration redirect for first rendering

db/v-2/tables/vulnerability-metadata.xml, save-cosv/src/main/kotlin/com/saveourtool/save/cosv/service/VulnerabilityMetadataService.kt
- Set first 35 letters of details as summary on creating or updating metadata
- Update database
It closes #2645
=> Set first 35 letters of details as summary

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/table/filters/VulnerabilitiesFiltersRow.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/vuln/VulnerabilityCollectionView.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/vuln/VulnerabilityGeneralInfoProps.kt, save-frontend/src/main/resources/locales/cn/table-headers.json, save-frontend/src/main/resources/locales/cn/vulnerability.json, save-frontend/src/main/resources/locales/en/table-headers.json, save-frontend/src/main/resources/locales/en/vulnerability.json, save-frontend/src/main/resources/locales/ru/table-headers.json, save-frontend/src/main/resources/locales/ru/vulnerability.json
- "Author" renamed, both as the key and as the translated string.
- Chinese (CN) translation left intact.
=> Rename "Author" -> "COSV Submitter" in the UI

save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/utils/Constants.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/vuln/VulnerabilityGeneralInfoProps.kt
- Now, the button's label changes according to the UI locale currently selected.
- The trailing space is not a part of the translation.
=> Make sure the "Edit" button has an i18n-ed label

save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/utils/StringUtils.kt, save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/validation/ValidationUtils.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/userprofile/UserProfileView.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/usersettings/SettingsViewLeftColumn.kt
- `isLengthOk` function has been changed so that in boundary cases number of characters matches maximum allowed length.
- added `shortenLoginWithTooltipIfNecessary` and `shortenRealNameWithTooltipIfNecessary` functions for names validation into their placeholders, which are in UserProfileView and SettingsView.
- added `shorten` function to shorten any string.
- added `shortenLogin` and `shortenRealName` functions to shorten strings of login and real name.
Closes #1195
=> Fixed long usernames don't fit into their placeholders.

save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/entities/cosv/VulnerabilityMetadataDto.kt, save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/utils/Constants.kt, save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/utils/StringUtils.kt, save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/entities/cosv/VulnerabilityMetadata.kt, save-cosv/src/main/kotlin/com/saveourtool/save/cosv/service/VulnerabilityMetadataService.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/ExecutionView.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/vuln/VulnerabilityGeneralInfoProps.kt
- The check is implemented on both the front-end and the back-end side.
- No more SQL exceptions when attempting to store a long summary.
- If the text exceeds the length (currently, 250 chars), then the Unicode Ellipsis (U+2026) is appended to the truncated string.
=> Shorten the `VulnerabilityMetadata.summary` if it exceeds the maximum allowed length

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/projects/ProjectSettingsMenu.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/OrganizationAdminView.kt
- It's now possible to navigate to an organization from the "Manage Organizations" admin-only view.
- It's now possible to delete a project from the settings of this very project (not from the project list).
- Fixes #2730.
=> Fix broken navigation to an organization

renovate.json
- locked version in renovate
It's part of #2221 and #2826
=> Lock `org.jetbrains.kotlin-wrappers:kotlin-wrappers-bom:1.0.0-pre.634`

renovate.json
- split "helm-values" and "helmv3"
- reordered according to `Dependency Dashboard`
- removed group names for automatic dependencies
It closes #2829
=> Lock Grafana stack in Renovate

save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/organizations/OrganizationContestsMenu.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/organizations/OrganizationToolsMenu.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/projects/ProjectStatisticMenu.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/table/filters/VulnerabilitiesFiltersRow.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/userprofile/UserProfileNewUsersTab.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/userprofile/UserProfileView.kt, save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/vuln/VulnerabilityTableComponent.kt
- vulnerabilities and users tabs are now only displayed if there are new users to approve.
- added text centering in tables on user, organization and project pages.
- added colors for `Status` field depending on its value in the vulnerability table.
- added colors for `Criticality` field depending on its value in the vulnerability table.
Closes #2643
=> Fixed text displaying in tables on user and organization pages

save-demo/build.gradle.kts, save-orchestrator-common/build.gradle.kts, save-orchestrator/build.gradle.kts
- added exclusion for `org.slf4j` in `io.fabric8:kubernetes-client`
=> Fixed broken logs in orchestrators

save-cloud-charts/save-cloud/templates/backend-deployment.yaml, save-cloud-charts/save-cloud/templates/demo-deployment.yaml, save-cloud-charts/save-cloud/templates/gateway-deployment.yaml, save-cloud-charts/save-cloud/templates/sandbox-deployment.yaml, save-cloud-charts/save-cloud/values.yaml
updated configs to be able to use also in HIS cloud by providing correct values when deploy via Helm
=> updated deployments config for HIS usecase

gradle/wrapper/gradle-wrapper.properties
- removed checksum since renovate cannot upgrade in such case
=> Removed checksum for gradle-wrapper

frontend-common/src/main/kotlin/com/saveourtool/frontend/common/components/basic/AvatarRenderers.kt, frontend-common/src/main/kotlin/com/saveourtool/frontend/common/components/inputform/InputWithDebounce.kt
=> Fixed organization render avatar in vulnerability filters

gradle/plugins/src/main/kotlin/com/saveourtool/save/buildutils/PublishingConfiguration.kt
- Removed `dokkaJar` as it causes compatibility problems with IDEA 2024.2.1+
=> Remove `dokkaJar` from the list of published JAR artifacts

common/build.gradle.kts, save-demo-agent/build.gradle.kts
- `macosX64` target removed (because `:common` depends on `cosv4k` which doesn't provide `macosX64`-specific publications);
- no more project resolution problems in IDEA 2024.1+;
- fixes #2972.
=> Remove `macosX64` target as it's causing problems with IDEA 2024.1+

gradle/plugins/src/main/kotlin/com/saveourtool/save/buildutils/PublishingConfiguration.kt, save-cloud-common/build.gradle.kts, save-demo-agent/build.gradle.kts
Cherry-picked the content of the following PRs from `feature/untested-release`:
- #2971 
- #2973
=> Cherry-pick IDEA 2024.1+ specific fixes from `feature/untested-release`

common/src/jvmMain/kotlin/com/saveourtool/common/storage/BackupStorageUtils.kt
- backup storage utils expects ID in s3 path after a common prefix, it leads to number exception
=> Supporting invalid path in BackupStorageUtils

save-cloud-charts/save-cloud/README.md
Updated information in chart readme about secrets
=> Updated information about secrets
